### PR TITLE
grand premmision for plugin testcomplete11-xunit

### PR DESCRIPTION
**Pull request by mgaert**
# Description

Plugin which will be hosted: https://github.com/mgaert/testcomplete11-xunit-plugin
HOSTING:  https://issues.jenkins-ci.org/browse/HOSTING-392
# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
This does not appear to be an existing plugin, and I cannot find the sources. Please provide references indicating otherwise, or review the checklist, as well as https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins. Thanks.

**Comment by mgaert** [comment]
The Hosting process is not finished jet https://issues.jenkins-ci.org/browse/HOSTING-392
I will add here a comment if this is done.

**Comment by daniel-beck** [comment]
@mgaert Thanks, tagged accordingly. Please also note the last section of the checklist, which does apply here as well.

**Comment by mgaert** [comment]
The Hosting process "https://issues.jenkins-ci.org/browse/HOSTING-392" is now finished.

**Pull request merged**
