### PR TITLE
Update plugin-veracode-scan.yml

### PR DESCRIPTION
**Pull request by dennisgu1**
Change path for compatibility issue.

# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by slide** [comment]
You didn't check any boxes or provide the information requested in the PR template.

**Comment by dennisgu1** [comment]
@slide , we changed our group id in pom.xml file in our Jenkins plugin open source repo, so I think we need to update this path so that we can have permission to push, am I right? thank you!

**Comment by slide** [comment]
Yes, if you change the groupId you need to change this file, but you didn't provide any information that is requested in the PR template.

**Comment by dennisgu1** [comment]
@slide, sorry about that, we just want to compatible with our old plugin, so I have to change it, is it good enough now? do you need me provide more information? please let me know, thanks.

**Comment by slide** [comment]
There is a section titled Always, you need to at least provide the information that is requested there

**Comment by dennisgu1** [comment]
Hi @slide , got it.
Our plugin Git Repo is:
https://github.com/jenkinsci/veracode-scan-plugin

We have changed group id in our "group-id" branch:
   ```
<groupId>com.veracode.jenkins</groupId>
   <artifactId>veracode-scan</artifactId>
```

and we will merge it to dev/master branch after this pull request is approved, thank you!

**Pull request merged**
