### PR TITLE
Update developers on permissions to bigpanda plugin

### PR DESCRIPTION
**Pull request by julioguereca**
# Description

Updating the list of developers for the bigpanda-plugin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above
https://github.com/jenkinsci/bigpanda-plugin

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
To merge this PR, the following users need to log into Jira https://issues.jenkins.io/ and artifactory https://repo.jenkins-ci.org/ui/login
- @julioguereca 
- @JuanDCardozo
- @cjcrist
- @goodwinjeremyr
- @shikha-gaur
- @PaulBaker27
- @lukej7

**Comment by julioguereca** [comment]
@NotMyFault All users above should have logged in by now

**Comment by NotMyFault** [comment]
> @NotMyFault All users above should have logged in by now

The only users who logged into artifactory and jira are lukej7 and goodwinjeremyr. All others are still to go.

**Comment by julioguereca** [comment]
@NotMyFault For myself, I have a `jguereca` user but since my github user is `julioguereca` should I be creating a new account? I did log into both sites with my `jguereca` account but from the sound of it, its not synced with my github user `julioguereca`

**Comment by julioguereca** [comment]
@NotMyFault I've also just talked to two of my engineers @cjcrist and @shikha-gaur and confirmed they did log into both of these sites last week. They have gone and logged in again just now

**Comment by NotMyFault** [comment]
> @NotMyFault For myself, I have a `jguereca` user but since my github user is `julioguereca` should I be creating a new account? I did log into both sites with my `jguereca` account but from the sound of it, its not synced with my github user `julioguereca`

The developer names listed are LDAP account names, acting completely independent of GitHub usernames. Please ensure all names listed match the name of the account people log into our services, and not their GitHub names.

**Comment by julioguereca** [comment]
@NotMyFault Ok, I got it now. I was using their GitHub users not their newly created Jenkins users. I have updated it so hopefully you can see all developers have logged in.

**Comment by NotMyFault** [comment]
> @NotMyFault Ok, I got it now. I was using their GitHub users not their newly created Jenkins users.

Thanks. `pbaker ` just needs to log into Jira https://issues.jenkins.io/ and all checks will pass.

**Comment by julioguereca** [comment]
@NotMyFault I saw him log into that site yesterday and just confirmed he logged in right now with that user.

**Review by NotMyFault — APPROVED** [review]
The PR will merge itself once all conditions are satisfied.

**Pull request merged**
