### PR TITLE
Adopt git-bisect plugin

### PR DESCRIPTION
**Pull request by ktsiligkiris**
# Description

Adopt the git bisect plugin.

Repository: https://plugins.jenkins.io/git-bisect/ 

Previous maintainer: @dorav (but since it is listed as "up for adoption", no need to wait for two weeks timeout)

GitHub user to be added: @ktsiligkiris 

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@ktsiligkiris you'll need to login to https://repo.jenkins-ci.org with the username `antepenult` and the jenkins.io password for that username.  About an hour after that login, we can run the checks for this pull request again.

**Review by basil — APPROVED** [review]

**Comment by ktsiligkiris** [comment]
OK, logged in to jfrog, and to jira also.

**Comment by halkeye** [comment]
Added you to the project team.
If you are not already a member of the org, please accept the org invite, or goto https://github.com/jenkinsci/ and accept it via ui there.

**Comment by basil** [comment]
Glad to see someone picking up where I left off. Welcome aboard!

**Pull request merged**
