### PR TITLE
Adding my new user in Jenkins Community/Artifactory

### PR DESCRIPTION
**Pull request by dneduva1**
# Description

https://github.com/jenkinsci/securecn-scanner-plugin @dneduva1 

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
This section is used for artifactory authentication. It's not used for CD. A quick glance over your repository reveals a few CD mistakes.
- You forgot to setup release drafter, the action which publishes releases. See https://www.jenkins.io/doc/developer/publishing/releasing-cd/#configure-release-drafter
- https://github.com/jenkinsci/securecn-scanner-plugin/blob/ca86182eb11d1fd8c289ac8658b71376fd06a4ca/pom.xml#L38 should be `scm:git:https`, git:git is deprecated.

**Comment by dneduva1** [comment]
Awesome, thank you for all this assistance! I am not sure why the validation didn't go through, I did login with that user

**Comment by NotMyFault** [comment]
> I am not sure why the validation didn't go through

It's refreshed hourly, I'll go ahead and merge it, once it passes.

**Comment by dneduva1** [comment]
@NotMyFault Hey I am still getting 403 errors, do you have an idea why? it seems that the setup is abiding by the docs

**Comment by NotMyFault** [comment]
Looks all good to me: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/portshift-scanner/34.v2a_997225850b/

The release has been published successfully.

**Comment by dneduva1** [comment]
> Looks all good to me: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/portshift-scanner/34.v2a_997225850b/
> 
> The release has been published successfully.

Yup but I am getting the following in the GitHub actions cd:
image
and not seeing it when I browse for the plugin in the https://plugins.jenkins.io/

**Comment by NotMyFault** [comment]
> > Looks all good to me: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/portshift-scanner/34.v2a_997225850b/
> 
> > 
> 
> > The release has been published successfully.
> 
> 
> 
> Yup but I am getting the following in the GitHub actions cd:
> 
> image
> 
> and not seeing it when I browse for the plugin in the https://plugins.jenkins.io/

I'm not able to look into that right now. I'd recommend you raise an issue on the Helpdesk: https://github.com/jenkins-infra/helpdesk/issues

**Comment by slide** [comment]
See https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-403-forbidden

**Pull request merged**
