### PR TITLE
Update plugin-redgate-sql-ci.yml

### PR DESCRIPTION
**Pull request by lubosmichalic**
Repository:

https://github.com/jenkinsci/redgate-sql-ci-plugin

My commits:

https://github.com/jenkinsci/redgate-sql-ci-plugin/commits?author=lubosmichalic

Existing maintainer: @petergerrard

- [x] Add link to plugin/component Git repository in description above
- [x] Make sure to @mention an existing maintainer to confirm the permissions request, if applicable
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] All newly added users have logged in to Artifactory at least once

### CODE REVIEW

**Comment by PeterGerrard** [comment]
I'm good for @lubosmichalic to be added

**Comment by batmat** [comment]
`Exception in thread "main" java.lang.IllegalStateException: User name not known to Artifactory: lubosmichalic`

**Comment by lubosmichalic** [comment]
image
I've logged in previously, is there a time this may take to register?

**Comment by batmat** [comment]
Normally nope. Can you double-check there's no typo in your username. Going to retrigger the check here in case.

**Comment by batmat** [comment]
Either there was an issue, or your login just now fixed, but now seems fine.

**Pull request merged**
