### PR TITLE
add performance-signature-dynatracesaas as new plugin

### PR DESCRIPTION
**Pull request by rpionke**
# Description
We created a new maven module for the Dynatrace Saas/Managed solution in the Performance Signature. We are also using the same Github repository: https://github.com/jenkinsci/performance-signature-dynatrace-plugin.
Plugin Links:
https://wiki.jenkins.io/display/JENKINS/Performance+Signature+with+Dynatrace+Plugin
https://plugins.jenkins.io/performance-signature-dynatrace

### Always

- [x] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### CODE REVIEW

**Comment by daniel-beck** [comment]
This looks weird. I recommend another hyphen in there.

**Comment by daniel-beck** [comment]
Note that `robkuehn` is allowed to release all other modules, just not this one.

**Comment by rpionke** [comment]
Yeah i know, the plugin naming is not ideal.
robkuehn is my colleague, i trust him ;)

**Comment by daniel-beck** [comment]
@rpionke Oops -- I didn't see that entry in this file and thought he was missing. Nevermind then.

**Pull request merged**
