### PR TITLE
Adopt plugin-next-executions

### PR DESCRIPTION
**Pull request by jonesbusy**
# Description

Adopt abandoned plugin-next-executions : https://github.com/jenkinsci/next-executions-plugin

I want to deliver https://github.com/jenkinsci/next-executions-plugin/pull/9 that is a refresh of the plugin

FYI @ialbors

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by jonesbusy** [comment]
Posted on dev list : https://groups.google.com/u/1/g/jenkinsci-dev/c/v4UPwA6q5Ts

**Comment by NotMyFault** [comment]
cc @ialbors

**Comment by jonesbusy** [comment]
Maintainer was ping on https://github.com/jenkinsci/next-executions-plugin/pull/9 more than 1 month ago. No answer

**Comment by NotMyFault** [comment]
> Maintainer was ping on [jenkinsci/next-executions-plugin#9](https://github.com/jenkinsci/next-executions-plugin/pull/9) more than 1 month ago. No answer

I see, thanks for the pointer. In that case, I'll skip the waiting period, if the maintainer moved on.

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
