### PR TITLE
Add permission file for fips-bundle-test

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

# Link to GitHub repository

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- @olamy
- @jtnord 

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Review by jtnord — APPROVED** [review]
would be nice to have CD from the start though :)

**Comment by olamy** [comment]
> would be nice to have CD from the start though :)

sure let's make some marketing for GHA :)

https://github.com/jenkins-infra/repository-permissions-updater/pull/4083/commits/657b3d76214271cd20cde314602440e45a661d40

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
CD hasn't been properly set up, there's now a `-rcwhatever` release. That's why there's a checklist item specifically for CD enablement  😉 

> Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.
> In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

**Comment by olamy** [comment]
hopefully should be fixed here https://github.com/jenkinsci/lib-fips-bundle-test/pull/2

**Comment by olamy** [comment]
this is fixed but the first release will break dependabot :( 

https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/test/fips/lib-fips-bundle-test/-rc16.e95456a_916d7/

I can see solutions:
- change the artifactId to `fips-bundle-test` (as mentioned here https://github.com/jenkins-infra/repository-permissions-updater/pull/4085#issuecomment-2347082147)
- delete the release -rc16.e95456a_916d7 from artifactory (I hope this will cleanup metadata.xml
- another solution?
-

**Comment by timja** [comment]
Change the artifact id would be the smoothest I think

**Comment by olamy** [comment]
done here   https://github.com/jenkins-infra/repository-permissions-updater/pull/4089

**Comment by olamy** [comment]
@timja thanks for your patience!

**Pull request merged**
