### PR TITLE
Enable CD permission for plugin-jetbrains-space

### PR DESCRIPTION
**Pull request by Kiryushin-Andrey**
# Link to GitHub repository

https://github.com/JetBrains/space-jenkins-plugin

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@username1`
- `@username2`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/jetbrains-space-plugin/pull/7

```[tasklist]
### CD checklist (for submitters)
- [X] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
Looks good so far, but be aware that cd will not work if your build is not green.

**Comment by Kiryushin-Andrey** [comment]
> Looks good so far, but be aware that cd will not work if your build doesn't pass all checks on ci.Jenkins.io

Ok, then I have a question about those checks :) They fail to fetch `org.jetbrains:space-sdk-jvm` dependency - ` Could not find artifact org.jetbrains:space-sdk-jvm:jar:2024.2-178074 in aws-proxy (https://repo.aws.jenkins.io/public/)`. But this dependency comes from https://maven.pkg.jetbrains.space/public/p/space/maven that is mentioned in the `pom.xml` file. Seems that the build on ci.jenkins.io for some reason ignores the repository referenced in the `pom.xml` and tried to fetch the dependency from this aws-proxy repo. So how can I either get the build to fetch the dependency from the right repo, or get this dependency published into the https://repo.aws.jenkins.io/public ?

**Comment by NotMyFault** [comment]
> I guess adding `useArtifactCachingProxy: false` to Jenkinsfile will help, but maybe I can use proxying for all the dependencies except this one?

I've exempted it in https://github.com/NotMyFault/jenkins-infra/commit/0951ba7537733286756b910da0d3b05ca1e92316

**Comment by NotMyFault** [comment]
For documentation purposes: https://github.com/jenkins-infra/helpdesk/issues/3973

**Pull request merged**
