### PR TITLE
Converted Groovy classes to Java

### PR DESCRIPTION
**Pull request by Giridharan002**
This pull request updates the project by converting all Groovy classes to Java,
The changes were made to improve performance and to make the codebase more maintainable in the long run.

Issue: #3028

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@Giridharan002 thanks for the pull request.  It fails the continuous integration job with the message:

```
08:32:11  [ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:2.1.0:compile (default) on project repository-permissions-updater: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
08:32:11  [ERROR] /home/jenkins/agent/workspace/tory-permissions-updater_PR-3207/src/main/groovy/io/jenkins/infra/repository_permissions_updater/ArtifactoryPermissionsUpdater.groovy: 453: Apparent variable 'ArtifactoryAPI' was found in a static scope but doesn't refer to a local variable, static field or class. Possible causes:
08:32:11  [ERROR] You attempted to reference a variable in the binding or an instance variable from a static context.
08:32:11  [ERROR] You misspelled a classname or statically imported field. Please check the spelling.
08:32:11  [ERROR] You attempted to use a method 'ArtifactoryAPI' but left out brackets in a place not allowed by the grammar.
08:32:11  [ERROR]  @ line 453, column 30.
08:32:11  [ERROR]            def artifactoryApi = ArtifactoryAPI.getInstance()
08:32:11  [ERROR]                                 ^
08:32:11  [ERROR] 
08:32:11  [ERROR] 1 error
08:32:11  [ERROR] -> [Help 1]
```

Can you investigate further and resolve that issue?

**Comment by Giridharan002** [comment]
> @Giridharan002 thanks for the pull request. It fails the continuous integration job with the message:
> 
> ```
> 08:32:11  [ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:2.1.0:compile (default) on project repository-permissions-updater: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
> 08:32:11  [ERROR] /home/jenkins/agent/workspace/tory-permissions-updater_PR-3207/src/main/groovy/io/jenkins/infra/repository_permissions_updater/ArtifactoryPermissionsUpdater.groovy: 453: Apparent variable 'ArtifactoryAPI' was found in a static scope but doesn't refer to a local variable, static field or class. Possible causes:
> 08:32:11  [ERROR] You attempted to reference a variable in the binding or an instance variable from a static context.
> 08:32:11  [ERROR] You misspelled a classname or statically imported field. Please check the spelling.
> 08:32:11  [ERROR] You attempted to use a method 'ArtifactoryAPI' but left out brackets in a place not allowed by the grammar.
> 08:32:11  [ERROR]  @ line 453, column 30.
> 08:32:11  [ERROR]            def artifactoryApi = ArtifactoryAPI.getInstance()
> 08:32:11  [ERROR]                                 ^
> 08:32:11  [ERROR] 
> 08:32:11  [ERROR] 1 error
> 08:32:11  [ERROR] -> [Help 1]
> ```
> 
> Can you investigate further and resolve that issue?

Certainly! I will investigate and resolve the issue with the pull request.

**Comment by Giridharan002** [comment]
> @Giridharan002 thanks for the pull request. It fails the continuous integration job with the message:
> 
> ```
> 08:32:11  [ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:2.1.0:compile (default) on project repository-permissions-updater: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
> 08:32:11  [ERROR] /home/jenkins/agent/workspace/tory-permissions-updater_PR-3207/src/main/groovy/io/jenkins/infra/repository_permissions_updater/ArtifactoryPermissionsUpdater.groovy: 453: Apparent variable 'ArtifactoryAPI' was found in a static scope but doesn't refer to a local variable, static field or class. Possible causes:
> 08:32:11  [ERROR] You attempted to reference a variable in the binding or an instance variable from a static context.
> 08:32:11  [ERROR] You misspelled a classname or statically imported field. Please check the spelling.
> 08:32:11  [ERROR] You attempted to use a method 'ArtifactoryAPI' but left out brackets in a place not allowed by the grammar.
> 08:32:11  [ERROR]  @ line 453, column 30.
> 08:32:11  [ERROR]            def artifactoryApi = ArtifactoryAPI.getInstance()
> 08:32:11  [ERROR]                                 ^
> 08:32:11  [ERROR] 
> 08:32:11  [ERROR] 1 error
> 08:32:11  [ERROR] -> [Help 1]
> ```
> 
> Can you investigate further and resolve that issue?

Certainly! I would be happy to investigate and resolve the issue with the pull request.

**Comment by MarkEWaite** [comment]
Closing the pull request after 2 months of inactivity.  It can be reopened in the future if activity resumes.

**Pull request closed without merging**
