### PR TITLE
add plugin-blueocean-pipeline-scm-api.yml

### PR DESCRIPTION
**Pull request by i386**
# Description

We are adding a new module to blue ocean for the pipeline-scm-api

# Permissions pull request checklist

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by i386** [comment]
@vivek please approve

**Comment by vivek** [comment]
LGTM 🐝

**Comment by daniel-beck** [comment]
It seems this is about https://github.com/jenkinsci/blueocean-plugin/pull/1042. What happened to https://github.com/jenkins-infra/repository-permissions-updater/pull/306?

**Comment by i386** [comment]
@vivek and I realised an error with the naming

**Comment by i386** [comment]
@daniel-beck I have done so in this PR. Sorry for the flux here.

**Comment by daniel-beck** [comment]
No problem, but I'd like to hold this until the PR is merged just to be safe ;-) Otherwise looks good 👍

**Comment by michaelneale** [comment]
yes once blue ocean PR is merged, @i386 post back here to let daniel know. We probably should think harder about names to avoid this churn.

**Pull request merged**
