### PR TITLE
sshd-module: Grant oleg_nenashev and kohsuke release permissions

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Required for the release of https://github.com/jenkinsci/sshd-module/pull/6

CC @aheritier

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
IMHO it should be relamed to "module-sshd.yml" as well as other modules

**Comment by daniel-beck** [comment]
> IMHO it should be [renamed] to "module-sshd.yml" as well as other modules

Feel free to do so (and adapt the README).

**Comment by aheritier** [comment]
+1 for the rights (thx @oleg-nenashev ) and for the renaming

**Comment by oleg-nenashev** [comment]
> Feel free to do so (and adapt the README).

Will do in a follow-up PR

**Comment by daniel-beck** [comment]
@oleg-nenashev Could we please not create origin branches?

**Pull request merged**
