### PR TITLE
Add @stephen-badger as a maintainer of metrics

### PR DESCRIPTION
**Pull request by stephen-badger**
# Description

https://github.com/jenkinsci/metrics-plugin

As suggested by @stephenc 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by batmat** [comment]
Hello, seems like you ignored the template. It is here for a reason :). Can you please check *all* boxes, and mark possibly _N/A_ the ones that are not applicable to show you've processed the entry. Thanks!

**Comment by stephen-badger** [comment]
@stephenc

**Comment by stephen-badger** [comment]
@batmat updated PR description accordingly

**Comment by batmat** [comment]
@stephen-badger seems like your account could not be found in Artifactory, but you did check the corresponding checkbox:
image

**Comment by oleg-nenashev** [comment]
We need an Artifactory admin like @daniel-beck to verify. Are you sure you logged in to Artifactory, not JIRA?

**Comment by stephen-badger** [comment]
I'm positive I am logged in to Artifactory:
https://gist.github.com/stephen-badger/2b2dd7841e3b9d9b1489f4ad5f0c5f29#file-sbadger-logged-in-wider-png

I am also logged in JIRA and Confluence too, but I don't imagine that affects anything here?

**Comment by daniel-beck** [comment]
Probably just the PR build needing a kick.

**Comment by daniel-beck** [comment]
I'm psychic 😆 

Closing & reopening PRs triggers a new PR build and doesn't need Artifactory admin access.

**Pull request merged**
