### PR TITLE
plugin-accurev.yml update as required for adoption. Removal of two contributors (@poojavishal and @abmohantyj) who are not with OpenText anymore.

### PR DESCRIPTION
**Pull request by aamanchaopentext**
# Link to GitHub repository

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@aamanchaopentext`
- `@mkasaramoni`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation.
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by alecharp** [comment]
As you are removing 2 users from being able to release the plugin, we would require both of them to approve this pull requests.
Please edit the pull request description to mention them there.

**Comment by aamanchaopentext** [comment]
Removed two maintainers who are not contributing anymore and not with OpenText Pvt Ltd. anymore.

**Comment by timja** [comment]
> As you are removing 2 users from being able to release the plugin, we would require both of them to approve this pull requests. Please edit the pull request description to mention them there.

Mention them yes, but we don't require approval to remove if someone with existing access has requested it, as normally in this case they never reply, often don't use those github accounts anymore

**Comment by aamanchaopentext** [comment]
> > As you are removing 2 users from being able to release the plugin, we would require both of them to approve this pull requests. Please edit the pull request description to mention them there.
> 
> Mention them yes, but we don't require approval to remove if someone with existing access has requested it, as normally in this case they never reply, often don't use those github accounts anymore

True. They are not contributing anymore and not with OpenText org anymore.

**Comment by timja** [comment]
Please @ mention their github usernames

**Comment by aamanchaopentext** [comment]
> Please @ mention their github usernames

Mentioned in PR description

**Comment by timja** [comment]
I can't see in the description only in the title which won't mention them.
Editing it in the description also won't mention them, you need to add a new comment

**Comment by aamanchaopentext** [comment]
> I can't see in the description only in the title which won't mention them. Editing it in the description also won't mention them, you need to add a new comment

Added in comment. It should mention them now.

**Comment by timja** [comment]
Ok given you don't have access an existing maintainer will need to approve it:

@alanharder @PoojaVishal @jsherwood-accurev @abmohantyj @AldenPratt

**Review by abmohantyj — APPROVED** [review]

**Comment by aamanchaopentext** [comment]
> As you are removing 2 users from being able to release the plugin, we would require both of them to approve this pull requests. Please edit the pull request description to mention them there.

Can you please check now? One of the old contributors approved

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Thanks, please go to https://github.com/jenkinsci to accept the invitation.

**Pull request merged**
