### PR TITLE
enable CD for the Applitools-Eyes plugin

### PR DESCRIPTION
**Pull request by itaibh**
### Plugin repository:
https://github.com/jenkinsci/applitools-eyes-plugin

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

https://github.com/jenkinsci/applitools-eyes-plugin/pull/14

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by itaibh** [comment]
I'm not sure how to *provide a reference that shows you have commit permissions*.

**Comment by itaibh** [comment]
I also don't know or don't have the username and password for jenkins' Jira and Artifactory.

**Comment by timja** [comment]
Can you add the pull request that enables CD in your plugin please?
https://www.jenkins.io/doc/developer/publishing/releasing-cd/

> Add a link to the pull request, which enables continuous delivery for your plugin or component.
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

**Comment by itaibh** [comment]
@timja I though this is the PR that does that...

**Comment by itaibh** [comment]
@timja perhaps you're referring to this:

https://github.com/jenkinsci/applitools-eyes-plugin/pull/14/files

**Comment by NotMyFault** [comment]
@itaibh If you're interested still in enabling CD according to the documentation linked above, please provide an updated link of the PR doing that.

**Pull request closed without merging**
