### PR TITLE
Create plugin-qmetry-for-jira-test-management.yaml

### PR DESCRIPTION
**Pull request by dharaghodasara**
# Description

# Submitter checklist for changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please work through the submitter checklist and ensure you've done everything it asks.

**Comment by myCodeHurts** [comment]
Revised Description:
Link to plugin/component Git repository: 
[https://github.com/jenkinsci/qmetry-for-jira-test-management-plugin](url)

Link to resolved HOSTING issue:
[https://issues.jenkins-ci.org/browse/HOSTING-364](url)

**Comment by daniel-beck** [comment]
There's still no user in Artifactory by the name `myCodeHurts`.

> All newly added users have logged in to Artifactory at least once

We don't have this checklist just to annoy you, but because it's important for the permissions system to work.

**Comment by daniel-beck** [comment]
> Check that the file is named `plugin-${artifactId}.yml` for plugins

Actual file extension is wrong.

**Comment by daniel-beck** [comment]
In the process I looked at some of your code. I added a comment to the hosting request with some issues I found.

**Comment by myCodeHurts** [comment]
Hi Daniel,
Sorry for these mistakes. Is it okay if we can create a new yml request in /repo and get rid of this one ? 

Thanks

**Comment by daniel-beck** [comment]
@myCodeHurts Sure, or just rename the file.

**Comment by dharaghodasara** [comment]
@daniel-beck  I did all the changes in source code suggested by you and updated pull request as per you comments. 
Do you think so now anything is pending from our side for this approval?

**Comment by daniel-beck** [comment]
@dharaghodasara Thanks for the update.

I would strongly prefer you follow my advice I commented in the hosting request before any releases so we don't start this with a security vulnerability.

**Comment by dharaghodasara** [comment]
@daniel-beck   
I completely agree. Thats the reason we fixed that issue yesterday only. Now we are using **Secret** for password encryption. And if you would like to review then code is also updated on repo.

**Comment by dharaghodasara** [comment]
@daniel-beck  
Can you approve this request today so we can release this plugin today? 
If you feel we should do any change before that then please let me know. I can do that quickly.

**Comment by daniel-beck** [comment]
@dharaghodasara Sorry about that, missed it when looking earlier. Do you not consider API key to be private information?

**Comment by dharaghodasara** [comment]
@daniel-beck  No, API is not private one.

**Pull request merged**
