### PR TITLE
Update plugin-fitnesse.yml

### PR DESCRIPTION
**Pull request by CSLTech**
# Description
Taking over for maintenance of fitnesse plugin. Plugin can be found at: https://github.com/jenkinsci/fitnesse-plugin
@lessonz approved change at https://groups.google.com/forum/#!msg/jenkinsci-dev/II-ishc_xfU/xq2rrChDAAAJ;context-place=forum/jenkinsci-dev
Refered by issue: https://issues.jenkins-ci.org/browse/HOSTING-532

# Submitter checklist for changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [X] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Ideally @lessonz would also confirm this here, just to be sure.

Do you still need commit access to the GitHub repo as well?

**Comment by CSLTech** [comment]
I will indeed need access to the GitHub repo as well.

**Comment by lessonz** [comment]
I'm not sure if this was directed at me. If so, I do NOT still need commit
access.

Cheers

**Comment by daniel-beck** [comment]
@lessonz Thanks! That part wasn't directed at you, sorry about that. Would still appreciate explicit overall approval of this addition to the plugin releasers / owners though.

**Comment by lessonz** [comment]
Okay, if the approval request is aimed at me, I approve.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/fitnesse-plugin/pull/35 is in the scope, I'd guess.
Merging the PR since we have an explicit approval now.

Rhanks @lessonz !

**Comment by CSLTech** [comment]
@daniel-beck The only thing missing seems to be the GitHub repo access.

Thanks

**Comment by daniel-beck** [comment]
@CSLTech Done, you should have been added to the repo, or gotten an invitation to the jenkinsci GitHub org.

**Pull request merged**
