### PR TITLE
Add permissions for plugin-openstack-heat

### PR DESCRIPTION
**Pull request by draoullig**
https://github.com/jenkinsci/openstack-heat-plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by daniel-beck** [comment]
The user `draoullig` does not exist in Artifactory. Please follow these instructions: https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by draoullig** [comment]
Hi,

I push the correct user existing in Artifactory.

Bests regards.

**Comment by daniel-beck** [comment]
@draoullig Thanks, and sorry for the delay. Most of the regular suspects are at Jenkins World right now.

**Pull request merged**
