### PR TITLE
Need to be fixed artifactID before release in Jenkins Artifactory

### PR DESCRIPTION
**Pull request by IBA-mainframe-dev**
# Description
Need to be fixed artifactID before release in Jenkins Artifactory
GitHub repository: https://github.com/jenkinsci/zos-devops-plugin
Hosting request: https://github.com/jenkins-infra/repository-permissions-updater/issues/2904

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
The `shortName` doesn't match this proposal yet, please update it too.

Also, has this plugin been released yet?

**Comment by IBA-mainframe-dev** [comment]
Thanks @NotMyFault ! I fixed the short name and also added jenkinsfile for the build.
No, .hpi haven't uploaded yet in Jenkins Artifactory.

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
I'd recommend you rename the repository and the file here too, to make it easier locating it in the future.

**Comment by IBA-mainframe-dev** [comment]
@NotMyFault, I understand your recommendation, but I corrected the name of the packages, removed the hyphen from there and from imports too, because it is undesirable to use it there. Because of this, we had to change the artifactID, but the plugin name and the repository name must be left in their current form - zos-devops-plugin, because. fully conveys its meaning - this plugin is developed and expands the possibilities for z/OS systems.

**Pull request merged**
