### PR TITLE
Add plugin-zap-pipeline.yml (https://github.com/jenkinsci/zap-pipeline)

### PR DESCRIPTION
**Pull request by vrondakis**
# Description

Adding myself as a developer to my zap-pipeline plugin. (Sorry about the last PR)

GitHub repository: https://github.com/jenkinsci/zap-pipeline-plugin
HOSTING issue: https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-646

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by vrondakis** [comment]
Could you please merge this as I would like to release, thanks

**Comment by vrondakis** [comment]
Is there anything you would like me to change so this can be merged?

**Comment by batmat** [comment]
Nope this looked good AFAICT. I marked it approved so that another pair of eyes could double check and merge, but other reviewers are busy I think. Let's move forward.

**Comment by batmat** [comment]
Nope this looked good AFAICT. I marked it approved so that another pair of eyes could double check and merge, but other reviewers are busy I think. Let's move forward.

**Pull request merged**
