### PR TITLE
Adds CD for the android emulator plugin.

### PR DESCRIPTION
**Pull request by gounthar**
# Link to GitHub repository

https://github.com/jenkinsci/android-emulator-plugin

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/android-emulator-plugin/pull/151/files

```[tasklist]
### CD checklist (for submitters)
- [X] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by timja** [comment]
You're missing the github action to actually do the releasing

**Comment by gounthar** [comment]
My bad.
Should be [ok](https://github.com/jenkinsci/android-emulator-plugin/blob/master/.github/workflows/cd.yaml) now.

**Comment by NotMyFault** [comment]
https://github.com/jenkinsci/android-emulator-plugin/blob/6ebeed93dd6e66724962fc993769468b1b72158f/pom.xml#L123 should match `<tag>${scmTag}</tag>`, in the best case.

**Comment by gounthar** [comment]
Thanks for your help, folks, and sorry for the back and forth, I think it's my first time ever. 🤷

**Pull request merged**
