### PR TITLE
adopting inodes-monitor-plugin

### PR DESCRIPTION
**Pull request by janasrikanth**
repository url: https://github.com/jenkinsci/inodes-monitor-plugin
cc: @batmat 

# Description

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@janasrikanth thanks for your willingness to adopt the plugin.

You need to login to https://repo.jenkins-ci.org with the username and password that you use to login to https://issues.jenkins.io .  If you don't have a username and password for https://issues.jenkins.io , you can create one through https://accounts.jenkins.io

**Comment by janasrikanth** [comment]
Hi @NotMyFault
I saw this plugin is not updated for a long time and is marked for adoption. So I would like to adopt it and maintain it from now onwards.
currently, I don't have any new features to add. I will work on it based on my thoughts and issues reported by users.

**Comment by MarkEWaite** [comment]
@NotMyFault since the plugin is up for adoption, I believe the pull request can be approved and merged even without involvement from previous maintainers.  I assume your CC of Baptiste was for his information, rather than because his approval is needed.  Is my assumption correct?

**Comment by NotMyFault** [comment]
> @NotMyFault since the plugin is up for adoption, I believe the pull request can be approved and merged even without involvement from previous maintainers. I assume your CC of Baptiste was for his information, rather than because his approval is needed. Is my assumption correct?

Absolutely, I noticed from contributing to core, that GitHub sometimes doesn't ping you when the mention is part of the PR body. Therefore, I mention the users again, to ensure they actually get an email, to raise awareness.

**Comment by timja** [comment]
> you when the mention is part of the PR body

It does afaik, but i don't think it does if you edit the mention in

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
Welcome aboard @janasrikanth!

Don't hesitate to join the [chat rooms](https://app.gitter.im/#/room/#jenkins-ci:matrix.org) or post on the [community forums](https://community.jenkins.io/) if you have questions.

**Comment by batmat** [comment]
Interesting, I didn't even remember I had put this one up for adoption. 

Anyway, I think this is cool. Thanks for stepping up @janasrikanth !

**Pull request merged**
