### PR TITLE
Add snowglobe plugin

### PR DESCRIPTION
**Pull request by magnayn**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@magnayn Where the plugin source code is hosted?
I do not recall the hosting request for it, so some descriptory info would be useful

**Comment by magnayn** [comment]
The jenkins part is https://github.com/nirima/SnowGlobe/tree/master/
snowglobe-jenkins - the product is in heavy co-development.

There is some project-detail at https://github.com/nirima/
SnowGlobe/blob/master/README.md, and a small example project at
https://github.com/nirima/hello-world

There's a placeholder in the wiki
https://wiki.jenkins-ci.org/display/JENKINS/SnowGlobe+Plugin which will get
filled out with some examples after I can cut a 0.0.1 (and hopefully a
call-for-paricipants on -user). I thought these got auto-pushed in the
plugin pom.xml ?

**Comment by oleg-nenashev** [comment]
CC @jenkins-infra/contributors . WDYT? I have no strong opinion. It would fine to have this plugin in the experimental UC, but I'm not sure hosting an external plugin for a work-in-progress software is what we want right now.

**Comment by magnayn** [comment]
*blink*

This is not the jenkinsci I remember...

**Comment by oleg-nenashev** [comment]
Well, it depends on people :)
The statement above is just my IMHO

**Comment by rtyler** [comment]
@magnayn We have had issues over the past couple years where plugins would maintain their source code outside of the jenkinsci GitHub Organization which makes it difficult for us to get security fixes or updates into the plugin repository if the maintainers disappear.

Our general convention has been to push plugins that wish to participate in the Jenkins project's Update Center to go through the [hosting process](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins)

**Comment by magnayn** [comment]
Which plugins would those be, and why could you not simply fork them? Is
not that the very essence of distributed version control?

Splitting the code out into a separate plugin may make sense one day, but
not whilst plugin changes and 'core tool' changes are liable to occur in
tandem, it just creates another world of pain for anyone trying to
contribute (2 PRs rather than one). Delivery via jenkinsci is a key usecase
for us - but it's not the *only* usecase.

And that's before I go into the fact that as he-who-shall-not-be-named is
in the jenkinsci organisation, I cannot shield myself from his "valuable
contributions". So unless github's features have changed and I can ban
individual org users from an individual repository, I'm loath to subject
myself to that all over again.

**Comment by oleg-nenashev** [comment]
> So unless github's features have changed and I can ban individual org users from an individual repository, I'm loath to subject myself to that all over again.

We can restrict access of jenkinsci/Everyone to the repo

> And that's before I go into the fact that as he-who-shall-not-be-named is in the jenkinsci organisation, I cannot shield myself from his "valuable contributions".

NOTE: The content below may cause a butthurt. It's just IMHO, which does not represent official position of jenkinsci org

Off-topic: Well, this person followed the process of getting push permissions to a plugin, which was unmaintained at that point. So these contributions were perfectly valid from the community standpoint. And well, they were really valuable.

**Comment by magnayn** [comment]
>
> Well, it may be the case that github now has features to control this. I
will look again at the point it makes sense to split out plugin
functionality. Certainly I don't seem to have the same control (settings)
over my projects within jenkinsci as I do outside.



> NOTE: The content below may cause a butthurt. It's just IMHO, which does
> not represent official position of jenkinsci org
>
> Off-topic: Well, this person followed the process of getting push
> permissions to a plugin, which was unmaintained at that point. So these
> contributions were perfectly valid from the community standpoint. And well,
> they were really valuable.
>

​*ahem*

In my case, person asked me for commit privs on a project *I* started and
was working on (and was in no way 'unmaintained'). They then proceeded to
demand everyone worked in the way *they* wanted, held others to a
completely different standard than their own behaviour, and was
actively ​driving potential contributors away (indeed, I got email from
someone who was not prepared to collaborate whilst they were around).

Then when he loudly proclaimed "I'm not going to work on this any more" -
but then complained when he was removed from the committers list (by the
person wanting to come in and collaborate -- and got it reversed).He also
now hangs round to loudly tell everyone that he isn't working on it any
more. Which I take as pretty childish, and fantastically rude to the people
who are donating their time and efforts for free. Everyone is free to take
their ball home if they don't like the game - but disruption from the
sidelines is just toxic.

Contributions can be valuable. But not at any cost.

**Comment by KostyaSha** [comment]
In docker-plugin i got a lot of positive feedbacks about my work to emails and a lot of negative about authors maintaining style (and still getting). People don't think that primitive blocking bugs existing for half year is `maintained` and `working on` plugin. You didn't reply to any of my comments and this is childish to complain behind the back here. All other words sounds harmful and could/will be raised to jenkins-board. Keeping in mind all this things 👎  for new such hosted plugin.

**Comment by oleg-nenashev** [comment]
I propose to return to the discussion subject. @daniel-beck @kohsuke @abayer @batmat We need more votes.

P.S: I do not think that Kostya is good at community interaction, but any contributions like Docer plugin stabilization by him are really appreciated. I'm sad that it ended up with a plugin fork, but it's how maintainers resolved their conflict there

**Comment by daniel-beck** [comment]
I'm with @rtyler. Hosting and publishing have always been linked. [From 2008](https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=18612231):

> We encourage plugin developers to host the plugins on java.net. This makes it easier for the community to help you more easily, as well as to have the community benefit from the plugin.

This clearly shows that hosting is implied by making the plugin publicly available ("have the community benefit"). So this has always been how it was supposed to work, it just wasn't enforced or enforceable.

Owing to the growth of the Jenkins project it can no longer operate as it has in the past when it was just "KK and friends". The necessity of the 'adopt a plugin' program and the rogue releases of plugins into the Jenkins update site clearly show that -- and while I'd prefer not to do something like per-plugin upload permissions, I accept that not doing that would be irresponsible towards our users.

While I can accept us grandfathering in existing plugins, for new plugins I'd really prefer you go through the usual hosting process and do so in good faith, i.e. also actually release from the jenkinsci repository.

I'd be happy to work with you on figuring out how to set the plugin up so we don't accidentally add access to others when you don't want us to. Removing 'Everyone' and adding a CONTRIBUTING document/having a note in the README should do the trick.

**Comment by batmat** [comment]
Having started [that thread](https://groups.google.com/forum/#!searchin/jenkinsci-dev/%5BPROPOSAL%5D$20Clarify$20the$20source$20code$20canonical$20place$20is$20required$20to$20be$20under%7Csort:relevance/jenkinsci-dev/IoRmYHNn3Q4/98xdt-YOCQAJ) some months ago, I'm also for going through the normal pipe.
In my mind, all the plugins proposed to users on the public Update Center should have their sources findable under http://github.com/jenkinsci

I'm inclined to consider, maybe, that we could want to study a more relaxed thing for experimental UC at some point. *But* in the current infra setup, I don't think that would be an easy change (all releases are going to the same place, pre-release or not). Let's keep that for another discussion.

**Comment by magnayn** [comment]
>
>
>  but it's how maintainers resolved their conflict there
>
>
>
​I don't consider it 'resolved'. I still have him sulking around a
repository he is not contributing to, which is not what I consider to be
polite behaviour.

Github gives me control on my repositories to deal with that. As far as I
am aware, hosting under jenkinsci does not. You are asking me to give up
that control.

**Comment by magnayn** [comment]
>
>
> I'm with @rtyler <https://github.com/rtyler>. Hosting and publishing have
> always been linked. From 2008
> <https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=18612231>:
>
> We encourage plugin developers to host the plugins on java.net. This
> makes it easier for the community to help you more easily, as well as to
> have the community benefit from the plugin.
>
> This clearly shows that hosting is implied by making the plugin publicly
> available ("have the community benefit"). So this has always been how it
> was supposed to work, it just wasn't enforced or enforceable.
>

​I believe you are skipping over the word "encourage".​

​But it *is* publicly available. This isn't some closed-source exception!

And the other pillar in that charter was "low barrier to entry". This
discussion seems to me to indicate that pillar is dying in favour of a
governance orgy. It's now literally easer for me to deploy a plugin to
repo1.maven.org ?!?
​
Further - it's declared in the <scm> tag (I believed this to be neccessary
for the deploy to succeed), and it's all auto-discovered for the wiki site.
I do not follow how hosting under some umbrella helps or hinders with any
of that.

IMO that is a serious OSS anti-pattern. "Hey, yes, it's all OSS - but this
committee here controls access to a vital piece of user infrastructure, so
for practical purposes your freedom is limited".

Owing to the growth of the Jenkins project it can no longer operate as it
> has in the past when it was just "KK and friends". The necessity of the
> 'adopt a plugin' program and the rogue releases of plugins into the Jenkins
> update site clearly show that -- and while I'd prefer not to do something
> like per-plugin upload permissions, I accept that not doing that would be
> irresponsible towards our users.
>

​You already *have* per-plugin upload permissions, no? Defined by this yaml
file?

I would suggest that the 'single point of failure' for plugins actually
makes this *worse*, not better.

While I can accept us grandfathering in existing plugins, for new plugins
> I'd really prefer you go through the usual hosting process and do so in
> good faith, i.e. also actually release from the jenkinsci repository.
>

​And whilst I might want to do that one day - I do not want to do that now.

a) ​H-W-S-N-B-N
b) because I don't want to split up the codebase of a project ("core",
"jenkins plugin", "system C plugin") _at this stage_ because in a period of
rapid growth changes end up touching everything at once.

This is less of an issue *for me as a developer* - but it's a barrier to
contributors. If you've ever had the complaints that a plugin relies on a
forked library, you will understand this implicitly.



> I'd be happy to work with you on figuring out how to set the plugin up so
> we don't accidentally add access to others when you don't want us to.
> Removing 'Everyone' and adding a CONTRIBUTING document/having a note in the
> README should do the trick.
>
​Is everyone-on-github minus one a group?​

**Comment by magnayn** [comment]
However - nobody seems to have a good answer as to why a plugin is any more
"findable" there. Compared with many plugin ecosystems, it's tremendously
easy. Go to the wiki page, follow the "SCM URL" link.



I think having the ability to do 'experimental', 'alpha', 'beta', 'rc' or
any variety of flavoured releases is a *good* thing, and to be able to make
it clear what sort of release it is.

I think the current rain-dance of having to type a URL into an update
center box, then change it back again, is a *bad* thing. Most external
users won't even bring themselves to download a .hpi and install it.

I think having an externalized committee to decide on what
terms-of-reference constitute being 'blessed to the place where mortals may
download' is a *terrible, horrible, no good very bad* thing.

Anything not in the main UC is effectively in a ghetto.

**Comment by daniel-beck** [comment]
@magnayn If your intention is to be able to keep the project structure fluid while working on experimental update site releases, I think we can grant this request for now, with the understanding that it will eventually be forked/moved into jenkinsci before actual releases happen. (CC @rtyler who disagreed earlier)

I'd still like to chat with you about your motivations here to better understand your POV and think about solutions that work for everyone. If that's something you're willing to do, please email me.

**Comment by rtyler** [comment]
@daniel-beck I trust your judgement, I'll leave this in your hands

**Comment by magnayn** [comment]
TBC, _I'm_ not billing it as 'experimental'; it's a low semver to indicate likely future extension; less conservatives souls than I would probably just go "v1.0". I would expect anyone with similar usecases to us to get immediate benefit, and their feedback may help influence direction (just as it has done on the other plugins I started). 

I'm not sure what you mean by 'fluid'. We're building - effectively - a plugin and a library at the same time. As the surface area grows, changes tend up to be codependent. Managing that as (say) git submodules is an unnecessary pain. It might not be one day.

I'm sure I posted at length on the ML on these issues, and suggestions of what could be done. I'm more than happy to reiterate them.

**Comment by daniel-beck** [comment]
Reviewing the past discussion on the topic from earlier this year shows approval of requiring `jenkinsci` plugin hosting for plugins distributed by the Jenkins project update site by most participants in the discussion. It appears that only @KostyaSha and @magnayn disagreed, for different reasons (and I hope most of Kostya's have been addressed, but that's not a topic for this thread). @batmat also documented that the requirement to host in `jenkinsci` (or equivalent) has always existed (and I confirmed it with @kohsuke last weekend, publishing was always supposed to be accompanied by hosting "here", what was *encouraged* was publishing the plugin at all).

Some of the ideas brought forward, such as namespacing plugins, are intriguing, but not possible due to missing infrastructure, both in Jenkins itself, and project infrastructure. Maybe in the future, but for now, we need to work with what we have.

All of that said, we're still allowing uploads of plugins hosted elsewhere due to how I initialized these permissions without looking at repositories (and may need to reconsider that, but this is the current state of things). Granting this request will not result in the first approved plugin not hosted in `jenkinsci`, and refusing it because @magnayn was just a few weeks late isn't a great approach either.

Since @magnayn mentioned a handful of specific and reasonable objections, I think we can approve this request with the understanding that at some point next year the plugin will be moved into `jenkinsci`. This should be enough time to stabilize the plugin sufficiently. I'll also work with @magnayn to implement reasonable measures ensuring he retains control over the plugin once it's in `jenkinsci`, e.g. no 'Everyone' team for his plugin.

Is this something we can agree on?

**Comment by oleg-nenashev** [comment]
@daniel-beck the plan works well for me (sorry for missing the PR update)

**Comment by daniel-beck** [comment]
After eight months without response, I assume that this request is obsolete.

**Pull request closed without merging**
