### PR TITLE
Requesting commit access for chabom2017 and nikhil-dabhade. Also, ple…

### PR DESCRIPTION
**Pull request by chabom2017**
Please make chabom2017 as the primary assignee and maintainer of this project.
Also please provide commit access to nikhil-dabhade

See thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-users/E3Z916xWpBo/JjNB5NmPAwAJ

# Description

# Permissions pull request checklist

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@chabom2017 That checklist in the PR is there for a reason. Please review the last few items.

**Comment by daniel-beck** [comment]
@ahawker FYI

**Comment by ahawker** [comment]
@daniel-beck Acknowledge and confirm.

**Comment by daniel-beck** [comment]
@chabom2017 With this PR merged, you (chabom) have permission to release the plugin.

Additionally, I've made both you and @nikhil-dabhade committers of the plugin repo. You may need to accept the invitation into the GitHub org. Also, you're now default assignee for new issues in Jira.

**Comment by ahawker** [comment]
@daniel-beck Thanks for the help!

**Comment by chabom2017** [comment]
@daniel-beck Thanks!

**Pull request merged**
