### PR TITLE
Extend lifx-notifier plugin developers list

### PR DESCRIPTION
**Pull request by vgaidarji**
I've worked on new version of [`lifx-notifier`](https://github.com/vgaidarji/lifx-notifier-plugin) plugin. I'm on the way of publishing it and want to extend list of developers of this plugin.
I was added to the repo [list of collaborators](https://github.com/jenkinsci/lifx-notifier-plugin/settings/collaboration) by plugin author as well.
screen shot 2016-11-25 at 11 46 19 am

### CODE REVIEW

**Comment by daniel-beck** [comment]
@vgaidarji Are you taking over maintainership of this plugin? I haven't seen anything on the developers' mailing list. if so, we'd make you also default assignee for new issues in Jira.

Also, some general advice when taking over a plugin, from [Adopt a plugin](https://wiki.jenkins-ci.org/display/JENKINS/Adopt+a+Plugin):

> As a new maintainer of a new plugin, you'll inherit its existing users, so be careful with breaking changes. We value data compatibility highly, so any new releases should remain compatible with previous data and upgrade smoothly. If you need help with this, don't hesitate to ask other Jenkins developers for help. And if all else fails, you can mark a new version as being incompatible with older releases to warn users before they update.

---

@michaelneale Could you confirm this is okay with you?

**Comment by michaelneale** [comment]
@daniel-beck yes this is legit. This wasn't up for adoption necessarily but he contacted me and we chatted via email (not public).  I didn't think to put it in that wiki page. But this is legit request. Thanks.

**Comment by vgaidarji** [comment]
@michaelneale thanks.
@daniel-beck Could you please guide me with next steps (if any), so that I can proceed with new plugin version release?

**Comment by daniel-beck** [comment]
@michaelneale To clarify, @vgaidarji is taking over maintainership? Or will you remain the main maintainer?

@vgaidarji Once you've been granted upload permissions (after this PR is merged), you can release at any time as described on [the wiki](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org). It also includes troubleshooting hints. If none of these work, the developers' mailing list should be able to help you.

**Comment by michaelneale** [comment]
Yes he will be taking over @daniel-beck.

**Comment by daniel-beck** [comment]
@michaelneale Thanks. I made @vgaidarji a regular team member to the repo and made him the default assignee for new issues in Jira.

**Pull request merged**
