### PR TITLE
Add pierrebtz as audit-trail-plugin maintainer

### PR DESCRIPTION
**Pull request by PierreBtz**
# Description

* [audit-trail-plugin repository](https://github.com/jenkinsci/audit-trail-plugin)
* [plugin adoption request](https://groups.google.com/forum/#!searchin/jenkinsci-dev/audit$20trail$20plugin%7Csort:date/jenkinsci-dev/Ql85bAlfe0A/0Z1lQNQABwAJ)

CC @tomaszsek

# Submitter checklist for changing permissions

### Always

- [*] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [*] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [*] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [*] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by ndeloof** [comment]
I don't consider myself to be a maintainer of this plugin.
Many people have been contributing without an obvious "maintainer" role before 2014.
A proper maintainer would be welcome

**Comment by olivergondza** [comment]
Likewise. @tomaszsek, thanks for taking over.

**Comment by batmat** [comment]
Ok, timeout + positive feedback both from Nicolas and Oliver, moving forward.

**Comment by batmat** [comment]
```
[10:14] <+     batmat> | jenkins-admin: hello!
[10:14] <@jenkins-adm> | Hello batmat!
[10:15] <+     batmat> | jenkins-admin: make pierrebtz committer on audit-trail-plugin
[10:15] <@jenkins-adm> | Added pierrebtz as a GitHub committer for repository audit-trail-plugin
[10:15] <+     batmat> | context is https://github.com/jenkins-infra/repository-permissions-updater/pull/955 for ^^^
```

**Pull request merged**
