### PR TITLE
plugin-parasoft-findings - add benken_parasoft

### PR DESCRIPTION
**Pull request by benken-parasoft**
# Description

Repository: https://github.com/jenkinsci/parasoft-findings-plugin
I am a contributor and work with existing contributor @jacekmarzecparasoft

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by benken-parasoft** [comment]
I'm am looking forward to this pull request being accepted.  I am not sure if is blocked at this point.  So, please let me know if you need additional action from myself or from Jacek (@jacekmarzecparasoft).  Jacek and I are both part of a larger team at Parasoft (@parasoft).  If you needs something from Jacek I can ping him as well.

**Comment by daniel-beck** [comment]
@benken-parasoft This is still pending:

> Make sure to @mention an existing maintainer to confirm the permissions request, if applicable

**Comment by benken-parasoft** [comment]
>Make sure to @mention an existing maintainer

Thank you.  Perhaps I misunderstand you.  Maintainer is @jacekmarzecparasoft (isn't this what you mean by @mention?).  This is his both his Jenkins ID and github ID.  He is currently the only developer listed in the plugin-parasoft-findings.yml which I am requesting myself to also be added so that I can publish releases to the Jenkins maven repo as well.  Jacek Marzec and I are both part of a larger team at Parasoft (@parasoft).  Both of us are generally involved with maintaining releases for @parasoft.  Development for this Jenkins plugin was primarily done by Jacek but other team members @parasoft are now involved.  In fact, you will see the last few commits to the project were not from Jacek but from myself (@benken-parasoft) and another one of co-workers Grigor (@grigorbarseghyan).  We want at least one other person to have permissions to publish releases.  I am an active committer and handle releases for several other related github projects for @parasoft.

Some additional evidence in case this helps (notice my name name/iD):
   * https://github.com/jenkinsci/parasoft-findings-plugin/blob/master/pom.xml
      * notice my Jenkins account info in the "developer" tag
   * https://github.com/jenkinsci/parasoft-findings-plugin/commits/master
      * notice my commits, including those for maven-release-plugin
    * https://github.com/jenkinsci/parasoft-findings-plugin/releases
      * notice my updates to the releases page

In case this also helps prove I'm legit and not attempting something nefarious, here is evidence of some other (non-Jenkins) projects for @parasoft that I maintain that are similar or related to this one for Jenkins (again notice my name/ID):
https://github.com/parasoft/parasoft-findings-bamboo/releases
https://github.com/parasoft/parasoft-findings-teamcity/releases
https://github.com/parasoft/parasoft-findings-vsts/releases

**Comment by daniel-beck** [comment]
@benken-parasoft To clarify, this request just needs a response from your colleague(s), approving this change. A comment to this PR from @jacekmarzecparasoft suffices. That's what the ping is for, but they haven't responded.

We have no insight into how your teams operate or anything like that, so we need explicit approval.

**Comment by jacekmarzecparasoft** [comment]
> A comment to this PR from @jacekmarzecparasoft suffices

Please approve this.

**Pull request merged**
