### PR TITLE
Adding to the maintainers list for this plugin

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

# Description

This is an official request to be made a co-maintainer of the plugin anchore-container-scanner-plugin (https://github.com/jenkinsci/anchore-container-scanner-plugin) as part of my job function.
I have filed the following issue: https://issues.jenkins-ci.org/browse/INFRA-2552
I have made the official request to the dev mailing list

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x]`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
cc: @oleg-nenashev

**Comment by markyjackson-taulia** [comment]
Mailing list note: https://groups.google.com/forum/#!topic/jenkinsci-dev/4RQFyTwjT7I

**Comment by markyjackson-taulia** [comment]
cc: @nurmi for approval

**Comment by oleg-nenashev** [comment]
Mailing list request is not mandatory for actively maintained plugins FTR. But we need an approval from the current maintainer

**Comment by markyjackson-taulia** [comment]
@oleg-nenashev I mainly do that part (mailing list) to serve as an example when new maintainers ask the question of what are the steps they need to take, this becomes my example.

**Comment by nurmi** [comment]
@oleg-nenashev @markyjackson-taulia - approved!

**Pull request merged**
