### PR TITLE
Adding user 'mhoffrog' to Unleash plugin developer list

### PR DESCRIPTION
**Pull request by mhoffrog**
Filed this PR according to https://github.com/jenkins-infra/repository-permissions-updater/issues/4001 - @timja - please approve and merge this PR.

# Link to GitHub repository

[unleash-plugin](https://github.com/jenkinsci/unleash-plugin)

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@mhoffrog`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by timja** [comment]
Welcome aboard

**Comment by mhoffrog** [comment]
@timja Did migrate old wiki doc to the repo already. Can you make sure to redirect from old wiki to the repo docs? I am a bit confused by all the information source on how to create this request for redirection - JIRA INFRA is telling that those requests did go to github infra helpdesk issues etc. Maybe you can help on that one. Many thanks in advance!

**Comment by timja** [comment]
Once you do a release of the plugin it should be updated within about 8 hours or so

**Comment by timja** [comment]
(The documentation source is this attribute: https://github.com/jenkinsci/unleash-plugin/blob/master/pom.xml#L21 and a release is required for picking up changes to it, docs changed will happen quicker in future and not require a release once you've changed it to GitHub)

**Comment by mhoffrog** [comment]
@timja - sorry for bothering again - realized that Stanley Hillner (shillner) is still in the plugins repo admin group. Since he did retire from maintaining that repo, I'd like to get him removed from the group. Can you manage that by this way or shall I file another request for this?
image

@shillner - Please let me know or request appropriate access again, if you still want to participate.

**Comment by timja** [comment]
I've given you permission to manage it

**Pull request merged**
