### PR TITLE
enable cd for inodes monitor plugin

### PR DESCRIPTION
**Pull request by janasrikanth**
repo: https://github.com/jenkinsci/inodes-monitor-plugin

# Description

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above
      https://github.com/jenkinsci/inodes-monitor-plugin
### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.
  https://github.com/jenkinsci/inodes-monitor-plugin/pull/7

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
Please include a link to the PR enabling CD in your plugin.

**Comment by janasrikanth** [comment]
> 

Hi @NotMyFault 
you mean the pr raised in inodes-monitor-plugin?

**Comment by NotMyFault** [comment]
> > 
> 
> Hi @NotMyFault you mean the pr raised in inodes-monitor-plugin?

Yes, the PR which prepares your plugin for CD according to the documentation.

**Comment by janasrikanth** [comment]
> PR

PR: https://github.com/jenkinsci/inodes-monitor-plugin/pull/7

**Comment by NotMyFault** [comment]
> @NotMyFault Merged PR: [jenkinsci/inodes-monitor-plugin#6](https://github.com/jenkinsci/inodes-monitor-plugin/pull/6) contains maintenance activity PR: [jenkinsci/inodes-monitor-plugin#7](https://github.com/jenkinsci/inodes-monitor-plugin/pull/7) update new version

I'm afraid that's not right and does not relate to CD at all. Did you not consult the documentation of how CD works before creating this PR? I recommend doing that.

**Comment by janasrikanth** [comment]
Hi @NotMyFault 
Please review the PR: https://github.com/jenkinsci/inodes-monitor-plugin/pull/7

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
