### PR TITLE
Update plugin-redgate-sql-ci.yml

### PR DESCRIPTION
**Pull request by diogo-duarte-rg**
Repository:

https://github.com/jenkinsci/redgate-sql-ci-plugin

My commits:

https://github.com/jenkinsci/redgate-sql-ci-plugin/commits?author=diogo-duarte-rg

Existing maintainer: @lubosmichalic 

- [x] Add link to plugin/component Git repository in description above
- [x] Make sure to @mention an existing maintainer to confirm the permissions request, if applicable
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] All newly added users have logged in to Artifactory at least once

### CODE REVIEW

**Comment by diogo-duarte-rg** [comment]
I'm struggling to login to artifactory and password reset does not work too.

**Comment by slide** [comment]
Can you try logging in to Jira (https://issues.jenkins.io)?

**Comment by diogo-duarte-rg** [comment]
Thanks for your reply. I have managed to login now. Turns out the password email was being blocked by my company spam filter.
I have now logged in to artifactory too.

**Comment by diogo-duarte-rg** [comment]
@slide are you able to retrigger the build please?

**Comment by slide** [comment]
Close and reopen for build.

**Comment by lubosmichalic** [comment]
I'm happy for @diogo-duarte-rg to be added as a contributor

**Comment by slide** [comment]
One clarification, is github access not needed?

**Comment by diogo-duarte-rg** [comment]
@slide I'm trying to be able to release our Jenkins plugin.
I think I have the github access I need as I've been able to raise the pull request on https://github.com/jenkinsci/redgate-sql-ci-plugin?
Is there any other repository that would need permissions?

**Comment by slide** [comment]
Anyone can create a PR there is no special access for that on github. If you need to be able to merge PR's, there is special access for that. Are you able to merge PRs?

**Comment by diogo-duarte-rg** [comment]
I did merge this one https://github.com/jenkinsci/redgate-sql-ci-plugin/pull/26

**Comment by slide** [comment]
Ok, then your github permissions should be good to go.

**Pull request merged**
