### PR TITLE
Plugin manager request

### PR DESCRIPTION
**Pull request by stopalopa**
# Description

Updating the paths for the plugin installation tool. 
https://github.com/jenkinsci/plugin-installation-manager-tool
https://issues.jenkins-ci.org/browse/HOSTING-777

# Submitter checklist for changing permissions

### Always

- [ x] Add link to plugin/component Git repository in description above

### CODE REVIEW

**Comment by slide** [comment]
Just wondering, why put Jenkins into the names? For plugins at least, we generally don't want "Jenkins" in the name

**Comment by slide** [comment]
@stopalopa ping on my previous question?

**Comment by stopalopa** [comment]
Earlier in the development process I merged in some changes suggested by @batmat (https://github.com/jenkinsci/plugin-installation-manager-tool/pull/2/commits/aa4ede47e463428e8751c582be5e2e70f09e7941), which included having Jenkins in the artifactId. Is this something I should change?

**Comment by slide** [comment]
@batmat We generally don't want jenkins in the artifactId, but if you have a good reason, we can bypass that "rule"

**Comment by oleg-nenashev** [comment]
No strong opinion here. IMHO it can be safely removed

**Comment by batmat** [comment]
My rationale was that, contrary to plugins, the Jenkins plugin-manager tooling was likely to be used quite outside of a Jenkins context.
Like we have dozens of [`core` modules in Central](https://search.maven.org/search?q=core) that become a mess when dumped as is on the classpath.

Like `jenkins-core` in Jenkins: https://github.com/jenkinsci/jenkins/blob/master/core/pom.xml#L35 or `jenkins-war` https://github.com/jenkinsci/jenkins/blob/master/war/pom.xml#L34 (`cli` sounds like a mistake to me, though, but well).

**Comment by slide** [comment]
What's the status on this one?

**Comment by slide** [comment]
I'm going to close this out (not merge) unless someone says otherwise.

**Pull request merged**
