### PR TITLE
Grant @oleg-nenashev and @olivergondza permissions to release the Javadoc plugin

### PR DESCRIPTION
**Pull request by oleg-nenashev**
CC @jglick 

Subj: https://github.com/jenkinsci/javadoc-plugin/pull/10

### CODE REVIEW

**Comment by jglick** [comment]
and CC @olivergondza

**Comment by oleg-nenashev** [comment]
ugh. How did I manage to create it from the master fork?
Should I recreate it @batmat ?

**Comment by batmat** [comment]
I don't feel that strongly about that, was trying to retrigger, but I would suspect the PR build is configured to only watch out forks. Which might be why the PR build doesn't kick in (but I've no access to the config).

**Comment by oleg-nenashev** [comment]
created the new one

**Pull request closed without merging**
