### PR TITLE
Add johanc as a developer on deepsecurity-smartcheck-plugin

### PR DESCRIPTION
**Pull request by johan1252**
# Description

Github Repository: https://github.com/jenkinsci/deepsecurity-smartcheck-plugin

Adding new developer:
johanc (jenkins username) -> @johan1252 (github username)

# Submitter checklist for changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by johan1252** [comment]
@Graham42 to provide approval as an existing maintainer of the plugin

**Comment by Graham42** [comment]
It appears the link to IRC Bot command: https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management is dead. Maybe it's meant to go to https://github.com/jenkins-infra/ircbot

**Comment by Graham42** [comment]
## Reviewer checklist (not for requesters!)
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an IRC Bot command
- [x] Check that the $pluginId Developers team has Admin permissions while granting the access.
- [ ] ~In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.~ N/A
- [ ] ~If security contacts are changed (this includes add/remove), ping the security officer (currently @daniel-beck) in this pull request. If an email contact is changed, wait for approval from the security officer.~ N/A

**Comment by daniel-beck** [comment]
> ping the security officer (currently @daniel-beck) in this pull request

Thanks for the unnecessary ping 😛 FYI the formatting in the template is as is to prevent that from occurring.

**Comment by Graham42** [comment]
Sorry about that!

**Comment by slide** [comment]
> It appears the link to IRC Bot command: https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management is dead.

I think the Jenkins infra is having some issues. The infra team is working on fixing it.

**Pull request merged**
