### PR TITLE
Adding yinhuan@amazon.com to CodePipeline plugin maintainers

### PR DESCRIPTION
**Pull request by maggiecopyAWS**
Adding yinhuan to CodePipeline plugin maintainers.

see https://issues.jenkins-ci.org/browse/HOSTING-246

https://github.com/jenkinsci/aws-codepipeline-plugin

### CODE REVIEW

**Comment by daniel-beck** [comment]
@belltimo @bankAWS @biagic Please confirm that @maggiecopyAWS should get commit access and permission to upload releases of aws-codepipeline-plugin.

**Comment by daniel-beck** [comment]
Either you put the wrong account name, or you haven't logged in. Since `maggiecopyaws` exists, I guess the latter.

The checklist for new PRs exists for a reason.

**Comment by belltimo** [comment]
Yes, @maggiecopyAWS should have access on aws-codepipeline-plugin.

**Comment by batmat** [comment]
@maggiecopyAWS please see the last comment of @daniel-beck 

you **must** log in at least once to enable your account

**Comment by daniel-beck** [comment]
> Either you put the wrong account name, or you haven't logged in. Since `maggiecopyaws` exists, I guess the latter.

Correction, probably the *former*.

**Comment by maggiecopyAWS** [comment]
@daniel-beck The account name is the account I use to login to https://repo.jenkins-ci.org/. Is it correct? Did I miss something?

**Comment by maggiecopyAWS** [comment]
@daniel-beck The account name I used to login to https://repo.jenkins-ci.org/ is maggiecopyAWS. Should I put this account into the pull request instead?

**Comment by daniel-beck** [comment]
@maggiecopyAWS 

Yes. Quoting [this repository's README](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/README.md#managing-permissions):

> A set of user names (Jenkins community user accounts in LDAP, the same as used for wiki and JIRA) allowed to upload this artifact to Artifactory.

… and the [pull request template](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/.github/PULL_REQUEST_TEMPLATE):

> Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name

I really have no idea how I could make this any clearer. Suggestions welcome.

**Comment by maggiecopyAWS** [comment]
@daniel-beck Sorry, the commit message confused me. This is clear enough. I lost the repo for some reason. Create a new pull request here. https://github.com/jenkins-infra/repository-permissions-updater/pull/166 Thanks for all the helps.

**Pull request closed without merging**
