### PR TITLE
Adding user to OverOps Query Plugin project

### PR DESCRIPTION
**Pull request by ccaspanello**
# Description
@daverted https://github.com/jenkinsci/overops-query-plugin
@ccaspanello https://github.com/jenkinsci/overops-query-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
Please fill out the PR template, it is there for a reason.

` User name not known to Artifactory: ccaspanello`

**Comment by ccaspanello** [comment]
Instructions are not clean on how to create an Artifactory account.
https://issues.jenkins-ci.org/browse/INFRA-2678

It appears now that I have created a JIRA account I have an Artifactory account.

**Comment by ccaspanello** [comment]
Pushed update to force another check.  Still getting:  
`User name not known to Artifactory: ccaspanello`

I have logged into Artifactory . . . not sure what I'm doing wrong.

**Comment by slide** [comment]
It can take a little bit of time for the permissions to propagate, so I'll requeue a build in just a little bit.

**Comment by ccaspanello** [comment]
Awesome!  Thank you for working through this with me @slide - Just realized your the same person responding to my JIRA ticket :)

**Comment by slide** [comment]
Closing and reopening for a build

**Comment by slide** [comment]
Ok, now we just need @daverted to comment here and approve.

**Comment by ccaspanello** [comment]
Thank you @slide & @daverted - You guys rock!

**Pull request merged**
