### PR TITLE
Add dfchang336 to CodePipeline plugin maintainers

### PR DESCRIPTION
**Pull request by dafangc-amazon**
For plugin https://github.com/jenkinsci/aws-codepipeline-plugin.

Existing member @egoramazon can approve this PR.

# Description

# Submitter checklist for adding or changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by egoramazon — APPROVED** [review]

**Comment by NotMyFault** [comment]
Hey @dafangc-amazon,

you need to log into Jira too, to get a successful build. https://issues.jenkins.io/

**Comment by dafangc-amazon** [comment]
> Hey @dafangc-amazon,
> 
> you need to log into Jira too, to get a successful build. https://issues.jenkins.io/
Thanks, going to close and reopen this pr to trigger the workflow

**Comment by dafangc-amazon** [comment]
Hey @NotMyFault , how do I get write permissions to our repo under jenkinsci? 
https://github.com/jenkinsci/aws-codepipeline-plugin

Not sure if this is the best place for this question.

**Comment by NotMyFault** [comment]
> Hey @NotMyFault , how do I get write permissions to our repo under jenkinsci? https://github.com/jenkinsci/aws-codepipeline-plugin
> 
> Not sure if this is the best place for this question, but I couldn't find related info on how to request access.

I sent you an invitation to the repository team. The part of the template covering GH repository permission wasn't filled out, so I was under the impression you were looking for release permission only.

**Pull request merged**
