### PR TITLE
add permission for maven-jenkins-dev-plugin

### PR DESCRIPTION
**Pull request by olamy**
permission to deploy maven-jenkins-dev-plugin

### CODE REVIEW

**Comment by daniel-beck** [comment]
@olamy Could you send an FYI/RFC to the dev list if you haven't, so we have a record of this? Otherwise :+1:

**Comment by olamy** [comment]
@daniel-beck then will I be ok with all administrative paperwork? :P

**Comment by olamy** [comment]
@daniel-beck suspens -> crossing fingers :-)

**Comment by olamy** [comment]
@daniel-beck no idea why but it's not working :-(
`
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project maven-jenkins-dev-plugin: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.tools:maven-jenkins-dev-plugin:jar:9.4.5.v20170502-jenkins-1 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/tools/maven-jenkins-dev-plugin/9.4.5.v20170502-jenkins-1/maven-jenkins-dev-plugin-9.4.5.v20170502-jenkins-1.jar, ReasonPhrase: Forbidden. -> [Help 1]
`

**Comment by olamy** [comment]
ok I fixed manually the tag.

**Comment by daniel-beck** [comment]
@olamy If you could share the full build log in gist, that would be helpful.

Perhaps even a wireshark log or similar to see exactly what failed?

**Pull request merged**
