### PR TITLE
Update plugin-rebuild.yml

### PR DESCRIPTION
**Pull request by GLundh**
# Description
https://github.com/jenkinsci/rebuild-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by GLundh** [comment]
I have gotten OK from Ragesh on LinkedIn to continue manage this plugin. 
See discussion here:
https://github.com/jenkinsci/rebuild-plugin/pull/49

I don't think he is active on github anymore, but Robert Sandell (also in the permission list), could probably +1 this one.

**Comment by GLundh** [comment]
@rsandell Ping.

**Comment by daniel-beck** [comment]
It doesn't look like rebuild plugin is well maintained, but a reference to the current maintainer (if any) or undisputed request to take over maintainership is still needed.

**Comment by daniel-beck** [comment]
FYI @hagzag if you're no longer maintaining this, please let us know/approve this request. Thanks!

**Comment by GLundh** [comment]
Would a screenshot from my conversation with the Ragesh on LinkedIn be enough in this case?

**Comment by daniel-beck** [comment]
@GLundh GitHub associated the commits with @shemeersulaiman so at least there's still an account. Would prefer a response from that account (or just wait for @rsandell or @hagzag to respond, they're more recently involved, and active elsewhere on GitHub).

**Comment by GLundh** [comment]
I also pinged Ragesh on linkedin. Hopefully one of mentioned maintainers will be able to +1 this request.

**Comment by daniel-beck** [comment]
@GLundh FYI if you're taking over as maintainer (rather than scratch and itch and move on), the usual process is to email the dev list. While we have this repo now to largely take over the 'get approval' role, it'd still be nice to let people know.

**Comment by GLundh** [comment]
I hope to handle the most urgent pull requests, though I'm not sure I can commit to long term maintenance. For how long I'm able to maintain it and on what level depends more on when my team will migrate our projects to pipeline code. After that I hope to start a building a new plugin to provide "Rebuild from stage"-functionality.

**Comment by rsandell** [comment]
Shemeer officially abandoned the plugin with a mail to me, that I forwarded to the dev list, and put it up for adoption a couple of years ago. 
Someone else took over maintainer duties after that, but it seems to have become abandoned again.

**Comment by rsandell** [comment]
But +1 from me :)

**Comment by daniel-beck** [comment]
@hagzag Last call – if you are still maintaining the Rebuild Plugin, please respond.

**Comment by GLundh** [comment]
Can we close this one? If it helps, I was one of the maintainers briefly when my team started work on the plugin at Sony 7 or 8 years ago...

**Comment by daniel-beck** [comment]
@hagzag had two weeks to respond and didn't, which is our usual timeout.

(@glundh We still prefer emails to the dev list about a change like this.)

**Comment by GLundh** [comment]
Thanks. 

> We still prefer emails to the dev list about a change like this.

Sure. I'll keep that in mind for next time.

**Pull request merged**
