### PR TITLE
Adopt oic-plugin

### PR DESCRIPTION
**Pull request by Skiepp**
Link to plugin/component Git repository -> https://github.com/jenkinsci/oic-auth-plugin
Previous Maintainers -> @mjmbischoff
Added Maintainers -> @Skiepp

### CODE REVIEW

**Comment by Skiepp** [comment]
Logged to jFrog and Jira

**Comment by halkeye** [comment]
Plugin is up for adoption, merging.

**Comment by halkeye** [comment]
Btw since your deleted the template I just did the minimum steps and only gave releases access

**Comment by Skiepp** [comment]
Thanks @halkeye, edited with the template

**Pull request merged**
