### PR TITLE
requesting permission to modify and release tfs-plugin

### PR DESCRIPTION
**Pull request by kasubram**
# Description

Request publish permission for Team Foundation Server Plugin
Github repo: https://github.com/jenkinsci/tfs-plugin
@DavidStaheli - as a committer, can you please review this request

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by batmat** [comment]
Why are you adding two entries? Can you clarify? Thanks

**Comment by kasubram** [comment]
@batmat I am requesting permission for two users
"kalyan" is my account. "jenkinssriramb" is of https://github.com/GitHubSriramB

**Comment by kasubram** [comment]
I still dont have write access on the github repo of the plugin https://github.com/jenkinsci/tfs-plugin
Is that also controller by the this permission? I got myself added to the developer [pom.xml](https://github.com/jenkinsci/tfs-plugin/blob/master/pom.xml). 
My jenkins ldap user name is all small case letters "kalyan"

Can someone help me on this?

**Comment by daniel-beck** [comment]
@kasubram https://github.com/jenkins-infra/repository-permissions-updater#about

**Pull request merged**
