### PR TITLE
Add new maintainer to plasticscm-plugin

### PR DESCRIPTION
**Pull request by mig42**
# Description

I'm adding @ferdef as developer of plugin `plasticscm-plugin` (https://github.com/jenkinsci/plasticscm-plugin) so he can upload new releases to the artifact repository.

I'm (@mig42) the main maintainer of the plugin at the moment.

I also created an issue in Jira requesting repository access for him: https://issues.jenkins-ci.org/browse/INFRA-2789

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by timja** [comment]
GitHub access granted, artifactory login needs to be done before release permissions

**Comment by mig42** [comment]
@ferdef had logged in to artifactory but the system probably didn't have the updated information. As said in the check result, I'll close and reopen the PR to retrigger the checks 😊

**Comment by timja** [comment]
note: our ci system is currently down 😄

**Comment by ferdef** [comment]
I've already logged in, so I guess it will pass once the CI goes up again

**Comment by mig42** [comment]
Let's try again...

**Comment by MarkEWaite** [comment]
As far as I can tell, the CI job is correctly reporting:

```
User name not known to Artifactory: fernando_de_francisco
```

**Pull request merged**
