### PR TITLE
Update plugin-bitbucket-pullrequest-builder.yml

### PR DESCRIPTION
**Pull request by damovsky**
# Description

added new developer, see https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin/commit/77d917dac2d5d52c8756b2e068da93d3af75713d

# Permissions pull request checklist

### Always

https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin

### When adding new uploaders (this includes newly created permissions files)
@nishio-dens

Unfortunately, I can't log in to the repo.jenkins-ci.org with my jenkins account

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Unfortunately, I can't log in to the repo.jenkins-ci.org with my jenkins account

Note that there's a problem right now with the reverse proxy in front of Artifactory; try jenkinsci.artifactoryonline.com instead.

**Comment by daniel-beck** [comment]
As usual in such cases, we will give existing committers like @nishio-dens some time to reject this request -- or approve (just by posting a comment here), in which case this change will be merged more quickly.

**Comment by damovsky** [comment]
@daniel-beck many thanks for your suggestion! yes, i can log in to the jenkinsci.artifactoryonline.com

This PR can be merged ....

**Comment by daniel-beck** [comment]
@damovsky Please see my second comment for how we're handling upload permission grants to new committers.

**Comment by damovsky** [comment]
I'm in touch with  @nishio-dens via emails...I'll ask him to approve this. Thanks ;-)

**Comment by nishio-dens** [comment]
Hello @daniel-beck and @damovsky,

I approve this PR, @damovsky  is a new commiter of bitbucket-pullrequest-builder-plugin.

Thanks

**Pull request merged**
