### PR TITLE
This PR is a request to add me as I am now the maintainer of this plugin and have been for the past 6 months

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by slide** [comment]
I don't know the history on this one, @batmat can you confirm?

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/1219/commits/627c43e46530a61533ae974d184f85354045f4e0 was never merged, so the PR title here is misleading.

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-prometheus.yml

**Comment by markyjackson-taulia** [comment]
A lot of confusion here and caused by me. Originally I became the maintainer and put in a PR but it was done wrong on my end. 
I am the maintainer but need this part changed.

**Comment by markyjackson-taulia** [comment]
I updated the misleading title

**Comment by markyjackson-taulia** [comment]
@daniel-beck @slide ^

**Comment by markyjackson-taulia** [comment]
@daniel-beck is it ok to move forward with this pr?

**Comment by slide** [comment]
Based on the history I see in the plugin's github repo, I think this is fine.

**Pull request merged**
