### PR TITLE
Update enable cd

### PR DESCRIPTION
**Pull request by thyldrm**
It's plugin pr link : https://github.com/jenkinsci/codethreat-scanner-plugin/pull/2

# Description

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
Hey @thyldrm,

Please take a moment and fill out the PR template in terms of enabling CD.

Thanks!

**Comment by thyldrm** [comment]
filled

**Comment by NotMyFault** [comment]
> filled

>  Add a link to the pull request, which enables continous delivery for your plugin or component.
 
I see no such link.

**Comment by thyldrm** [comment]
added

**Comment by NotMyFault** [comment]
> added

This is not valid. The PR template asks to add a link to the PR where you enable CD in your plugin. Please take a moment and prepare such a PR towards your plugin so we can review it.

**Comment by thyldrm** [comment]
Is it enough to just open a PR for the plugin without committing it? Be a little more descriptive please.

**Comment by NotMyFault** [comment]
> Be a little more descriptive please.

Please file a pull request towards your plugin where you enable automatic releases [according to the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/).
Then add a link to this PR linking to your plugin's PR enabling CD, allowing us to review it.

**Comment by thyldrm** [comment]
> Enable the continuous delivery flag in [repository permission updater](https://github.com/jenkins-infra/repository-permissions-updater/) (RPU) for your plugin by filing a pull request adding to permissions/plugin-xxx.yml:

This is in the document. This is the current PR. What will I commit to my plugin? Which commit will I put the PR of? I can not understand.

**Comment by NotMyFault** [comment]
> What will I commit to my plugin?

The changes where you enable automatic release according to the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#configure-cd-workflow).
The PR towards the repository permission updater (this PR) activates CD on our backend only. It does not release anything if you don't configure your plugin according to the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#configure-cd-workflow). 
I recommend you take a moment and read the documentation linked carefully.

> Which commit will I put the PR of?

See my previous answer what to commit.

**Comment by thyldrm** [comment]
added

**Comment by NotMyFault** [comment]
Thanks, this is a good start, but not yet complete.

You forgot to update your pom.xml and .mvn/maven.config according the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config).

**Comment by thyldrm** [comment]
i updated
also the maven work was already up to date. I updated the pom.xml file.

**Review by NotMyFault — APPROVED** [review]

**Comment by thyldrm** [comment]
Hello, I have done a lot of necessary things. Now do I need to do anything for the plugin to be published here https://plugins.jenkins.io/ ?

**Pull request merged**
