### PR TITLE
Add new maintainer to scm-sync-configuration

### PR DESCRIPTION
**Pull request by guipal**
# Description
After trying to contact the current maintainers (@fcamblor,@rodrigc) of https://github.com/jenkinsci/scm-sync-configuration-plugin for 1 month, i receive no answer so i would like to be a maintainer for the plugin. I would also need write permissions on the github repo for my user @guipal.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
> After trying to contact the current maintainers (@fcamblor,@rodrigc) of https://github.com/jenkinsci/scm-sync-configuration-plugin for 1 month, i receive no answer so i would like to be a maintainer for the plugin

Is there a public track of this communication?

**Comment by guipal** [comment]
I started over email and afterwards move to developers mail list: https://groups.google.com/forum/#!msg/jenkinsci-dev/ibIaxqzfciY/YX5eDeQrCAAJ

**Comment by daniel-beck** [comment]
@fcamblor @rodrigc If you're still maintaining scm-sync-configuration, please respond. Otherwise I'll assume you're no longer active or interested in the plugin, and transfer maintainership. Thanks!

**Comment by fcamblor** [comment]
Yes I'm still alive.

But nope, I'm not maintaining it anymore (and am very happy when some folks want to take this burden :-))

Happy to welcome you on board @guipal (sorry for not answering it previously, had some mail filterings which are a bit too restrictive it seems :-))

**Comment by guipal** [comment]
@fcamblor would you be so kind to provide me the proper grants over the repo? Thank you!

**Comment by fcamblor** [comment]
@guipal unfortunately, I don't think I will have the rights to.

I guess either the infra bot (or maybe @daniel-beck himself ?) should have the rights for this.

**Comment by daniel-beck** [comment]
@guipal Done, sorry about that -- when I reviewed this yesterday I missed your note.

**Comment by guipal** [comment]
Thank you @fcamblor @daniel-beck :)

**Pull request merged**
