### PR TITLE
updating maintainer of skytap plugin

### PR DESCRIPTION
**Pull request by jchenry**
@tommilligan  per conversation on the mailing list, I @jchenry, am taking over as maintainer of the skytap plugin
https://github.com/jenkinsci/skytap-cloud-plugin

# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by tommilligan** [comment]
@jchenry possible you meant to tag someone else?

**Comment by daniel-beck** [comment]
@tommilligan He meant @tjmilligan.

@tjmilligan Since you're around, could you confirm this change? Just comment here.

**Comment by daniel-beck** [comment]
> Since you're around, could you confirm this change? Just comment here.

https://github.com/jenkinsci/skytap-cloud-plugin/pull/2#issuecomment-335305042 is an adequate response, so no further needed from @tjmilligan unless he wants to retain upload permissions. That's quick enough to restore if needed.

**Comment by jchenry** [comment]
Apologies @tommilligan!

**Pull request merged**
