### PR TITLE
Create plugin-snyk-security-scanner.yml

### PR DESCRIPTION
**Pull request by AH7**
# Description
Repository URL: https://github.com/jenkinsci/snyk-security-scanner-plugin
Hosting Request: https://issues.jenkins-ci.org/browse/HOSTING-376

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### CODE REVIEW

**Comment by daniel-beck** [comment]
@AH7 `adrukh` has not logged in, and permission changes are not effective if some users don't exist in Artifactory. So please remove that user, or tell them to log in. Looks good otherwise.

**Comment by adrukh** [comment]
@daniel-beck I signed into https://issues.jenkins-ci.org/browse/HOSTING-376, please let me know if this is ok.

**Comment by daniel-beck** [comment]
@adrukh I'm referring to Artifactory, see this repo's readme.

**Comment by adrukh** [comment]
@daniel-beck sorry for missing this one! Logged in just now.

**Pull request merged**
