### PR TITLE
add Joseph 'casz' Petersen

### PR DESCRIPTION
**Pull request by casz**
as new maintainer of Accurev plugin I would like to be added :tada:

### CODE REVIEW

**Comment by orrc** [comment]
casz is indeed the new maintainer:
https://botbot.me/freenode/jenkins/2016-08-27/?msg=72058192&page=4
https://github.com/jenkinsci/accurev-plugin/commits/master?author=casz

Assuming LDAP and GitHub usernames are the same, 👍 from me.

@daniel-beck: Do we have a good way of verifying the LDAP-GitHub association? Do we want to remove old maintainers from the list (this plugin was up for adoption until recently)?

**Comment by casz** [comment]
@orrc username is casz, all around.
only reference I gave was:
https://groups.google.com/forum/#!msg/jenkinsci-dev/SdNcPm5q_vY/wQ0rYg8uCQAJ

**Comment by daniel-beck** [comment]
@batmat Did you get a response by the previous maintainer before making @casz the maintainer? @rym002 was still around not even a year ago.

**Comment by batmat** [comment]
@daniel-beck Nope, I proceeded immediately after seeing the plugin was already marked as to-be-adopted. I would have asked the previous maintainer(s) for sure as usual if not.

**Comment by rym002** [comment]
I am OK with this.

**Comment by daniel-beck** [comment]
@rym002 Thanks!

**Pull request merged**
