### PR TITLE
Preparing plugin adoption

### PR DESCRIPTION
**Pull request by rzanner**
# Link to GitHub repository

As discussed with @NotMyFault, we consider this plugin abandoned by the current maintainers @diabol_jenkins, @mrfatstrat, @patbos and @tommysdk.
I want to adopt and integrate it into the jenkinsci github repository, so this would be https://github.com/jenkinsci/delivery-pipeline-plugin, I guess.

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@rzanner`
- `@gianluca-soffredini`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
Hey,

thanks for filing the PR. Is there a typo in the GH handle of `gsoffredini`? There's no GH account with such a handle.

In https://github.com/jenkinsci/delivery-pipeline-plugin/commit/28bccea096189177f75546aeafca8856d17f0829 I've added this plugin to ci.jenkins.io, but bear in mind, modernization is needed still in order to get a green build, just FYI.

**Comment by rzanner** [comment]
Thanks for having a look at the PR - I didn't notice that Gianlucas GH handle is `@gianluca-soffredini`. 

Is it an issue that it's different from his username in the Jenkins JIRA? :see_no_evil:

**Comment by NotMyFault** [comment]
> @NotMyFault: Thanks for having a look at the PR - I didn't notice that Gianlucas GH handle is `@gianluca-soffredini`.
> 
> Is it an issue that it's different from his username in the Jenkins JIRA? 🙈

No, accounts.jenkins.io operates independently of your GH account. Hence, you log in to artifactory and Jira with its own credentials.

**Comment by rzanner** [comment]
> > @NotMyFault: Thanks for having a look at the PR - I didn't notice that Gianlucas GH handle is `@gianluca-soffredini`.
> > Is it an issue that it's different from his username in the Jenkins JIRA? 🙈
> 
> No, accounts.jenkins.io operates independently of your GH account. Hence, you log in to artifactory and Jira with its own credentials.

So I need to use the GH handle `@gianluca-soffredini` in the YAML file?

**Comment by rzanner** [comment]
> > > @NotMyFault: Thanks for having a look at the PR - I didn't notice that Gianlucas GH handle is `@gianluca-soffredini`.
> > > Is it an issue that it's different from his username in the Jenkins JIRA? 🙈
> > 
> > 
> > No, accounts.jenkins.io operates independently of your GH account. Hence, you log in to artifactory and Jira with its own credentials.
> 
> So I need to use the GH handle `@gianluca-soffredini` in the YAML file?

Ah - no. Only in the PR description. Got it (hopefully)...

**Comment by rzanner** [comment]
I just confirmed with @gianluca-soffredini - `gsoffredini` is his Artifactory (and JIRA) username. :sweat_smile:

**Comment by NotMyFault** [comment]
> just confirmed that he was able to login to Artifactory - do we need to re-open the PR?

No, the job fetching Jira users runs every 2h. After the next run, I'll trigger a new build.

**Review by NotMyFault — APPROVED** [review]

**Comment by rzanner** [comment]
Good morning, @NotMyFault! 

Many thanks for creating the repository for the [delivery-pipeline-plugin](https://github.com/jenkinsci/delivery-pipeline-plugin) and granting me access to it. 
I just happened to realize that my colleague @gianluca-soffredini was not having any permissions on the new repository (probably because he did not accept your invite?).

I invited him to the project and gave him explicit "Admin" permissions now.

But: I guess that's not the "right" way to do it, am I right? 

I noticed there's a team called "[delivery-pipeline-plugin Developers](https://github.com/orgs/jenkinsci/teams/delivery-pipeline-plugin-developers)" where I am the only member so far. All members of this group have "Admin" permissions on the delivery-pipeline-plugin repository.
I wanted to ask you if you could give me the "Maintainer" role for this group, so that I can add my colleague as a "Maintainer" as well.

Thank you and kind regards,
René

**Comment by timja** [comment]
I've made you a maintainer, but you aren't able to invite people to the org so still need either these requests filed:
https://github.com/jenkins-infra/repository-permissions-updater/issues/new?assignees=&labels=github-permissions&projects=&template=5-github-permissions.yml

or if they want manual release permissions then send a PR to https://github.com/rzanner/repository-permissions-updater/blob/master/permissions/plugin-delivery-pipeline-plugin.yml and their github can be added at the same time

**Comment by rzanner** [comment]
Thanks a lot, @timja - that was already enough. @gianluca-soffredini is already part of the jenkinsci organization. He was just missing in the team and I couldn't add him until now. 
😄

**Pull request merged**
