### PR TITLE
Add 'lenin_atlassian' to 'Atlassian Jira Software Cloud' plugin

### PR DESCRIPTION
**Pull request by lenin-atlassian**
# Description

Allow 'lenin_atlassian' (username of my account at accounts.jenkins.io) to deploy the plugin 'Atlassian Jira Software Cloud'.

GitHub repository: https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin
Plugin Homepage: https://plugins.jenkins.io/atlassian-jira-software-cloud/

cc @rafalmyslek 
# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by lenin-atlassian** [comment]
@slide Can you please review and merge this? (Similar to https://github.com/jenkins-infra/repository-permissions-updater/pull/1189)

**Comment by timja** [comment]
@lenin-atlassian this needs approval from @rafalmyslek

**Comment by rafalmyslek** [comment]
I approve

**Comment by lenin-atlassian** [comment]
@timja Rafal has approved. Can you merge now?

**Pull request merged**
