### PR TITLE
added froque as maintainer to plugin usage

### PR DESCRIPTION
**Pull request by froque**
# Description

The link to plugin repository: https://github.com/jenkinsci/plugin-usage-plugin

pinging @michallaskowski for confirmation.

My github user is @froque and it should be granted GitHub merge access. 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by michallaskowski** [comment]
I approve. Thank you.

**Comment by froque** [comment]
@slide @michallaskowski I don't believe I have commit access to https://github.com/jenkinsci/plugin-usage-plugin repository

**Comment by slide** [comment]
You didn't check the box in the PR template saying you needed GitHub access. That is why we have a PR template, so we know where to look for certain things. You did mention it in the comment, but there is a reason we have check boxes.

**Comment by slide** [comment]
```
06:40 <+Slide-O-Mix> jenkins-admin: make froque a committer on plugin-usage-plugin
06:40 <@jenkins-admin> Added froque as a GitHub committer for repository plugin-usage-plugin
```

**Pull request merged**
