### PR TITLE
Add gmoore to plugin-contrast-continuous-application-security.yml

### PR DESCRIPTION
**Pull request by gmoore**
# Description

Grant @gmoore permission to deploy contrast-continuous-application-security

cc @meg23

https://github.com/jenkinsci/contrast-continuous-application-security-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
You will also need GitHub commit access, correct?

**Comment by gmoore** [comment]
Yes, please. Thanks for your help. First time going through all of this.

**Comment by daniel-beck** [comment]
@meg23 Please approve this request.

**Comment by meg23** [comment]
I approve this message. Please add gsmoore.

**Pull request merged**
