### PR TITLE
add maintainer to travis-yml plugin

### PR DESCRIPTION
**Pull request by kanekotic**
hello I am adding myself to get maintaining and push permissions for the travis-yml plugin , @masaki is on the loop, and I have been already added as contributor on his [repository](https://github.com/masaki/jenkins-travis-yml-plugin/graphs/contributors)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@masaki Could you please confirm? Thanks.

**Comment by daniel-beck** [comment]
This looks like the wrong repo, it even links to the jenkinsci one in the description…?

**Comment by kanekotic** [comment]
what do you mean with the wrong repo?

**Comment by masaki** [comment]
@daniel-beck 
I confirmed, co-maint with @kanekotic the travis-yml-plugin.
And, correct repo is https://github.com/jenkinsci/travis-yml-plugin ?

Thanks.

**Comment by daniel-beck** [comment]
@masaki Thanks.

We strongly prefer plugins be maintained in the jenkinsci organization so we can provide continuity in the case of maintainers moving on. See e.g.:

https://wiki.jenkins-ci.org/display/JENKINS/Governance+Document#GovernanceDocument-Plugins
https://wiki.jenkins-ci.org/display/JENKINS/Pull+Request+to+Repositories

Note that we've since become a bit stricter wrt granting commit access to anyone who asks, and e.g. require that maintainers be directly contacted (and we wait for longer than a week).

**Comment by kanekotic** [comment]
ok so in the case now that I will help maintain the project, do I have the rights to accepts PR and close issues on the jenkins ci repo? (https://github.com/jenkinsci/travis-yml-plugin)
or how should I request that?

**Comment by daniel-beck** [comment]
@kanekotic You just did, and you should have an invitation into the jenkinsci organization in your email inbox.

**Comment by kanekotic** [comment]
thanks a lot @daniel-beck

**Comment by masaki** [comment]
@daniel-beck @kanekotic Thanks a lot!

**Pull request merged**
