### PR TITLE
Enables cd permissions for plugin-signpath

### PR DESCRIPTION
**Pull request by paulsavoie**
# Link to GitHub repository

https://github.com/jenkinsci/signpath-plugin

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

In this PR

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation.
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
You forgot to fill out the PR template.

**Comment by paulsavoie** [comment]
> You forgot to fill out the PR template.

Hello, sorry for the late reply, the message got lost on me. I don't understand the template. All I want to do is enabled the automated releases. It says to reference the PR that is performing this change. From my understanding, this very PR that I am commenting on is the one.

**Comment by timja** [comment]
It should be a PR in this repository for making the Maven and GitHub workflow changes required:
https://github.com/jenkinsci/signpath-plugin

see
https://www.jenkins.io/doc/developer/publishing/releasing-cd/

**Comment by paulsavoie** [comment]
Thank you @timja - and again sorry for the delay. GitHub notification unfortunately go nowhere for me. There is no such PR in https://github.com/jenkinsci/signpath-plugin, we've fulfilled all the criteria (as far as I can tell) separately and most of them from the beginning.
All that's missing is the change in this (jenkins-infra repo) PR.

**Comment by timja** [comment]
As far as I can tell you've done none of https://www.jenkins.io/doc/developer/publishing/releasing-cd/
Please check it closer

**Comment by volbobvol** [comment]
Dear @timja
thank you for guiding us through the release process. Could you please check this PR:

https://github.com/jenkinsci/signpath-plugin/pull/17 

regards,
Volodymyr

**Comment by NotMyFault** [comment]
> As far as I can tell you've done none of [jenkins.io/doc/developer/publishing/releasing-cd](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) (apart from this PR) Please check it closer

But this PR doesn't address https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config at all.

**Comment by volbobvol** [comment]
> But this PR doesn't address https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config at all.

Thank you for your thorough review.

This part was already in the main branch, which is why it is not in the pull request. I should have mentioned it in the PR description. See the following files:
- https://github.com/jenkinsci/signpath-plugin/blob/main/.mvn/maven.config
- https://github.com/jenkinsci/signpath-plugin/blob/main/pom.xml

We would like to have a manually controlled prefix. The only difference that I see, and which I'm not sure about, is in the maven.config file.

In the example, the revision is set to 1 - `<revision>1</revision>`. We already have version 2.0.1, so ideally, we would like to continue versioning if possible. 

Additionally, the second one, `<changelist>999999-SNAPSHOT</changelist>`, is empty in our codebase: `<changelist></changelist>`.

regards,
Volodymyr

**Comment by volbobvol** [comment]
Hi @timja and @NotMyFault,

I wanted to follow up on my last comment. We've already made the required changes in the main branch, which is why they aren't reflected in this PR. Here are the files for your reference:

[.mvn/maven.config](https://github.com/jenkinsci/signpath-plugin/blob/main/.mvn/maven.config)
[pom.xml](https://github.com/jenkinsci/signpath-plugin/blob/main/pom.xml)
Could you please review and let us know if anything else is needed? We’re eager to move forward and appreciate your guidance.

Thanks,
Volodymyr

**Comment by timja** [comment]
These two lines (version and changelist) are still not correct, please review the documentation and adapt:
https://github.com/jenkinsci/signpath-plugin/blob/e0b85b951934c0e03ef88194af3414dbb96ec5ef/pom.xml#L12

https://github.com/jenkinsci/signpath-plugin/blob/e0b85b951934c0e03ef88194af3414dbb96ec5ef/pom.xml#L16

**Comment by volbobvol** [comment]
Hi @timja

Thank you for the review.

I've created a new pull request to address the changes you mentioned:
https://github.com/jenkinsci/signpath-plugin/pull/25

Thanks,
Volodymyr

**Comment by volbobvol** [comment]
Hi @timja and @NotMyFault,

I wanted to follow up on my pull request. Have you had a chance to review it?
https://github.com/jenkinsci/signpath-plugin/pull/25

Thanks,
Volodymyr

**Comment by timja** [comment]
> Hi @timja and @NotMyFault,
> 
> I wanted to follow up on my pull request. Have you had a chance to review it? [jenkinsci/signpath-plugin#25](https://github.com/jenkinsci/signpath-plugin/pull/25)
> 
> Thanks, Volodymyr

I reviewed https://github.com/jenkinsci/signpath-plugin/pull/25 on August 19th and you haven't responded to the review =/

**Comment by volbobvol** [comment]
Hi @timja, thank you for your review.

Your last finding has now been addressed:

>These two lines (version and changelist) are still not correct, please review the documentation and adapt:
> https://github.com/jenkinsci/signpath-plugin/blob/e0b85b951934c0e03ef88194af3414dbb96ec5ef/pom.xml#L12
> https://github.com/jenkinsci/signpath-plugin/blob/e0b85b951934c0e03ef88194af3414dbb96ec5ef/pom.xml#L16

These two lines have been updated and now align with the "Manually controlled prefix (optional)" version approach.

Is there anything else we need to enable for CD?

**Comment by volbobvol** [comment]
Hi @timja and @NotMyFault,

I wanted to check in again regarding the pull request. Do you think we’re ready to proceed with enabling CD?

Thanks for your time,
Volodymyr

**Comment by timja** [comment]
Sorry not sure what happened here I should have merged when I approved your other PR

**Pull request merged**
