### PR TITLE
Add ljader as developer to ssh-plugin

### PR DESCRIPTION
**Pull request by ljader**
# Description

This is to release the ssh-plugin after merge of PR https://github.com/jenkinsci/ssh-plugin/pull/16

CC @edmund-wagner and @stephenc

### CODE REVIEW

**Comment by daniel-beck** [comment]
@ljader Is @edmund-wagner active as maintainer, or will you be taking over this plugin?

**Comment by ljader** [comment]
@daniel-beck honestly I haven't seen @edmund-wagner activity on the ssh-plugin recently, so I believe no.

I cannot assure that I will have time to actively monitor new issues in the future for ssh-plugin.

My current plan is to release 2.5 version, which migrates to using ssh-credentials-plugin.
Then I'll make another "bugfix" release and fix few minor issues from JIRA.

**Comment by daniel-beck** [comment]
Let's wait for @edmund-wagner for a bit then. If you have other means to contact him asking for approval of this request, please do so.

**Comment by daniel-beck** [comment]
Maybe @johnny-b-goode could approve this request as well, he's also a committer of the ssh-plugin.

**Comment by daniel-beck** [comment]
Looks to me like @johnny-b-goode is still around based on the comment to the other PR so I'd really like to first get his opinion before making you a committer.

**Comment by johnny-b-goode** [comment]
@daniel-beck I am OK with adding @ljader as a committer.

**Comment by daniel-beck** [comment]
@johnny-b-goode Could you please clarify whether he should also have permission to release the plugin (this PR)?

**Comment by johnny-b-goode** [comment]
@daniel-beck Sorry for the late response. I am OK with him being able to release the plugin.

**Pull request merged**
