### PR TITLE
Add basil to http_request

### PR DESCRIPTION
**Pull request by basil**
# Description

My primary interest in adopting this plugin is to refresh the plugin metadata and to merge and release the Guava fix in jenkinsci/http-request-plugin#63. I may keep maintaining the POM/BOM and merging/releasing minor bug fixes, but I can't promise major feature development, security fixes, or in-depth code reviews.

- https://github.com/jenkinsci/http-request-plugin

CC @oleg-nenashev as an existing maintainer

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by timja** [comment]
@janario also

**Comment by basil** [comment]
May I invoke the two week timeout policy?

**Review by oleg-nenashev — APPROVED** [review]
I am not really an "existing maintainer", just caretaker after the releases of tables-to-divs & Co. +1 from me

**Comment by oleg-nenashev** [comment]
@basil Please ping me in the PRs waiting for me. Otherwise it may take me a while to get to them. Huge queue after the recent months

**Comment by basil** [comment]
Thanks, Oleg! Could I please get write permissions on the GitHub repository?

**Comment by timja** [comment]
Done

**Pull request merged**
