### PR TITLE
Initialize the permission file for bytecode-compatiliby-transformer

### PR DESCRIPTION
**Pull request by batmat**
I would like to be able to release a 2.x pre-release of [bytecode-compatibility-transformer](https://github.com/jenkinsci/bytecode-compatibility-transformer/b) that includes ASM6 with https://github.com/jenkinsci/bytecode-compatibility-transformer/pull/9, to keep doing baby steps with moving forward our Java 9 compatibility.

Please @kohsuke @rtyler @markewaite @jglick @abayer @jtnord @daniel-beck can you weigh in? Thanks

# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by batmat** [comment]
> Maybe add @jtnord 
@jglick I did, actually (and no, I didn't edit the description in the meantime) :-).

**Comment by slide** [comment]
:+1: from me, though I don't know that I actually matter :)

**Comment by batmat** [comment]
> :+1: from me, though I don't know that I actually matter :)

@slide you absolutely do, definitely. You're one of the masterpieces of that community :-).

> If an approval without comprehension is helpful, then I approve.

Thanks @MarkEWaite, it's to fix at least https://issues.jenkins-ci.org/browse/JENKINS-46602 and move forward with Java 9 compatibility essentially.

**Comment by batmat** [comment]
Thanks everyone!

**Comment by jglick** [comment]
>> Maybe add @jtnord
>
> I did, actually

Uh, where? I see only

```yaml
developers:
- "batmat"
```

**Comment by batmat** [comment]
@jglick OK, I misunderstood, I thought you were talking about asking a review from him. Like in 
image

**Pull request merged**
