### PR TITLE
Enable CD for gerrit-checks-api-plugin

### PR DESCRIPTION
**Pull request by tdraebing**
# Description

Enable use of CD for [gerrit-checks-api-plugin](https://github.com/jenkinsci/gerrit-checks-api-plugin).

Change implementing changes required for CD: https://review.gerrithub.io/c/jenkinsci/gerrit-checks-api-plugin/+/547445

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
There's no open pull request on GitHub.

**Review by NotMyFault — APPROVED** [review]

**Comment by tdraebing** [comment]
> If you don't work with PRs and labels, CD will not work as intended for you.

Yes, I thought as much. If it doesn't work at all, I will switch back to using GitHub and PRs. Would only the creation of release notes not work or what else might not work?

**Comment by NotMyFault** [comment]
CD will automatically cut a release, if a PR with an interesting label has been merged, like 'bug' or 'enhancement', but if there are no PRs (labeled correctly), no automatic releases will take place.
You still have the opportunity to trigger a release by hand, but that kinda defeats the purpose of automatic release workflows.

Additionally, you don't have any release notes at all.

**Comment by tdraebing** [comment]
Ok. We will move back to GitHub moving forward. I would than trigger the initial release manually from GitHub. Could you then merge this PR? Or is something still missing?

**Pull request merged**
