### PR TITLE
added plugin-pipeline-dependency-walker.yml

### PR DESCRIPTION
**Pull request by estarter**
# Description

Adds the Pipeline step ‘walk’ to execute a pipeline task for the job and all its downstream jobs.

Git repo: https://github.com/jenkinsci/pipeline-dependency-walker-plugin
Hosting issue: https://issues.jenkins-ci.org/browse/HOSTING-256

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks good, although I wonder about the chosen groupId. *Pipeline* was born as *Workflow*, hence the groupId. For a new plugin, I'm not sure how useful that is.

Not a blocker, just a suggestion to consider.

CC @jglick WDYT?

**Comment by daniel-beck** [comment]
Merging as is, groupId can always be changed later.

**Comment by estarter** [comment]
Thanks @daniel-beck !
i'm not clear whether I should change the group id. Please tell me me if I should do it!

**Comment by daniel-beck** [comment]
@estarter Entirely your choice. Note that plugins by default use `org.jenkins-ci.plugins`, so maybe go with the default?

**Pull request merged**
