### PR TITLE
Add andytinkham & itsbrugu to conjur-credentials-plugin developers

### PR DESCRIPTION
**Pull request by andytinkham**
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>

# Description

Add Jenkins users andytinkham and itsbrugu (github users: @andytinkham and @itsbrugu) to developers for https://github.com/jenkinsci/conjur-credentials-plugin. We will need merge access to the repo, please. (Tag: @cyberark-bizdev for confirmation)

# Submitter checklist for adding or changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by andytinkham** [comment]
I'm not sure why the Validation step says I need to log into artifactory. I did that just prior to submitting the PR... Is there something I missed?

**Comment by NotMyFault** [comment]
I don't need 4 additional mails 🥴 

We (the hosting team) can trigger builds ourselves too.

**Comment by andytinkham** [comment]
> I don't need 4 additional mails 🥴
> 
> We (the hosting team) can trigger builds ourselves too.

Sorry - the Details for the Validation says to Close and reopen the PR.  The Validation check is still failing though. I have logged in to Artifactory, however.

**Comment by halkeye** [comment]
It can take up to an hour for people to show up in https://reports.jenkins.io/artifactory-ldap-users-report.json

**Comment by halkeye** [comment]
> Oh, I see it's hourly rebuild. OK - I'll trigger the rebuild in an hour.

where are you seeing hourly rebuild?

**Comment by andytinkham** [comment]
> where are you seeing hourly rebuild?

I meant "refresh", and it's in the Details for the Validation as well.

**Comment by andytinkham** [comment]
> It can take up to an hour for people to show up in https://reports.jenkins.io/artifactory-ldap-users-report.json

It was over 2 hours ago when I logged in, and I do show up in that json.

**Comment by andytinkham** [comment]
Oh, I see I need to get Brugu to log into Jira now. There wasn't anything about that in the PR template. I'll have him do so, and then let you all retrigger builds.

**Comment by slide** [comment]
I submitted a PR for updating the instructions: https://github.com/jenkins-infra/repository-permissions-updater/pull/2894

**Comment by andytinkham** [comment]
Brugu tells me he has now signed in to Jira, so please trigger a rebuild. Thanks!

**Comment by NotMyFault** [comment]
> Brugu tells me he has now signed in to Jira, so please trigger a rebuild. Thanks!

Looks all good, all this PR needs is approval by the maintainer you mentioned.

**Comment by andytinkham** [comment]
I've pinged him internally as well. Hopefully, he'll approve it soon. Thanks for all the help & guidance & patience on this!

**Comment by cyberark-bizdev** [comment]
approve

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
