### PR TITLE
Enable cd on Material Theme

### PR DESCRIPTION
**Pull request by timbrown5**
# Description
Enable the cd option for this plugin.

### CODE REVIEW

**Comment by halkeye** [comment]
we need one of the existing maintainers to approve

Also if you want to be listed as one of the developers (who can release), we need you to login to jira and artifactory

**Comment by timja** [comment]
> we need one of the existing maintainers to approve
> 
> Also if you want to be listed as one of the developers (who can release), we need you to login to jira and artifactory

Tim is the maintainer, I assume he's matching Jira to GitHub in this.

**Comment by halkeye** [comment]
who is canuck1987 then?

**Comment by halkeye** [comment]
> who is canuck1987 then?

ah, also tim brown - https://issues.jenkins.io/secure/ViewProfile.jspa?name=canuck1987

**Comment by timbrown5** [comment]
Yeah, sorry. I have two accounts on Jira (I forgot I had Canuck when I
wanted to raise an issue, so created the new one).
I should rationalise it at some point (probably to timbrown5 as that is my
GitHub account).

**Comment by timja** [comment]
Did you want to use the timbrown one or the old one? If you want timbrown you’ll need to login to Jira and artifactory

**Comment by timja** [comment]
Ping @timbrown5 ?

**Pull request merged**
