### PR TITLE
Add developer for custom-tools-plugin

### PR DESCRIPTION
**Pull request by robertohern83**
Adding rhernandezm as a developer for
https://github.com/jenkinsci/custom-tools-plugin

# Description

# Submitter checklist for adding or changing permissions

Plugin: https://github.com/jenkinsci/custom-tools-plugin
Adding a new uploader: rhernandezm, for the jenkins plugin custom-tools-plugin
@oleg-nenashev @uhafner 
GithubUser added: https://github.com/robertohern83

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by robertohern83** [comment]
Hi, I've logged several times to artifactory since yesterday. I've logged again just in case.

**Comment by robertohern83** [comment]
I don't understand why validations are failing, I've logged to jira and artifactory with rhernandezm several times. Am I forgetting something?

**Comment by oleg-nenashev** [comment]
Thanks for stepping up as a plugin maintainer! Any contributions to this plugin will be much appreciated. Unfortunately I have not had enough time to dedicate to it in the recent years

**Comment by MarkEWaite** [comment]
The repository permissions updater job is failing.  It appears to be due to Microsoft moving the Azure CLI docker image from Docker to Microsoft Container Registry.

**Comment by MarkEWaite** [comment]
> The repository permissions updater job is failing on trusted.ci.jenkins.io. It appears to be due to Microsoft moving the Azure CLI docker image from Docker to Microsoft Container Registry.

Repository permissions updater job has been repaired.  Special thanks to @olblak for the fix!

**Pull request merged**
