### PR TITLE
add some more folks to permissions for releasing blue ocean

### PR DESCRIPTION
**Pull request by michaelneale**
cc @daniel-beck @rtyler

### CODE REVIEW

**Comment by daniel-beck** [comment]
What about https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/pom-blueocean-parent.yml ?

**Comment by michaelneale** [comment]
*sigh* this is getting tedious. 

OK added those @daniel-beck  (didn't even know about that file)

**Comment by michaelneale** [comment]
dat logo ;)

**Comment by oleg-nenashev** [comment]
👍

**Comment by daniel-beck** [comment]
@michaelneale 

> sigh, really wish didn't have to do this

As do I. If you have a better idea, I'd like to know. (Combining all related components into one file may work for this particular zoo of plugins, but little else.)

**Comment by michaelneale** [comment]
@daniel-beck yeah its mostly tedious for multi module plugins (which have their own issues, and probably aren't always a good idea). Security is often an enemy in ease of use by necessity, sadly..

**Comment by daniel-beck** [comment]
@michaelneale FYI at least @scherler has not logged in yet, resulting in permissions update failure.

https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by michaelneale** [comment]
@daniel-beck yeah hopefully he will. Ideally this could skip over mistaken user id's.

**Comment by daniel-beck** [comment]
@michaelneale Permissions are now getting applied.

**Pull request merged**
