### PR TITLE
Create plugin-viber-notification.yml

### PR DESCRIPTION
**Pull request by vinaypuranik**
# Description

Source code hosted at - https://github.com/jenkinsci/viber-notification-plugin

Hosting issue url:
https://issues.jenkins-ci.org/browse/HOSTING-309

https://issues.jenkins-ci.org/browse/INFRA-1124

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by vinaypuranik** [comment]
Awaiting PR review and merge.

**Comment by daniel-beck** [comment]
I unchecked the items in your list that are incomplete or wrong. Please fix those.

**Comment by vinaypuranik** [comment]
Hi, 
Source code is hosted at -  https://github.com/jenkinsci/viber-notification-plugin

If above is not the correct link. Could you please let me know which link to include for "resolved HOSTING issue" ? 

Regards,
Vinay

**Comment by vinaypuranik** [comment]
Hi,

I have made the changes as suggested. Kindly, check and let me know for any
amendments.

Regards,
Vinay

**Comment by batmat** [comment]
@vinaypuranik you need to fix the file name. ${artifactId} is a placeholder.

**Comment by vinaypuranik** [comment]
@batmat Done. Kindly verify and approve. Please let me know for any other corrections.

**Comment by vinaypuranik** [comment]
Done. Could you please verify and approve?

Regards,
Vinay

**Pull request merged**
