### PR TITLE
Added ppaczyn to parameter-separator

### PR DESCRIPTION
**Pull request by pit3k**
# Description

https://github.com/jenkinsci/parameter-separator-plugin

@pit3k

I've been given GitHub Admin access by @olhado, in order to become new maintainer of this plugin.
Proof that I have commit access (I've merged a pull request): https://github.com/jenkinsci/parameter-separator-plugin/commit/36a4abe1d1a94fdca8a1c2ca3f857e09b14b1e3f

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by timja** [comment]
@olhado can you approve please?

**Comment by pit3k** [comment]
https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/indexing/console
> Error while processing pull request 1630
> Reason: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/jenkins-infra/repository-permissions-updater/collaborators/pit3k/permission {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level"}

Is this a generic problem on your side or perhaps this is because I'm not a member of "jenkinsci" GitHub organization? If so, how can I remedy that?

**Comment by timja** [comment]
the problem is on our side

**Comment by timja** [comment]
I've fixed the build issue

**Pull request merged**
