### PR TITLE
Add @batmat to extended-read-permission releasers

### PR DESCRIPTION
**Pull request by batmat**
As agreed with @dty

_(This PR template only applies to permission changes -- ignore for changes to the tool)_

# Description

_As discussed with @dty privately, I am taking over maintenance of https://github.com/jenkinsci/extended-read-permission-plugin/. So I need to be allowed to release for that purpose. (still waiting for public ack on https://groups.google.com/d/msg/jenkinsci-dev/bCvDTWciRz0/xxhjZ91RDQAJ though)._

# Permissions pull request checklist

### Always

- [X] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- N/A (already existing)

### For a new permissions file only

- [X] Make sure the file is created in `permissions/` directory
- [X] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [X] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [X] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
"As agreed with @dty" seems to be wrong, though we can move forward due to the response timeout

**Comment by batmat** [comment]
@oleg-nenashev Actually, it's not wrong, but I'm not going to paste a private email in public without an explicit approval.

Anyway, you're right, my initial email on the ML dates back to the 19th of February, so we're past the typical ~2 weeks of delay.

@daniel-beck WDYT, can we now merge?

cc @orrc @slide for possible feedback as usual reviewers here.

Thanks!

**Comment by slide** [comment]
Looks fine to me

**Comment by daniel-beck** [comment]
Timeouted.

Also, I think we can trust @batmat to not make things up.

**Comment by batmat** [comment]
Thanks @oleg-nenashev @slide and @daniel-beck  !

**Pull request merged**
