### PR TITLE
Enable CD for plugin-mysql-api

### PR DESCRIPTION
**Pull request by jonesbusy**
# Link to GitHub repository

https://github.com/jenkinsci/mysql-api-plugin/pull/4

Ping @cleclerc Do you agree with this ?

It's similar to the 'plugin-postgresql-api'

Also can an admin restart Jenkins build due to Jenkinsfile changes ?

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/mysql-api-plugin/pull/4

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
The plugin looks abandoned to me. I think you could adopt it for now and merge the PR yourself, thoughts?

**Comment by jonesbusy** [comment]
Fine for me!

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
For the refreshing PR I'd recommend to align it with the current archetypes version, which tests a different Java version: https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile
Configurating dependabot has a positive impact on the plugin's [health score](https://plugins.jenkins.io/mysql-api/healthscore/) too.

**Comment by jonesbusy** [comment]
> For the refreshing PR I'd recommend to align it with the current archetypes version, which tests a different Java version: https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile
> Configurating dependabot has a positive impact on the plugin's [health score](https://plugins.jenkins.io/mysql-api/healthscore/) too.

Sure I will thanks

**Pull request merged**
