### PR TITLE
component-jenkins-test-harness + olamy

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by daniel-beck** [comment]
I don't think we have a maintainer of this per se, @jglick comes closest perhaps?

**Comment by olamy** [comment]
@daniel-beck @jglick I don't mind being or not in the file. I just will be happy about a release with this change https://github.com/jenkinsci/jenkins-test-harness/commit/67e38f5d8ee18ce673c3bd0ce39e2423ceb836e1
Thanks!

**Comment by daniel-beck** [comment]
@jglick PTAL -- looks like a release would be useful?

@olamy Please ping me in a day if Jesse hasn't responded.

**Comment by oleg-nenashev** [comment]
I have thought it has been already released :(
Unfortunately I am also not in the list hence I cannot spin it as well.
CC @olivergondza @andresrc @stephenc could somebody release it?

**Pull request merged**
