### PR TITLE
Request upload permission for azure-iot-edge

### PR DESCRIPTION
**Pull request by michaeljqzq**
# Description

Request upload permission for the following plugins:
### Azure IoT Edge Plugin
[http://github.com/jenkinsci/azure-iot-edge-plugin](http://github.com/jenkinsci/azure-iot-edge-plugin)
[https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-629](https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-629)

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by michaeljqzq** [comment]
@daniel-beck Could you help review this PR, thanks

**Comment by daniel-beck** [comment]
Build failure is real, not all users exist in Artifactory.

**Comment by michaeljqzq** [comment]
@daniel-beck , I confirmed again the the following 2 accounts specified in Yaml file existed and have logged in to Artifactory at least once. Is there anything else I need to do?

- "michaeljqzq"
- "azure_iot_tooling"

account1
account2
account3
account4

**Comment by michaeljqzq** [comment]
@daniel-beck  Can you help me look at this? As the snapshot above, I already registered and logged in to Artifactory for accounts, and I even tried removing the developers in this [PR](https://github.com/jenkins-infra/repository-permissions-updater/pull/861), but the build still failed.
It is quite urgent blocking issue for me, thanks

**Comment by oleg-nenashev** [comment]
Retriggered the build

**Comment by daniel-beck** [comment]
Actual culprit is https://github.com/jenkins-infra/repository-permissions-updater/pull/856 being merged with bad data, now all PR builds are failing. The assumption here is that master is good and only PRs can be bad, which was violated here.

**Pull request merged**
