### PR TITLE
Add `timja` as a maintainer to commons-lang3-api plugin

### PR DESCRIPTION
**Pull request by timja**
# Description

@nhojpatrick I'd like to help out with this could you approve please?

see some issues:
https://github.com/jenkinsci/commons-lang3-api-plugin/issues/18
https://github.com/jenkinsci/commons-lang3-api-plugin/issues/12

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [x] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by jglick — APPROVED** [review]
(non-voting :+1:)

**Review by MarkEWaite — APPROVED** [review]
Considering the challenges with https://issues.jenkins.io/browse/JENKINS-69034 and the importance of providing a solution as soon as we can, I recommend that we make an exception for the adoption process and allow that @timja can immediately be added as a plugin maintainer.

**Comment by halkeye** [comment]
> I recommend that we make an exception for the adoption process

I feel like instead of asking the few people on this thread, it should goto dev mailing list for board approval (Since its skipping past the established procedures)

**Comment by MarkEWaite** [comment]
> > I recommend that we make an exception for the adoption process
> 
> I feel like instead of asking the few people on this thread, it should goto dev mailing list for board approval (Since its skipping past the established procedures)

[Request](https://groups.google.com/g/jenkinsci-dev/c/Zt0jyM7gfME/m/elNPb0u5BAAJ) has been posted to the Jenkins developer mailing list.

**Comment by daniel-beck** [comment]
The easy fix without plugin governance challenges is to remove the ill-advised dependency from configuration-as-code, reverting https://github.com/jenkinsci/configuration-as-code-plugin/pull/1979. It seems unnecessary to go over maintainers' heads while that's an option. While this is the only plugin with the dependency, there's no benefit in conflict prevention anyway, and the PR provides no justification.

**Comment by timja** [comment]
Proceeding

**Pull request merged**
