### PR TITLE
Added new developer to release the Kiuwan plugin

### PR DESCRIPTION
**Pull request by jsalado**
Added developer kwjsalado (Javier Salado)

# Description

Requesting permission for a new developer to release the kiuwanJenkinsPlugin
@jptejela
https://github.com/jenkinsci/kiuwan-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@kiuwan would probably be the one to approve this request.

**Comment by kiuwan** [comment]
Approved

The Kiuwan Team

**Comment by daniel-beck** [comment]
@jsalado Please let me know if you need access to push to the GitHub repo.

**Comment by jsalado** [comment]
@daniel-beck if that is to push the Kiuwan plugin code to the github.com/jenkinsci/kiuwan-plugin repo it can be handled by someone else in the team but it may be helpful if I have that push access as well.
Thanks

**Comment by daniel-beck** [comment]
@jsalado Done. You may need to accept an invitation into the jenkinsci org sent via email.

**Comment by jsalado** [comment]
@daniel-beck I've followed al the instruction in this article https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Requestuploadpermissions to have my user kwjsalado have permissions to release new versions of our plugin including uploading it to repo.jenkins-ci.org.

I think I have everything configured correctly: I created the account in the Jenkins community, logged in to https://repo.jenkins-ci.org/webapp, changed my password, get the encrypted password and put it the correspondent <server> tag in the .m2/settings.xml, requested the upload permissions here, got it approved and committed and merged...

Still I get a 401 when uploading:
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project kiuwanJenkinsPlugin: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:kiuwanJenkinsPlugin:hpi:1.4.6 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases): Failed to transfer file: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/kiuwanJenkinsPlugin/1.4.6/kiuwanJenkinsPlugin-1.4.6.hpi. Return code is: 401, ReasonPhrase: . -> [Help 1]

Is there anything else I'm missing? Do I have to wait until the requested permissions are propagated?
Thanks

**Comment by daniel-beck** [comment]
401 is unauthorized, meaning your password is wrong or does not get sent. Make sure to specify the repository ID `maven.jenkins-ci.org` in the settings.xml, even though that host is long down. It's just an ID.

**Pull request merged**
