### PR TITLE
add new maintainer of pipeline-github-plugin

### PR DESCRIPTION
**Pull request by aaronwalker**
This PR is to add myself (@aaronwalker) to be a maintainer of the Jenkins pipeline-github-plugin plugin.

# Description

Link to the plugin: https://plugins.jenkins.io/pipeline-github/
Link to code in GitHub: https://github.com/jenkinsci/pipeline-github-plugin

cc: @aaronjwhiteside 

# Submitter checklist for adding or changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by aaronjwhiteside** [comment]
@aaronwalker why?

**Comment by aaronwalker** [comment]
> @aaronwalker why?

@aaronjwhiteside 

Many hands make light work :) I think having more people as maintainers means changes can be merged and released quicker. 

I'm actually working on a plugin that uses pipeline-github-plugin and I have features I'd like to add to it and also I'd like to push out the 2.8 release with my additional triggers and fixes.

Do you have an objection to additional maintainers?

**Comment by aaronjwhiteside** [comment]
@aaronwalker 

So in theory I don't have any objections to more maintainers, and I'm more than willing to admit I've been poor on time for a while, not enough time to spend really giving this the attention it needs.

The one thing I want to ensure is that we keep true to the original technical vision of providing proxy objects backed by the GitHub APIs. A very rich object oriented approach, I don't want this to just turn into another GitHub API client (think CRUD). I think we can provide a much richer experience than that.. which was the original reason I started this project.

If you're ok with that, then I'm ok with you becoming another maintainer.

After all two Aaron's are better than one ;)

**Comment by aaronwalker** [comment]
@aaronjwhiteside completely agree with you on ensuring the right level of abstraction is maintained. This is the primary reason I choose this plugin in the first place :) 

I'm actually working on a custom plugin which relies on pipeline-github plugin too and I believe some of its functionality would make more sense to be in it. But any new features I would always ant to ran past you first to see if it makes sense.

**Review by aaronjwhiteside — APPROVED** [review]

**Pull request merged**
