### PR TITLE
Update plugin-deployit-plugin.yml

### PR DESCRIPTION
**Pull request by nitheshrayuduv**
Added Jenkins CI Username - Nithesh Rayudu Vaddey - Integrations

# Description

Repo:
https://github.com/jenkinsci/xldeploy-plugin

@FellipeAvanci 

Mentioning users being added
@nitheshrayuduv
@nehag83
@yogeshghotekar
@isaacsatish
@sachgaik-xl
@soni-ankur
@vrushnim
@mflynn001
@balaji-digital-ai

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).

- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by timja** [comment]
you haven't filled out the template?

**Comment by timja** [comment]
These aren't just tick boxes to tick, read what they say and do them.

**Comment by nitheshrayuduv** [comment]
Hi Tim Jacod,
We are adding more people into this(1957) and the 1958 pull request, once we add everyone and once everything is green we will request for the review :) 
Thank you for the information

**Comment by nitheshrayuduv** [comment]
Hi Tim,
These are the new team members who are added to our team those who will be maintaining plugin-deployit-plugin.
Everyone of them did the steps according to the tick boxes.
Thanks and Regards,
Nithesh

**Comment by nitheshrayuduv** [comment]
> please fill out the template

Done, and all the checks are now passing :)

**Comment by timja** [comment]
>  Add link to plugin/component Git repository in description above

??

> Make sure to @mention an existing maintainer to confirm the permissions request, if applicable

??

**Comment by nitheshrayuduv** [comment]
Hi Tim,
I have now added the repository link, but am not sure if that is the repo you were talking about (The link where we made changes to files) and also tagged an existing maintainer to confirm the permissions request.
Let me know if you require any other information.

**Comment by timja** [comment]
no it's the github repository you're requesting access to

**Comment by FellipeAvanci** [comment]
I authorize these developers to get permission to our repo.

**Comment by FellipeAvanci** [comment]
@daniel-beck  these are new devs on my team and I need them to be added so they can have privileges to fix https://issues.jenkins.io/browse/SECURITY-1982 and https://issues.jenkins.io/browse/SECURITY-1981 Thank you

**Comment by daniel-beck** [comment]
@FellipeAvanci Release permissions are not a precondition to be able to work on security fixes as long as any maintainer is involved to approve (unless you choose to ignore my recommendation to prepare fixes in private again); see my comments in SECURITY-1981.

These instructions have been followed successfully many times before now, if they confuse you and it's unclear what they're asking, you can always look up what others did in the past and do something similar (adapted to your request, of course).

**Review by timja — CHANGES_REQUESTED** [review]
missing step:

> Make sure to @mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).

I can't grant access if I don't know their github usernames

**Comment by nitheshrayuduv** [comment]
Have updated the description to have all the people who are being added with their GitHub usernames

**Comment by timja** [comment]
invites sent to github

**Pull request merged**
