### PR TITLE
Update plugin-synopsys-coverity.yml

### PR DESCRIPTION
**Pull request by vhegde2017**
Adding new maintainers

# Description

# Submitter checklist for adding or changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
cc @jcroall to authenticate the request.

All users added need to log into https://issues.jenkins.io/ and https://repo.jenkins-ci.org/ui/login

**Comment by NotMyFault** [comment]
@jcroall This PR overlaps with your other PR (https://github.com/jenkins-infra/repository-permissions-updater/pull/3068), do you approve the addition of this user still?

**Comment by jcroall** [comment]
Took me a second to figure out! it looks like @vhegde2017 who is one of our engineers also added himself to this. I wasn't aware of that change but I approve of it. @vhegde2017 is that also your Jenkins.io account and have you logged into artifactory?

**Comment by vhegde2017** [comment]
Hi,

Yes, it’s my account. Few days back I tried to create my account on Jenkins.io and artifactory. Thanks for approving.

--
Regards
Venkat


From: James Croall ***@***.***>
Date: Friday, 13 January 2023 at 6:36 AM
To: jenkins-infra/repository-permissions-updater ***@***.***>
Cc: Venkatramana Hegde ***@***.***>, Mention ***@***.***>
Subject: Re: [jenkins-infra/repository-permissions-updater] Update plugin-synopsys-coverity.yml (PR #3045)

Took me a second to figure out! it looks like @vhegde2017<https://urldefense.com/v3/__https:/github.com/vhegde2017__;!!A4F2R9G_pg!eCykjmBy1O1wolYYEp3ED3d2akO2ou8JBN90vh5wAB8dIlk59s0WOk4Sm9Alw72XM6vSnI4LAqFHgm0svhvl7eT4$> who is one of our engineers also added himself to this. I wasn't aware of that change but I approve of it. @vhegde2017<https://urldefense.com/v3/__https:/github.com/vhegde2017__;!!A4F2R9G_pg!eCykjmBy1O1wolYYEp3ED3d2akO2ou8JBN90vh5wAB8dIlk59s0WOk4Sm9Alw72XM6vSnI4LAqFHgm0svhvl7eT4$> is that also your Jenkins.io account and have you logged into artifactory?

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
@vhegde2017 

> Few days back I tried to create my account on Jenkins.io and artifactory.

You also need to log into both once.
- https://issues.jenkins.io/
- https://repo.jenkins-ci.org/ui/login

**Comment by NotMyFault** [comment]
I'll go ahead and close this PR. Please re-open the PR once the couple of conditions above are satisfied.

Thanks!

**Pull request closed without merging**
