### PR TITLE
Plugin manager request

### PR DESCRIPTION
**Pull request by stopalopa**
# Description

This requests permissions for the following repository: 
https://github.com/jenkinsci/plugin-installation-manager-tool
The hosting request is here: 
https://issues.jenkins-ci.org/browse/HOSTING-777

Requested for @batmat @kwhetstone @jonbrohauge @arnab1896 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ x] Make sure the file is created in `permissions/` directory
- [ x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)

### When adding new uploaders (this includes newly created permissions files)

- [ x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
Looks like jnz_topdanmark has not logged in to artifactory.

**Comment by jonbrohauge** [comment]
@slide I must have missed something. Could you please drop a link to artifactory, and I'll log into it asap?

**Comment by jonbrohauge** [comment]
nevermind... I RTFM and found it. Logged in now.

**Comment by slide** [comment]
FYI, this is not to get repository access on github, this is to get access to release this tool to the maven repository.

**Pull request merged**
