### PR TITLE
add cashlalala as developer

### PR DESCRIPTION
**Pull request by cashlalala**
# Description

https://github.com/jenkinsci/parameterized-remote-trigger-plugin 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by cashlalala** [comment]
Just FYI, it seems I'm the only active maintainer now which was assigned on 5/10, so I didn't @ anybody else.

**Comment by daniel-beck** [comment]
Please provide a public reference, e.g. a mailing list thread or GitHub PR discussion, for you taking over maintainership of the plugin.

**Comment by cashlalala** [comment]
@daniel-beck ,
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-dev/y1Sv9MQhyaY/PHL751RDBwAJ

**Comment by daniel-beck** [comment]
FYI @kutzi @morficus

Seems only the former was pinged about this? CC @oleg-nenashev

**Comment by oleg-nenashev** [comment]
> Seems only the former was pinged about this? CC @oleg-nenashev

There were multiple public pings to maintainers in GitHub repos with no response. Cristoph was the last person to release the plugin, so it seemed enough to me.

**Comment by daniel-beck** [comment]
@oleg-nenashev OK, thanks. Wasn't aware of all that happened, so IMO we can proceed here.

**Comment by cashlalala** [comment]
@daniel-beck  Is there anything I need provide to proceed? 
Thanks

**Pull request merged**
