### PR TITLE
Add myself to release list

### PR DESCRIPTION
**Pull request by slide**
# Description

Would like release permissions for https://github.com/jenkinsci/change-assembly-version-plugin, cc @lkobus, @nilleb, @znek for sign-off

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@slide Is there a context for permissions that would speed this up, or are we waiting for approval by the pinged users?

**Comment by nilleb** [comment]
I definitely approve, since I wasn't anymore aware of being a maintainer of
this plugin (sorry)

Le mar. 13 févr. 2018 à 18:21, Daniel Beck <notifications@github.com> a
écrit :

**Comment by daniel-beck** [comment]
It's not clear to me what the user list is based on. In the GitHub team, @lkobus and @sankethpb are developers, and here, only the former has access. @slide Could you clarify?

**Comment by slide** [comment]
@daniel-beck This is the context https://github.com/jenkinsci/change-assembly-version-plugin/pull/17#issuecomment-364553617

**Comment by daniel-beck** [comment]
@slide Well, @lkobus merged https://github.com/jenkinsci/change-assembly-version-plugin/pull/4 https://github.com/jenkinsci/change-assembly-version-plugin/pull/5 https://github.com/jenkinsci/change-assembly-version-plugin/pull/7 which are by the other users you mentioned, and how they got into the history, so that doesn't really count 😉 

While @sankethpb is a committer, there's no activity of them I can find, so we'll wait for confirmation by @lkobus; I recommend you try to reach out to them directly.

**Comment by znek** [comment]
Not sure how I got here, but I shouldn't have release permissions. So, no.

**Comment by slide** [comment]
@znek You got here because I used the wrong list in my CC. Sorry about that.

**Comment by daniel-beck** [comment]
Pinging @lkobus and @sankethpb again. We'd appreciate a response, thanks!

**Comment by slide** [comment]
@lkobus replied directly to me via email, but I can ping again if desired for public confirmation.

**Pull request merged**
