### PR TITLE
Adding belltimo and bank @amazon.com to CodePipeline plugin maintainers

### PR DESCRIPTION
**Pull request by belltimo**
Adding belltimo and bank to CodePipeline plugin maintainers.

See: https://issues.jenkins-ci.org/browse/HOSTING-210

https://github.com/jenkinsci/aws-codepipeline-plugin/commits/master

### CODE REVIEW

**Comment by belltimo** [comment]
Hey, I'm still having some trouble deploying.

I'm getting:

```
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project aws-codepipeline: Failed to deploy artifacts: Could not transfer artifact com.amazonaws:aws-codepipeline:hpi:0.19 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/releases): Access denied to: https://repo.jenkins-ci.org/releases/com/amazonaws/aws-codepipeline/0.19/aws-codepipeline-0.19.hpi, ReasonPhrase: Forbidden. -> [Help 1]
```

Will it take some time for these permissions to be applied?

**Comment by daniel-beck** [comment]
> Permission target contains a reference to a non-existing user 'bank'.

https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

While this references users who do not exist in Artifactory, these permissions will not be applied.

**Comment by daniel-beck** [comment]
@belltimo Please see above comment, I forgot to at-mention you.

**Comment by belltimo** [comment]
Thanks, all sorted now!

**Comment by daniel-beck** [comment]
Yep, I see it too.

**Pull request merged**
