### PR TITLE
Enable CD Permissions for plugin-feishu-notification.yml

### PR DESCRIPTION
**Pull request by 721806280**
# Link to GitHub repository

https://github.com/jenkinsci/feishu-notification-plugin

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
The PR template is supposed to be filled out, not to be deleted.

**Comment by NotMyFault** [comment]
@721806280 Are you still interested in enabling CD? Please address my comment above.

**Comment by 721806280** [comment]
> @721806280 Are you still interested in enabling CD? Please address my comment above.

updated

**Comment by NotMyFault** [comment]
> > @721806280 Are you still interested in enabling CD? Please address my comment above.
> 
> updated

Screenshot 2023-07-21 at 10 16 58

You didn't provide such a link.

**Comment by 721806280** [comment]
> updated

updated

**Comment by NotMyFault** [comment]
The plugin is not incrementalified, nor is there a PR linked to review. Please take a look at the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) which files you'll need to modify.

**Pull request closed without merging**
