### PR TITLE
Transferring upload permission to "sat_blazemeter"

### PR DESCRIPTION
**Pull request by dzmitrykashlach**
Transferring upload permissions from `zmicerkashlach` to `sat_blazemeter` for
[BlazeMeterJenkins plugin](https://github.com/jenkinsci/blazemeter-plugin.git)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@dzmitrykashlach have you logged in to Artifactory from that account as suggested in the checklist?

**Comment by daniel-beck** [comment]
They have not.

The checklist for PRs to this repo exists for a reason. Please review it, and complete all items that apply.

**Comment by daniel-beck** [comment]
Context: https://groups.google.com/forum/#!topic/jenkinsci-dev/PXCr9rWzvbw

**Comment by artem-fedorov** [comment]
@oleg-nenashev @daniel-beck 
Could you please describe which steps we skipped? 
- @dzmitrykashlach and me have access to plugin's repository (https://github.com/jenkinsci/blazemeter-plugin)
- we changed pom.xml 
- we created a new account and authorized with it in Jira and Artifactory

**Comment by daniel-beck** [comment]
>  Could you please describe which steps we skipped?

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/.github/PULL_REQUEST_TEMPLATE.md exists for a reason; it makes the job of the not-even-a-handful people who process these requests *much* easier. So I've decided to no longer process requests that don't even bother to do everything described there, even if it's as simple as…

> Add link to plugin/component Git repository in description above

**Comment by dzmitrykashlach** [comment]
@daniel-beck @oleg-nenashev 
Sorry for misunderstanding. 
I've updated initial comment to PR with link to
[BlazeMeterJenkinsPlugin](https://github.com/jenkinsci/blazemeter-plugin)
Thank you for assistance.

**Pull request merged**
