### PR TITLE
Grant access to plugin-snyk-security-scanning to additional team members

### PR DESCRIPTION
**Pull request by adrukh**
# Description

Repository URL: https://github.com/jenkinsci/snyk-security-scanner-plugin

Granting additional access permissions to team members.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added persons also need to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by adrukh** [comment]
I'll restart the build once we complete the signing in stage.

**Comment by yuliabaron** [comment]
Hi @jenkinsadmin,

I see the PR is merged but I do not have permissions to our repo. How an we sort this out?

**Comment by pavel-github** [comment]
me too (no permissions to merge or assign reviewers).
@slide, perhaps we need some sync or something?

**Comment by slide** [comment]
Hmm, let me check.

**Comment by slide** [comment]
I added @pavel-github and @yuliabaron to the committer list. Please make sure you accept the invitation from the jenkinsci org.

**Pull request merged**
