### PR TITLE
Update and rename plugin-castecho.yml to plugin-carl.yml

### PR DESCRIPTION
**Pull request by castnightlybuild**
# Description

Project has been renamed.
new github repo: https://github.com/jenkinsci/Carl-plugin

# Submitter checklist for changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [X] Make sure the file is created in `permissions/` directory
- [X] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [X] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [X] Check that the file is named `plugin-${artifactId}.yml` for plugins

### CODE REVIEW

**Comment by slide** [comment]
Please follow the naming convention for plugin repos and make the whole thing lowercase (carl-plugin).

**Comment by slide** [comment]
I mean the actual repo, not what you have in the file.

**Comment by castnightlybuild** [comment]
Hello,
Sorry but I'm new with pull-requests...
I've commit changes on my repo. Is there anything I must still do to close this pull-request?

**Comment by castnightlybuild** [comment]
OK. Thank you :-)

**Pull request merged**
