### PR TITLE
pipeline-gcp: enable cd

### PR DESCRIPTION
**Pull request by Enigo**
# Link to GitHub repository

https://github.com/jenkinsci/pipeline-gcp-plugin

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/pipeline-gcp-plugin/pull/3

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by Enigo** [comment]
Hi @timja 
Thx for reviewing
Should I merge the PR in the plugin repo myself now?

**Comment by Enigo** [comment]
hi @timja 
the plugin was released last Friday but still not available on https://plugins.jenkins.io/pipeline-gcp
in the documentation it is stated that the update should be available in "a few hours"
is something wrong? or should I be asking somewhere else?

**Comment by timja** [comment]
can you create a [helpdesk](https://github.com/jenkins-infra/helpdesk) ticket please

**Comment by timja** [comment]
Likely this @Enigo: https://github.com/jenkins-infra/helpdesk/issues/3997#issuecomment-2006638867

**Pull request merged**
