### PR TITLE
Add mysql-api plugin

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
# Description

https://issues.jenkins-ci.org/browse/HOSTING-768
https://github.com/jenkinsci/mysql-api-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
There was some concern on irc about the licensing for this plugin since the MySQL connector is gplv2 with no class path exception. Before releasing the plugin, the concerns may need to get addressed. I am not a lawyer, so I can't weigh in myself, but it would need good to figure out the impact

**Comment by cyrille-leclerc** [comment]
@slide I changed the licensing yesterday to prevent misunderstanding. I replaced the ""MIT License" by "The GNU General Public License, v2 with FOSS exception":

```xml
        <license>
            <name>The GNU General Public License, v2 with FOSS exception</name>
            <distribution>repo</distribution>
            <comments>See https://raw.githubusercontent.com/mysql/mysql-connector-j/8.0.16/LICENSE</comments>
        </license>
```

**Comment by slide** [comment]
This looks good to me, @batmat everything good for you on this one?

**Comment by batmat** [comment]
IANAL, but I think this is OK.

**Pull request merged**
