### PR TITLE
Add @oleg-nenashev to the list of Periodic Backup plugin developers.

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Request is here: https://groups.google.com/forum/#!topic/jenkinsci-dev/PrEcN9Etcxg

* Maintainers are in CC (both @emanuelez and Tomasz Blaszczynski). CC @johnou who is not listed in the developer list
* Two weeks have passed
* Nobody responded

So I think that we can proceed with the request without any further authorization.

CC @daniel-beck

### CODE REVIEW

**Comment by daniel-beck** [comment]
As usual in the case of maintainer unresponsiveness, let's give them a few days to respond here.

**Comment by johnou** [comment]
@oleg-nenashev that's cool with me.

**Comment by oleg-nenashev** [comment]
@daniel-beck I think it is ready to go

**Comment by emanuelez** [comment]
Hello there! Interestingly I didn't receive any notification prior an email this morning.
I'm totally fine to have Oleg be the maintainer of the plugin as my current job and family situation doesn't really allow me to dedicate time to it. Thank you very much!

**Comment by oleg-nenashev** [comment]
@emanuelez Thanks for the response! Regarding the emails, I was using the address listed on Wiki (the one at gmail.com).

I will go forward with the release preparations then

**Pull request merged**
