### PR TITLE
Added tommysdk user as Delivery Pipeline Plugin developer

### PR DESCRIPTION
**Pull request by tommysdk**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please note that you need to log in to Artifactory once first (or this isn't the correct user name).

Also, what's the repo for this? It's not in `jenkinsci`. I'd like to see existing maintainers approve of this.

**Comment by tommysdk** [comment]
Hi,

I'm not really familiar with the process. How do I log in to artifactory and where? Is it with my Jenkins JIRA credentials?

Source code repository: https://github.com/Diabol/delivery-pipeline-plugin
Developer section in plugin descriptor: https://github.com/Diabol/delivery-pipeline-plugin/blob/master/pom.xml#L69

I can ask for one of my co-maintainers to approve this here.

@daniel-beck Do you need anything else?

**Comment by patbos** [comment]
I approve

**Comment by daniel-beck** [comment]
@tommysdk 

> I'm not really familiar with the process. How do I log in to artifactory and where? Is it with my Jenkins JIRA credentials?

https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by daniel-beck** [comment]
@patbos Please note that we strongly prefer plugins be hosted within and released from the jenkinsci GitHub organization to be able to provide continuity in case of maintainers moving on, and be able to fix urgent issues (e.g. security). I'd appreciate if you would consider moving.

**Comment by tommysdk** [comment]
@daniel-beck I was successfully able to log in to artifactory.

**Pull request merged**
