### PR TITLE
add new plugin codebeamer-coverage-publisher

### PR DESCRIPTION
**Pull request by abanfi**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by batmat** [comment]
:+1: 

Checked HOSTING-171 for reference, and user name seems correct: https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=abanfi

**Comment by daniel-beck** [comment]
@abanfi Please note that this permission will not be granted until you've logged in to Artifactory at https://repo.jenkins-ci.org once. Even then it may take a while for the permission to be effective. See https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by abanfi** [comment]
Hi Daniel, 

Thank you for the hint, I have missed that.

**Pull request merged**
