### PR TITLE
Add more missing issue links to plugins

### PR DESCRIPTION
**Pull request by NotMyFault**
This is a follow up to https://github.com/jenkins-infra/repository-permissions-updater/pull/2559, which adds more missing issue tracker links to the plugins, allowing them to appear on plugins.jenkins.io and in Jenkins itself through the update center.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
build is failing for a typo somewhere

**Comment by NotMyFault** [comment]
> build is failing for a typo somewhere

There we go, should be good now.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
more apparently 👅

**Comment by NotMyFault** [comment]
Checks are all green, had to read the error twice to understand that we actually need a github repository listed in a file.

**Pull request merged**
