### PR TITLE
Add pdk27 to ec2-fleet-plugin

### PR DESCRIPTION
**Pull request by pdk27**
# Description

Requesting permissions for @pdk27 for https://github.com/jenkinsci/ec2-fleet-plugin

I have Admin privileges to the repo and have commit permission. Here is a PR I recently merged: https://github.com/jenkinsci/ec2-fleet-plugin/pull/344. @cjerad 

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by pdk27** [comment]
I have logged into Artifactory and Jira. I opened the pull request after my account name (pdk27) appeared in https://reports.jenkins.io/artifactory-ldap-users-report.json. Tried closing and re-opening PR, the checks are still failing. Am I missing something? Thanks!

**Comment by NotMyFault** [comment]
> I have logged into Artifactory and Jira. I opened the pull request after my account name (pdk27) appeared in https://reports.jenkins.io/artifactory-ldap-users-report.json. Tried closing and re-opening PR, the checks are still failing. Am I missing something? Thanks!

No, once the next build runs, the status will reflect your actions.

Still needs authorization by an existing maintainer @cjerad @schmutze @haugenj

**Comment by cjerad** [comment]
Hi @NotMyFault, how do I provide authorization? I couldn't find relevant steps in the README.

**Comment by NotMyFault** [comment]
> Hi @NotMyFault, how do I provide authorization? I couldn't find relevant steps in the README.

Leaving a comment that states you're fine with the addition or simply by approving this PR.

**Comment by cjerad** [comment]
@NotMyFault I approve adding @pdk27.

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
