### PR TITLE
Add permissions for qualys-cs plugin

### PR DESCRIPTION
**Pull request by nikita-bedmutha**
# Description

Github repository: https://github.com/jenkinsci/qualys-cs-plugin
Hosting request ticket: https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-871
Committers: @qualys-plugins @pmgupte @lseletos @gwaghmare @pranaybqualys @nikita-bedmutha @gouripatilqualys @aphatangade

https://github.com/jenkinsci/qualys-cs-plugin
# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo. If needed, it can be done using an [IRC bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management). Make sure to check that the `$pluginId Developers` team has `Write` permissions or above while granting the access.

### CODE REVIEW

**Comment by nikita-bedmutha** [comment]
@slide @oleg-nenashev - I am unable to do - mvn release:prepare release:perform , at last step of deploy it fails saying -   Failed to deploy artifacts: Could not transfer artifact .......
Access denied to: https://repo.jenkins-ci.org/releases/com/qualys/plugins/qualys-cs/1.6.0.1/qualys-cs-1.6.0.1.hpi, ReasonPhrase: Forbidden. I have used correct keys, could there be some other reason?

**Comment by slide** [comment]
You are doing this using 4he qualys user credentials?

**Comment by nikita-bedmutha** [comment]
@slide yes, using qualys user.

**Comment by slide** [comment]
Did you follow this tutorial? https://jenkins.io/doc/developer/publishing/releasing/

**Comment by nikita-bedmutha** [comment]
@slide Found the issue, I had mistakenly commited the permissions file outside permissions directory. Have opened a new PR to fix it.

**Comment by slide** [comment]
Ah, I should have caught that.

**Pull request merged**
