### PR TITLE
Update maven-plugin and maven-interceptors

### PR DESCRIPTION
**Pull request by aheritier**
* Add new modules for https://github.com/jenkinsci/maven-interceptors 
* Add missing parent pom for https://github.com/jenkinsci/maven-interceptors 
* Add aheritier as developper for https://github.com/jenkinsci/maven-interceptors and https://github.com/jenkinsci/maven-plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Would be great to have line break at the last line, but LGTM

**Comment by aheritier** [comment]
good idea @oleg-nenashev 
Fixed

**Comment by batmat** [comment]
:+1: 

Why did you add the `needs-authorization` label @daniel-beck ? Have you pinged people off-band and are waiting for their feedback?

**Comment by daniel-beck** [comment]
@batmat This is the responsibility of the PR author per https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions (or am I missing something?)

**Comment by aheritier** [comment]
@batmat @daniel-beck I'm lost :-)
I re-re-read the README. I think I perhaps didn't logged into artifactory. It is now done (or at least I'm sure it's done)

About authorisations are we talking about 

> provide a reference that shows you have commit permissions

???

In that case: 

https://github.com/jenkinsci/maven-interceptors/commit/e40ce347226175e73ee3aa32692138fb1196880d
https://github.com/jenkinsci/maven-plugin/commit/3038b552821dc7af34d200b3a8f5e77e5166832c

Is it enough ?

**Comment by daniel-beck** [comment]
Yeah, I suck. Sorry about that.

**Pull request merged**
