### PR TITLE
Request to rename plugin from iTMS JUnit Report Publisher to iTMS for JIRA

### PR DESCRIPTION
**Pull request by iTMSJenkins**
# Description

# Submitter checklist for changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo. If needed, it can be done using an [IRC bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management). Make sure to check that the `$pluginId Developers` team has `Write` permissions or above while granting the access.

### CODE REVIEW

**Comment by slide** [comment]
Have you already done a release of this plugin? If so, then the new name will cause the plugins to be different from each other and could cause issues if both are installed.

**Comment by oleg-nenashev** [comment]
Note that changing artifactId might be disrupting to the current plugin users., because artifactId  is directly converted into a pluginId used by the update manager and other components. Basically changing `artifactId` means that there is a new plugin created, there is no tooling for changing pluginIds at the moment

**Comment by slide** [comment]
This still doesn't solve the problem if someone already had you plugin installed. Both plugins will be installed at the same time, which could cause stability issues for users

**Comment by slide** [comment]
Do you think its imperative that the repo be renamed as well? (You have a different repo name in the updated file).

**Comment by slide** [comment]
Also, we would like to clean-up the old permissions file at the same time, so please add a removal of the current file to this PR.

**Comment by oleg-nenashev** [comment]
Yes, our practice is to rename the GitHub repo as well (`pluginId-plugin`),. It is a safe change

**Comment by slide** [comment]
I don't have access to rename repos on GitHub, can you file an INFRA ticket on issues.jenkins.io and select the GitHub component? Feel free to CC me on the ticket.

**Pull request merged**
