### PR TITLE
Add new plugin github-pr-coverage-status

### PR DESCRIPTION
**Pull request by terma**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Plugin POM: https://github.com/jenkinsci/github-pr-coverage-status-plugin/blob/master/pom.xml

User exists in Artifactory.

**Comment by terma** [comment]
Hi @daniel-beck I'm trying to release my plugin to Jenkins repo but got:
```
 Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project github-pr-coverage-status: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:github-pr-coverage-status:hpi:1.0.8 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/github-pr-coverage-status/1.0.8/github-pr-coverage-status-1.0.8.hpi, ReasonPhrase: Forbidden. -> [Help 1]
```
My username and password are same as for Jenkins wiki and issues account.

**Comment by daniel-beck** [comment]
@terma You forgot the file extension, needs to be `.yml`. I didn't notice when reviewing the PR.

I fixed it, give it another ~5 minutes to apply.

**Comment by terma** [comment]
Ops. Thanks a lot.

**Pull request merged**
