### PR TITLE
Remove old maintainers from gitlab-plugin deploy permissions

### PR DESCRIPTION
**Pull request by omehegan**
# Description
Remove old maintainers from deploy permissions for https://github.com/jenkinsci/gitlab-plugin

In addition, please remove the following from the GitHub Developers group for the plugin, as they are no longer active maintainers:
@slide 
@batmat 
@bassrock
@colourmeamused 
@omorillo
@coder-hugo
@xaniasd
@trance1st

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### CODE REVIEW

**Comment by daniel-beck** [comment]
As discussed with @omehegan I'll leave this for a day or two to give affected people a chance to response.

**Comment by slide** [comment]
:+1: from me

**Comment by coder-hugo** [comment]
:+1: from me

**Comment by daniel-beck** [comment]
Removed the specified users from the team. Left are: @argelbargel, @mreichel, @christ66, @omehegan, and @dblessing

**Pull request merged**
