### PR TITLE
Adopt badge-plugin

### PR DESCRIPTION
**Pull request by strangelookingnerd**
Adding @strangelookingnerd to developer list since the plugin is currently up for adoption.
Ping current maintainers @bakito @mPokornyETM

Plan to release pull request:

* https://github.com/jenkinsci/badge-plugin/pull/130

Posted [request to Jenkins developers list](https://groups.google.com/g/jenkinsci-dev/c/4xGJqploFgs/m/QK8JiNQBBgAJ)

# Link to GitHub repository

https://github.com/jenkinsci/badge-plugin
# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@strangelookingnerd`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Review by bakito — APPROVED** [review]
@strangelookingnerd thank you for your Initiative

**Review by MarkEWaite — APPROVED** [review]
Thanks very, very much @strangelookingnerd !

**Comment by MarkEWaite** [comment]
@strangelookingnerd thanks very much for your contributions to Jenkins.  Are you interested in being highlighted in the [Jenkins contributor spotlight](https://contributors.jenkins.io/)?  We have a survey that we use to gather information from contributors and then we post it to that site to highlight the varied backgrounds and experiences of Jenkins contributors.

**Comment by strangelookingnerd** [comment]
> @strangelookingnerd thanks very much for your contributions to Jenkins. Are you interested in being highlighted in the [Jenkins contributor spotlight](https://contributors.jenkins.io/)? We have a survey that we use to gather information from contributors and then we post it to that site to highlight the varied backgrounds and experiences of Jenkins contributors.

I‘d love to!

**Comment by MarkEWaite** [comment]
> > @strangelookingnerd thanks very much for your contributions to Jenkins. Are you interested in being highlighted in the [Jenkins contributor spotlight](https://contributors.jenkins.io/)? We have a survey that we use to gather information from contributors and then we post it to that site to highlight the varied backgrounds and experiences of Jenkins contributors.
> 
> I‘d love to!

That's great!  Could you send an email message to me at mark.earl.waite@gmail.com and I'll send you the link to the survey form and more information.

**Comment by mPokornyETM** [comment]
> > > @strangelookingnerd thanks very much for your contributions to Jenkins. Are you interested in being highlighted in the [Jenkins contributor spotlight](https://contributors.jenkins.io/)? We have a survey that we use to gather information from contributors and then we post it to that site to highlight the varied backgrounds and experiences of Jenkins contributors.
> > 
> > 
> > I‘d love to!
> 
> That's great! Could you send an email message to me at [mark.earl.waite@gmail.com](mailto:mark.earl.waite@gmail.com) and I'll send you the link to the survey form and more information.

@strangelookingnerd congratulations

**Comment by MarkEWaite** [comment]
> > > > @strangelookingnerd thanks very much for your contributions to Jenkins. Are you interested in being highlighted in the [Jenkins contributor spotlight](https://contributors.jenkins.io/)? We have a survey that we use to gather information from contributors and then we post it to that site to highlight the varied backgrounds and experiences of Jenkins contributors.
> > > 
> > > 
> > > I‘d love to!
> > 
> > 
> > That's great! Could you send an email message to me at [mark.earl.waite@gmail.com](mailto:mark.earl.waite@gmail.com) and I'll send you the link to the survey form and more information.
> 
> @strangelookingnerd congratulations

@mPokornyETM you are another that we would like to highlight on the contributor spotlight.  Same pattern.  If you'll send me an email message to mark.earl.waite@gmail.com I will send the survey link and more information.

**Pull request merged**
