### PR TITLE
Requesting permission to maintain semantic versioning plugin

### PR DESCRIPTION
**Pull request by christ66**
# Description

I would like to request access to be able to maintain the semantic versioning plugin: http://wiki.jenkins-ci.org/display/JENKINS/semantic-versioning-plugin.

Git location: https://github.com/jenkinsci/semantic-versioning-plugin

Permission was granted in the mailing list: https://groups.google.com/forum/#!topic/jenkinsci-dev/HfSDoNsLOjw.

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to @ciroque mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions) (see https://groups.google.com/forum/#!topic/jenkinsci-dev/HfSDoNsLOjw)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@christ66 Could you confirm the user [schristou88](https://github.com/jenkins-infra/repository-permissions-updater/search?utf8=%E2%9C%93&q=schristou88) is obsolete and can be replaced with [schristou](https://github.com/jenkins-infra/repository-permissions-updater/search?utf8=%E2%9C%93&q=schristou&type=Code)?

**Comment by christ66** [comment]
@daniel-beck user schristou88 is obsolete and not used anymore. I confirmed by checking my `settings.xml` file and I only release plugins using `schristou`.

**Comment by christ66** [comment]
@daniel-beck I will fix in a new PR

**Comment by christ66** [comment]
@daniel-beck https://github.com/jenkins-infra/repository-permissions-updater/pull/188

**Pull request merged**
