### PR TITLE
Set permissions for code-coverage-api plugin

### PR DESCRIPTION
**Pull request by tempora-mutantur**
# Description
Repo: https://github.com/jenkinsci/code-coverage-api-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)
@cizezsy 
- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by uhafner** [comment]
@asavanchuk @cizezsy 

Are you still actively maintaining the https://github.com/jenkinsci/code-coverage-api-plugin? We are currently improving the plugin in our GSoC project (see https://github.com/jenkinsci/code-coverage-api-plugin/pulls). If you don't have the time for reviewing and integrating changes please let us know. Then I would try to step in as additional maintainer so that we can get the GSoC changes (and some additional ones) published.

**Comment by oleg-nenashev** [comment]
Also CC @jeffpearce

**Comment by tempora-mutantur** [comment]
@uhafner 
Hi. Sorry for late response. I don't have enough time to maintain it for now and would appreciate if somebody could take it over.

**Comment by timja** [comment]
@tempora-mutantur could you take a look at https://github.com/jenkins-infra/repository-permissions-updater/pull/1627 please

**Pull request merged**
