### PR TITLE
add permission for thinbackup and SCTMExecutor

### PR DESCRIPTION
**Pull request by tofuatjava**
as I am the maintainer of thinBackup I want to publish some commits. I'm not able to execute these script myselve because of an NPE. However, it would be cool if I could puplish again...
Thanks
Thomas

### CODE REVIEW

**Comment by daniel-beck** [comment]
> I'm not able to execute these script myselve because of an NPE. 

@tofuatjava No worries, you're not supposed to. It requires Artifactory admin permissions.

**Comment by daniel-beck** [comment]
@tofuatjava I'm not sure the syntax of these files is correct. In any case, it's inconsistent with all others – could you please use the format shown in the README, with the user name on its own line, after a dash?

**Comment by tofuatjava** [comment]
@daniel-beck - changed the format as requested.

**Comment by daniel-beck** [comment]
@tofuatjava FYI I added a few commits changing some minor details.

**Pull request merged**
