### PR TITLE
Enable CD for `groovy`

### PR DESCRIPTION
**Pull request by jglick**
# Description

https://github.com/jenkinsci/groovy-plugin/pull/32#issuecomment-1172885724 @olivergondza @vjuranek @daniel-beck 

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by vjuranek** [comment]
I'm not maintaining Groovy plugin for couple of years. I can do the release if needed (and if I noticed there's some need for it), but it would be much better to find active maintainer and fix the name in plugin `pom.xml` and also here.

**Comment by vjuranek** [comment]
@daniel-beck yes, already done in jenkinsci/groovy-plugin#39 (thanks @jglick !). I need to do the same cleanup in couple of other plugins.

**Comment by halkeye** [comment]
That's purely cosmetic. If you want to remove yourself from the listing you want to change the file in this pr

**Comment by daniel-beck** [comment]
@vjuranek Could you confirm you're handing over maintainership to @jglick as proposed here?

**Comment by vjuranek** [comment]
> @vjuranek Could you confirm you're handing over maintainership to @jglick as proposed here?

Yes, I agree. Applies also to other plugins where I'm still listed as maintainer for historical reason and there is someone who is willing to take care about the plugin. Thanks!

**Review by vjuranek — APPROVED** [review]

**Pull request merged**
