### PR TITLE
Add andresrc to jquery

### PR DESCRIPTION
**Pull request by andresrc**
# Description

Add permission for `andresrc` to release [jquery plugin](https://github.com/jenkinsci/jquery-plugin). Currently only @kohsuke has permissions.

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Probably best if you just email the dev list requesting to take over this plugin. It can probably be considered to not have a maintainer currently.

**Comment by daniel-beck** [comment]
@andresrc Are you still interested in this?

**Comment by daniel-beck** [comment]
Assuming not.

**Comment by andresrc** [comment]
sorry, @daniel-beck I missed the ping. My bad. Yes, I was interested, will resubmit when needed.

**Pull request closed without merging**
