### PR TITLE
Update and rename plugin-blackduck-security-scan.yml to plugin-black-duck-security-scan.yml

### PR DESCRIPTION
**Pull request by zaman-akib**
# Link to GitHub repository

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@username1`
- `@username2`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Review by jahid1209 — APPROVED** [review]

**Comment by jahid1209** [comment]
When we submitted the hosting request to the Jenkins infrastructure, the artifact ID was originally `blackduck-security-scan`. However, after some discussion, we decided to change it to `black-duck-security-scan` to better align with our organizational needs. Now, when we attempt to release the plugin using the manual approach, we encounter the following error:
```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.2:deploy (default-deploy) on project black-duck-security-scan: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:black-duck-security-scan:pom:2.0.0 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): status code: 403, reason phrase:  (403) -> [Help 1]

```

Could you please take a quick look at this? We need to release this plugin as soon as possible. Tagging @timja @NotMyFault @alecharp for quick response.

Thanks in advance

**Comment by NotMyFault** [comment]
You may not change it.

**Comment by jahid1209** [comment]
@NotMyFault Thanks for your quick response. Could you please guide me what should I do next to resolve `403`?

**Comment by zaman-akib** [comment]
> Restore the original artifactId. It's not visible to the end user and can safely remain.

@NotMyFault we have to keep the **artifactId** as it is now because of the company name. It was one of the requirements. So if we want to keep this artifactId, will there be any other impact?

**Comment by zaman-akib** [comment]
@NotMyFault @timja @alecharp A quick response will really be helpful since today is our release day for this plugin. As per your response we will plan accordingly. Thanks in advance.

**Comment by zaman-akib** [comment]
> Restore the original artifactId. It's not visible to the end user and can safely remain.

For now, we are going with this. Thank you for your support.

**Comment by timja** [comment]
Hi for an initial release its not a problem to rename it and if no one has installed it we can delist it

**Pull request closed without merging**
