### PR TITLE
Update plugin-configuration-as-code.yml

### PR DESCRIPTION
**Pull request by ndeloof**
updated groupId for configuration-as-code

# Description

https://github.com/jenkinsci/configuration-as-code-plugin updated groupID see 
https://github.com/jenkinsci/configuration-as-code-plugin/commit/d7fe9956a5a6e571aca1f7bdee80401321de9048

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@ndeloof is listed as a developer in https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/pom.xml . I doubt it needs extra authorization @daniel-beck . But CC @ewelinawilkosz just in case

**Comment by ewelinawilkosz** [comment]
If I’m the one who can authorize then consider it done! If I misunderstood then sorry :)

**Comment by ndeloof** [comment]
by the way, @ewelinawilkosz I wonder the upload permission is set for user "praqma", and not individual contributors at Praqma.

**Comment by daniel-beck** [comment]
Just wasn't sure how the release model in CasC was supposed to work, with @ewelinawilkosz's approval this is fine.

**Pull request merged**
