### PR TITLE
Added cd enabled true

### PR DESCRIPTION
**Pull request by IBA-mainframe-dev**
# Link to GitHub repository

Zowe zDevOps plugin
https://github.com/jenkinsci/zdevops-plugin

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/zdevops-plugin/pull/35

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

### CODE REVIEW

**Comment by timja** [comment]
Please review the document more closely:
https://www.jenkins.io/doc/developer/publishing/releasing-cd/

1. Version format isn't right
2. You haven't deleted either the release drafter configuration file or the workflow

**Comment by IBA-mainframe-dev** [comment]
@timja , I removed the release drafter file and updated the PR.

However, when the automated build started on the Jenkins Infa side, the pipline fails with an error (https://ci.jenkins.io/job/Plugins/job/zdevops-plugin/job/release%252Fv1.1.0/1/console):

16:09:35  [ERROR] Failed to execute goal on project zdevops: Could not resolve dependencies for project io.jenkins.plugins:zdevops:hpi:1.1.0-38.vdfc0cff2a_304
16:09:35  [ERROR] dependency: org.zowe.sdk:zowe-kotlin-sdk:jar:0.5.0 (compile)
16:09:35  [ERROR] 	Could not find artifact org.zowe.sdk:zowe-kotlin-sdk:jar:0.5.0 in azure-aks-internal (http://artifact-caching-proxy.artifact-caching-proxy.svc.cluster.local:8080/)
16:09:35  [ERROR] -> [Help 1]
16:09:35  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project zdevops: Could not resolve dependencies for project io.jenkins.plugins:zdevops:hpi:1.1.0-38.vdfc0cff2a_304
16:09:35  dependency: org.zowe.sdk:zowe-kotlin-sdk:jar:0.5.0 (compile)
16:09:35  	Could not find artifact org.zowe.sdk:zowe-kotlin-sdk:jar:0.5.0 in azure-aks-internal (http://artifact-caching-proxy.artifact-caching-proxy.svc.cluster.local:8080/)

However, the path to the artifact is written in pom.xml (<url>https://zowe.jfrog.io/artifactory/libs-release</url>) and locally everything runs without issues.
Could you please tell me how to fix such issue?

Thanks in advance!

Repo path to the missing artifactory from pom.xml:
```
    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>

        <repository>
            <id>zowe.jfrog.io</id>
            <url>https://zowe.jfrog.io/artifactory/libs-release</url>
        </repository>
    </repositories>
```

**Comment by timja** [comment]
The two normal version formats are:

```
<version>${changelist}</version>
```

```
<version>${revision}.${changelist}</version>
```

You have neither of those in https://github.com/jenkinsci/zdevops-plugin/blob/release/v1.1.0/pom.xml
Also your changelist variable doesn't match the expected one

**Comment by timja** [comment]
Please file a https://github.com/jenkins-infra/helpdesk request for https://github.com/jenkins-infra/repository-permissions-updater/pull/4150#issuecomment-2435481135

Its to do with the Artifact Caching proxy.
Basically its expected that all artifacts are in Maven Central, https://repo.jenkins-ci.org/ or if really necessary then another mirror can be added to the artifact proxy by the jenkins infra team.

**Comment by IBA-mainframe-dev** [comment]
@timja , I changed the format of the version like you requested.
And I created a ticket about the Artifact Caching proxy issue: https://github.com/jenkins-infra/helpdesk/issues/4367#issue-2612144943

**Pull request merged**
