### PR TITLE
Add Bernardo Buelga as a cloudformation-plugin dev

### PR DESCRIPTION
**Pull request by MarkEWaite**
# Description

Bernardo Buelga wants to adopt the [jenkins-cloudformation-plugin](https://github.com/jenkinsci/jenkins-cloudformation-plugin).  He's an active user of AWS CloudFormation and would like to merge several pull requests and perform additional maintenance on the plugin.

Last commit to the repository was over 2 years ago.  @edovale and @nathanagood are listed as current developers.  Mail request to adopt the plugin has been sent to the [Jenkins dev list](https://groups.google.com/d/msg/jenkinsci-dev/RMXrntZfJWs/VPd1vSiXEwAJ), edovale, and nathanagood requesting that Bernardo be allowed to develop and release new versions of the plugin.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable (@edovale approval received by tweet to @MarkEWaite)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

Don't merge until I've confirmed that @tolivia has a Jenkins community (LDAP) account and that he has logged into Artifactory at least once.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
> and nathanagood requesting that Bernardo be allowed to develop and release new versions of the plugin.

I do not see a public track of that.  If there is an explicit approval in public, we will be able to proceed

**Comment by MarkEWaite** [comment]
I've asked @edovale to post a reply on the public thread so that we have a public record of his permission.

Unfortunately, I don't see an easy way to contact @nathanagood .  I've posted the mention here and have sent him a request on twitter, but his twitter account has been inactive since 2013.

**Comment by MarkEWaite** [comment]
@tolivia could you confirm that you can login to the Jenkins Community (Jira, for example) with your account name "tolivia".  If not, can you tell me your Jenkins Community account name so that I can update the pull request with the correct account name?

**Comment by nathanagood** [comment]
I thought that I had officially given this up for adoption long ago. As
such, I've been ignoring emails concerning it. My apologies. I took a role
that prohibited me from being involved with it. Now, ironically, I no
longer have that role.

Whatever permissions you need from me for someone else to pick this up, you
have it.

**Comment by oleg-nenashev** [comment]
Yey, thanks everybody for the confirmation!

**Comment by tolivia** [comment]
@MarkEWaite , can you let me know the link to try login into that Jenkins community? 
And thanks everyone for letting me adopting this plugin, I will take good care of it!

**Comment by MarkEWaite** [comment]
Thanks @nathanagood!  Yes, we saw that you had marked the plugin for adoption.  We want to be doubly safe by asking for confirmation before making the ownership transfer.

**Comment by MarkEWaite** [comment]
@tolivia the [Jenkins issues](https://issues.jenkins-ci.org/secure/Dashboard.jspa) site is one place that uses community credentials.

**Comment by daniel-beck** [comment]
This was merged without a successful PR build so now all PR builds are failing.

**Comment by oleg-nenashev** [comment]
Reverted the change. User must login.
Sorry for the mistake

**Pull request merged**
