### PR TITLE
Added "PaJaSoft" account to Foreman node sharing plugin

### PR DESCRIPTION
**Pull request by pjanouse**

### CODE REVIEW

**Comment by pjanouse** [comment]
@scoheb 
Can you approve this requests please?

**Comment by scoheb** [comment]
Only the infra team can approve...

**Comment by daniel-beck** [comment]
@scoheb Well, we want confirmation from existing maintainers that permissions should be granted.

**Comment by daniel-beck** [comment]
@pjanouse I'm not sure whether this needs to match letter case. To be safe, you could change this to `pajasoft`.

**Comment by daniel-beck** [comment]
Given #130 I'll just assume this is approved. I'll merge later today.

**Pull request merged**
