### PR TITLE
Rename component-publish-over.yml to plugin-publish-over.yml

### PR DESCRIPTION
**Pull request by daniel-beck**
publish-over is a plugin.

@slide

### CODE REVIEW

**Comment by slide** [comment]
This has gone back and forth a few times I believe...so what's another time...

**Comment by daniel-beck** [comment]
@slide Could you clarify, This is simply adapting to https://github.com/jenkinsci/publish-over-plugin/commit/4df65157e33651733d51b9ee060971098c2af346, before which this was always a jar/library.

**Comment by slide** [comment]
@daniel-beck I believe this switch has been made to component in the past and back again to plugin, I was being tongue in cheek, the change is fine.

**Comment by slide** [comment]
Close and reopen to get a completed build.

**Comment by slide** [comment]
hmmmm, PR build is not reporting status?

**Comment by oleg-nenashev** [comment]
CI is still running according to the status, and I cannot merge it.
CC @daniel-beck @olblak could you apply your superpowers here?

**Comment by daniel-beck** [comment]
It's an origin PR that doesn't get built redundantly as a pr-merge build. Whoever protected the master branch did not expect this would happen.

**Pull request merged**
