### PR TITLE
Add upload permissions for blackduck-coverity-on-polaris-plugin

### PR DESCRIPTION
**Pull request by zaman-akib**
# Link to GitHub repository

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@blackduck-saraf`
- `@manjeet-s`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation.
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
Is @saraf their GitHub handle?

**Comment by zaman-akib** [comment]
> Is @saraf their GitHub handle?

@NotMyFault no. **saraf** is the account that is created in https://accounts.jenkins.io/

**Comment by zaman-akib** [comment]
GitHub handles to add permission: 
1. [blackduck-saraf](https://github.com/blackduck-saraf)
2. [manjeet-s](https://github.com/manjeet-s)

**Comment by alecharp** [comment]
@zaman-akib The pull request template that is setup in this repository is here to format and help you with those requests. Removing it is not a good thing to do. 

Please edit the pull request description to use the template https://github.com/jenkins-infra/repository-permissions-updater/blob/master/.github/PULL_REQUEST_TEMPLATE.md and fill in the details.

**Comment by zaman-akib** [comment]
> @zaman-akib The pull request template that is setup in this repository is here to format and help you with those requests. Removing it is not a good thing to do.
> 
> Please edit the pull request description to use the template https://github.com/jenkins-infra/repository-permissions-updater/blob/master/.github/PULL_REQUEST_TEMPLATE.md and fill in the details.

@alecharp updated the description

**Comment by alecharp** [comment]
We need either @blackduck-saraf or @manjeet-s to approve this pull request.

**Review by blackduck-saraf — APPROVED** [review]
LGTM

**Comment by timja** [comment]
> We need either @blackduck-saraf or @manjeet-s to approve this pull request.

The author was already a maintainer: https://github.com/orgs/jenkinsci/teams/blackduck-coverity-on-polaris-plugin-developers/members

@blackduck-saraf already had GitHub access

@manjeet-s please go to https://github.com/jenkinsci to accept the invitation

**Pull request merged**
