### PR TITLE
Request for developer status on Job DSL and Docker plugins

### PR DESCRIPTION
**Pull request by thecooldrop**
# Description

Hello everyone, I am looking to adopt the plugins listed in the title and whose files have been changed in this PR.

# Submitter checklist for adding or changing permissions

The links to plugins which I would like to adopt are:

https://github.com/jenkinsci/docker-plugin
https://github.com/jenkinsci/job-dsl-plugin

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
Could you provide a list of pull requests you created to the named plugins you would like to deliver?

**Comment by thecooldrop** [comment]
Hello @NotMyFault, currently I do not have concrete PRs which I would like to deliver. Majorly I would like to start working on documentation, and on improvements regarding the integration of information which is available in the plugins into the automatically generated documentation page of Job DSL.

For Docker plugin I would like to start working on documentation regarding how this plugin is different from other plugins and providing usage examples. 

In general I am a beginner in the ecosystem of plugins, but I am active user of both of these plugins

**Comment by basil** [comment]
@thecooldrop Thank you for your quality contributions to other Jenkins plugins. We appreciate it when a user of a plugin steps up to maintain it, because such maintainers have a good idea of the testing that is required in order to avoid regressions.

For plugins with a high user count, we typically want to see prior contributions to that plugin and/or or prior experience maintaining other Jenkins plugins. I would recommend you file some PRs to the abovementioned plugins and/or start by maintaining some less popular plugins to get some experience with the plugin development and release process in order to ensure a smooth transition as you take on maintainership.

**Comment by thecooldrop** [comment]
Hello @basil, okay sounds good to me. Thanks for the fast response.

From my point of view this PR can be closed and I will create a new one at later more appropriate time

**Pull request closed without merging**
