### PR TITLE
Add mihai_virag as developer

### PR DESCRIPTION
**Pull request by SilkPerformer**
# Description

https://github.com/jenkinsci/silk-performer-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by slide** [comment]
None of the check boxes have been checked, please follow the PR template instructions.

**Comment by SilkPerformer** [comment]
I am new to this and I don't know what should I do next. Can you help me? 
Thanks.

**Comment by slide** [comment]
The @ mention is checked, but you didn't @ mention anyone. If you have specific questions about the items in the check list, please send an email to the developers group with the specific questions, it will be easier to answer full there AND it will be a good resource for other people with similar questions to refer to.

**Comment by oleg-nenashev** [comment]
I assume it could be merged now. Any blockers @slide ?

**Pull request merged**
