### PR TITLE
Add config for gerrit plugin

### PR DESCRIPTION
**Pull request by ssbarnea**
# Description

Gerrit Plugin is hosted at https://github.com/jenkinsci/gerrit-plugin and authored by @lucamilanesio

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by ssbarnea** [comment]
@lucamilanesio Can you please confirm that you logged-in at least on once to https://repo.jenkins-ci.org/ ?

**Comment by daniel-beck** [comment]
Is this related to the old Gerrit Plugin that is blacklisted, or is this an actual name collision?

https://wiki.jenkins.io/display/JENKINS/Gerrit+Plugin
https://github.com/jenkins-infra/update-center2/blob/35bebcc3abd10a2caa715a586efcb75942e501ef/src/main/resources/artifact-ignores.properties#L39

**Comment by ssbarnea** [comment]
No, this plugin is new and implements Gerrit SCM functionality via branch-api, enabling Gerrit users to use multibranch pipelines.

Does this means that we need to rename it or is ok to replace the old one?

**Comment by daniel-beck** [comment]
Honestly, I don't know. We haven't had this situation before. I think this should use a different artifactId, as there are still hundreds of instances with the plugin installed, and those users would have a very weird "upgrade" experience:
: http://stats.jenkins.io/plugin-installation-trend/gerrit.stats.json

Not to mention that we'd need to blacklist specific plugin versions that must not be used for this plugin.

Could you create a thread on the dev list?

**Comment by lucamilanesio** [comment]
@daniel-beck I am a bit surprised that there is a name collision because:

- Git repo is different
- Jira component in the issues is different

How did we ended up in this situation?

**Comment by lucamilanesio** [comment]
Look at the repositories names:
https://github.com/jenkinsci?utf8=%E2%9C%93&q=gerrit&type=&language=

The deprecated plugin is called 'hudson-gerrit-plugin' and thus the corresponding entry on artifactory should have been 'hudson-gerrit-plugin' correct? It looks to me a problem in the Jenkins CI's artifactory instsance.

The new repo is called 'gerrit-plugin' and the plugin 'gerrit'. I do not see any conflicts with the previous name.

**Comment by daniel-beck** [comment]
@lucamilanesio 

> The deprecated plugin is called 'hudson-gerrit-plugin' and thus the corresponding entry on artifactory should have been 'hudson-gerrit-plugin' correct? It looks to me a problem in the Jenkins CI's artifactory instsance.

The GitHub repo does not match the usual naming convention. I don't know why, development ended well after I became involved in the project. The artifactId is `gerrit` and that is all that matters for distribution: https://github.com/jenkinsci/Hudson-Gerrit-Plugin/blob/24f1c8f14803989b81a5189026bb26433be65ec7/pom.xml#L10

**Comment by lucamilanesio** [comment]
Can we call the new artifact gerrit-review?

**Comment by daniel-beck** [comment]
Seems reasonable.

**Comment by lucamilanesio** [comment]
Should I just change the plugin build pom.xml ... or do the renaming everywhere? What do you think?

**Comment by lucamilanesio** [comment]
... and thanks a lot @ssbarnea for raising this :-) I was just too busy or too lazy for doing it myself :-(

**Comment by ssbarnea** [comment]
I support the idea of consistent naming everywhere and now is the best time to do it (before it becomes more popular).

I will update this PR later this evening, I am not near laptop now.

**Comment by lucamilanesio** [comment]
👍 all good from my side for the whole renaming. @daniel-beck can you rename the Git repo as well to jenkinsci/gerrit-code-review-plugin?

**Comment by daniel-beck** [comment]
@lucamilanesio Renamed both GitHub repo and component in Jira.

**Comment by lucamilanesio** [comment]
Thanks @daniel-beck and @ssbarnea for your support

**Pull request merged**
