### PR TITLE
Create plugin-eagle-tester.yml

### PR DESCRIPTION
**Pull request by mobile-enerlytics**
# Description
https://github.com/jenkinsci/eagle-tester-plugin
https://issues.jenkins-ci.org/browse/HOSTING-471

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please complete the checklist.

**Comment by mobile-enerlytics** [comment]
I've added the plugin's github link. Sorry for the delay.

**Comment by daniel-beck** [comment]
The specified user still hasn't logged into Artifactory, which is the last checklist item, or perhaps the one before that.

The checklist exists for a reason.

**Comment by mobile-enerlytics** [comment]
Sorry, I wasn't sure the last section applied to me (when adding new uploader); I've completed that check list now. Hope everything is in order. Sorry for the inconvenience.

**Comment by mobile-enerlytics** [comment]
Hi @daniel-beck , 

Is there a way to verify that the upload permissions have taken effect? I am unable to upload the plugin. I'm getting 

    $ mvn release:prepare release:package
    ....
        Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/eagle-tester/1.0/eagle-tester-1.0.hpi
    Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/eagle-tester/1.0/eagle-tester-1.0.pom
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 01:00 min
    [INFO] Finished at: 2018-01-11T17:54:29-08:00
    [INFO] Final Memory: 69M/564M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project eagle-tester: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:eagle-tester:hpi:1.0 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/eagle-tester/1.0/eagle-tester-1.0.hpi, ReasonPhrase: . -> [Help 1]

I've already added my artifactory username and password to ~/.m2/settings.xml. I'm using OSX
`
  <servers>
    <server>
      <id>maven.jenkins-ci.org</id>
      <username>mobileenerlytics</username>
      <password>...</password>
    </server>
   </servers>
`

Thank you for your help!

**Comment by daniel-beck** [comment]
You're allowed to upload `com/mobileenerlytics/eagle/tester/eagle-tester`. You fail to upload `org/jenkins-ci/plugins/eagle-tester`. https://github.com/jenkinsci/eagle-tester-plugin/commit/1c74e7c730c652af7c13923e005a4cade1980e8c#diff-600376dffeb79835ede4a0b285078036 needs a corresponding change in permissions.

**Comment by mobile-enerlytics** [comment]
Ouch. Works now. Many thanks for quick responses!

**Pull request merged**
