### PR TITLE
Adding startup-trigger-plugin

### PR DESCRIPTION
**Pull request by ejpenney**
https://github.com/jenkinsci/startup-trigger-plugin-plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'm aware about "tartup-trigger-plugin-plugin" repo, but it's a historical issue.
@rtyler may want to rename the plugin

👍 anyway

**Comment by daniel-beck** [comment]
This already exists here:
https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-startup-trigger-plugin.yml

**Comment by ejpenney** [comment]
Shows how blind I am... Pull request updated, thanks!

**Comment by ejpenney** [comment]
Is there anything else needed from me to get this PR merged?

**Comment by oleg-nenashev** [comment]
merged

**Comment by daniel-beck** [comment]
@ejpenney I'd like to rename the repository to `startup-trigger-plugin` -- GitHub should forward everything transparently, but still in rare cases you may need the new URL. OK with you?

**Comment by ejpenney** [comment]
@daniel-beck Sounds great, go right ahead.  Let me know if you need anything from me.

**Comment by daniel-beck** [comment]
@ejpenney FYI I've renamed the repo now.

**Pull request merged**
