### PR TITLE
Update plugin-bearychat.yml

### PR DESCRIPTION
**Pull request by shonenada**
# Description

Plugin repo in BearyInnovative organization:
https://github.com/bearyinnovative/jenkins-bearychat-plugin

Plugin repo in JenkinsCI organization:
https://github.com/jenkinsci/bearychat-plugin

@yuanbobo please approve this permission .

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by yuanbohan** [comment]
I agree it. shonenada is our team member. cc @orrc

**Comment by daniel-beck** [comment]
@yuanbohan Does @shonenada need write access to the Git repository as well?

**Comment by yuanbohan** [comment]
@daniel-beck yes, he will be the maintainer.

**Comment by shonenada** [comment]
Thank you both, @yuanbohan @daniel-beck.

**Comment by daniel-beck** [comment]
Granted @shonenada commit access.

**Comment by shonenada** [comment]
Thank you @daniel-beck .

**Pull request merged**
