### PR TITLE
Request permission for gitea plugin

### PR DESCRIPTION
**Pull request by mecseid**
# Description
Add new maintainer (@mecseid) to gitea plugin.
Repository link: https://github.com/jenkinsci/gitea-plugin
@stephenc please look into the PR to approve my request.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by halkeye** [comment]
as someone with absolutely no authority whats so ever, i approve this request, mostly because it passed CI

**Comment by oleg-nenashev** [comment]
I pinged @stephenc to get the confirmation

**Comment by mecseid** [comment]
I would work in it but haven't seen any outcoming activities from there since February. Because of it, I thought it was an abandoned repo, so I applied as a maintainer.
Do you have time for the plugin?
I would gladly dedicate some time to it because it would ease my recent work as well. I just need more info about the upcoming development and permission to do my best.

**Comment by stephenc** [comment]
I don't have tons of time, but I occasionally check in on the plugin. My plan is to offer it up for adoption once it gets to the "this is a really good example of how to do an SCM plugin" state... just awaiting some auth api changes in the git plugin before we can get there

**Comment by mecseid** [comment]
Sorry for late response.

I really appreciate your work and thanks the new bugfix release.
To fit the requirements, I will check the JIRA and look the codebase to fix some issues or make improvements.

I think thise PR is closeable.

**Comment by stephenc** [comment]
Let’s close this now and consider re-opening when you have a track record of contributions

**Pull request closed without merging**
