### PR TITLE
Added Security Contacts

### PR DESCRIPTION
**Pull request by cyberark-bizdev**
Added product_security@cyberark.com as security contact

# Submitter checklist for adding or changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by halkeye** [comment]
Oh cool, I had forgotten that email: was valid for that (confirmed via https://github.com/jenkins-infra/repository-permissions-updater/blob/e7a5e64a6dc01e6628ef6609597b608771530772/src/main/java/io/jenkins/infra/repository_permissions_updater/Definition.java#L19-L22)

lgtm

**Comment by timja** [comment]
cc @Wadeck 

> If security contacts are changed (this includes add/remove), ping the security officer (currently @Wadeck) in this pull request. If an email contact is changed, wait for approval from the security officer.

**Comment by halkeye** [comment]
🤦 thanks tim

**Comment by Wadeck** [comment]
@cyberark-bizdev If you are able to provide a Jira account and not a email, that will really help us not having a specific treatment to apply to your plugin.

> Please note that we generally reject email contacts due to the additional overhead in reaching out via email. Unless you represent a large organization with dedicated security team that needs to be involved in the coordination of a release, but is not otherwise part of plugin maintenance, please refrain from requesting to be contacted via email.

Having a Jira account backed by that email is the recommended approach :)

(and due to the early merge + revert, you will have to create a new PR)

**Comment by Wadeck** [comment]
Revert proposal in https://github.com/jenkins-infra/repository-permissions-updater/pull/2398. Waiting until end of the week to be adjusted, otherwise the contact will be removed.

**Pull request merged**
