### PR TITLE
Enable CD permissions for plugin-accurev.yml

### PR DESCRIPTION
**Pull request by AldenPratt**
# Link to GitHub repository

https://github.com/jenkinsci/accurev-plugin

Incrementalified PR: https://github.com/jenkinsci/accurev-plugin/pull/62/files

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation.
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
The PR linked is incomplete and 5 years out of date. Please file a new PR according to the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to enable CD.

**Comment by AldenPratt** [comment]
Thanks for the info, much appreciated.  Here's a new PR: https://github.com/jenkinsci/accurev-plugin/pull/101.

**Comment by NotMyFault** [comment]
> Thanks for the info, much appreciated. Here's a new PR: [jenkinsci/accurev-plugin#101](https://github.com/jenkinsci/accurev-plugin/pull/101).

The PR linked is incomplete. The maven extension is still 5 years out of date, and the pom hasn't been incrementalified yet.
Additionally, I recommend against merging PRs with failing builds. As outlined in https://groups.google.com/g/jenkinsci-dev/c/iy5bhV8_4Ak/m/VzAuZBDVBAAJ, various modernization chores are due to make it work to cut a release.

**Comment by NotMyFault** [comment]
@AldenPratt If you're still interested in moving your PR forward, please provide a new PR for us to review to address the comments above.

**Pull request closed without merging**
