### PR TITLE
update users permissions for LoadNinja plugin

### PR DESCRIPTION
**Pull request by kordian-smartbear**
User that is set as a dev is no longer in the company, in addition we would like to pass our repo administration to SmartBear devops team.

# Link to GitHub repository

https://github.com/jenkinsci/loadninja-plugin

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- @yamini-sethu
- @runkalicious (Matt Runkle)
- @loadninja-bot

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request **(Not feasible as the developer is not working with us any more.)**

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by timja** [comment]
Given that no one has access to this repo AND that it was last updated 5 years ago, this means the plugin up for adoption.

I'll go ahead and grant the specified users permission on this plugin

**Comment by timja** [comment]
Please go to https://github.com/jenkinsci to accept the invitation

**Comment by yamini-sethu** [comment]
@timja We're new to the community and are working on our loadninja-plugin repository. We're trying to figure out how to create a team within the repo that allows us to add new contributors. Additionally, we'd like to maintain a separate list of members who have the permissions to make releases. Could you guide us on the best approach for setting this up?


https://github.com/jenkinsci/loadninja-plugin

image

**Comment by timja** [comment]
Hi you can either add them as collaborators directly, or you can send a request here using this issue form and we can add them to the team:

https://github.com/jenkins-infra/repository-permissions-updater/issues/new?assignees=&labels=github-permissions&projects=&template=5-github-permissions.yml

**Comment by yamini-sethu** [comment]
Thanks @timja, we will add the users as collaborators directly.

**Pull request merged**
