### PR TITLE
Add extended-security-settings plugin

### PR DESCRIPTION
**Pull request by jvz**
This is the new plugin name and settings for paranoia-plugin which was
recently moved and renamed.

https://github.com/jenkinsci/extended-security-settings-plugin

# Description

https://github.com/jenkinsci/extended-security-settings-plugin

Rename of paranoia-plugin. Adding @jeffret-b as another developer.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by daniel-beck** [comment]
What are your plans for paranoia plugin? Wouldn't it make sense to rename and change that metadata file, and blacklist the plugin?

**Comment by slide** [comment]
There is no longer a paranoia-plugin repo in jenkinsci org. I agree though, renaming the metadata file is the way to go instead of creating a new file.

**Comment by slide** [comment]
@daniel-beck does this look ok to you?

**Comment by batmat** [comment]
Can you also fine the PR on https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/artifact-ignores.properties then maybe @jvz ?

**Pull request merged**
