### PR TITLE
changing maintainer and devs for the iTest plugin

### PR DESCRIPTION
**Pull request by cwhitty**
This is the changing maintainer and devs for the iTest plugin. Here is the email thread...
https://groups.google.com/d/msg/jenkinsci-dev/2fD4xvS73eM/_SeZwxvLBgAJ

### CODE REVIEW

**Comment by batmat** [comment]
... There are a number of checkboxes to check or at least ack for a reason, to show you checked those...
image

**Comment by cwhitty** [comment]
thanks, the checklist has been filled out.

**Comment by daniel-beck** [comment]
The original request is an unreadable mess, but it looks like the topmost email is from @oleg-nenashev.

Not sure we really want to support permission changes for plugins hosted outside the `jenkinsci` project. They're only grandfathered in anyway, and I'm not really sure this request is legitimate.

@cwhitty Could you have `rmstratus` file an INFRA issue on issues.jenkins-ci.org about this transfer of ownership?

**Comment by daniel-beck** [comment]
Found the dev list thread: https://groups.google.com/d/msg/jenkinsci-dev/2fD4xvS73eM/_SeZwxvLBgAJ

**Comment by cwhitty** [comment]
@daniel-beck, sorry about the messy request - I have cleaned it up. 
Robert Martin, the original author of the plugin, is no longer with Stratus, and I've tried to reach him.

**Comment by cwhitty** [comment]
@daniel-beck, I'm trying to get this repo hosted on jenkins-ci. It's currently on a private repo: https://github.com/Spirent/Spirent-iTest-Jenkins-Plugin 
You can see the request here:
https://issues.jenkins-ci.org/browse/HOSTING-511

So, do you still need something from my side?

**Comment by daniel-beck** [comment]
@cwhitty Please ping me again when the hosting request has been processed, then I can do this.

**Comment by cwhitty** [comment]
hi @daniel-beck, it seems that the hosting has taken place: https://github.com/jenkinsci/itest-plugin

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/itest-plugin/blob/master/pom.xml#L11...L13 still needs to be adapted.

**Pull request merged**
