### PR TITLE
Added aliaandersen to plugin-contrast-continuous-application-security.yml

### PR DESCRIPTION
**Pull request by aliaandersen**
Added aliaandersen to plugin-contrast-continuous-application-security.yml

# Description

Grant @aliaandersen permission to deploy contrast-continuous-application-security

cc @gmoore 

https://github.com/jenkinsci/contrast-continuous-application-security-plugin

# Submitter checklist for changing permissions
### Always
 - [x] Add link to plugin/component Git repository in description above
- [x] Make sure to @mention an existing maintainer to confirm the permissions request, if applicable
- [x]  Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to @mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] All newly added users have logged in to Artifactory at least once

### CODE REVIEW

**Comment by gmoore** [comment]
@slide I approve. Thanks!

**Comment by gmoore** [comment]
Hi @slide sorry to bring back an old PR but wasn't sure of another way to contact the Jenkins team. alianadersen has the rights to deploy, but how do we get her added to the plugin repository here: https://github.com/orgs/jenkinsci/teams/contrast-continuous-application-security-plugin-developers/members 

Likewise, how do we remove people form that list?

**Comment by slide** [comment]
@gmoore I made you a maintainer of that team. It should allow you to add and remove people. Let me know if you still have issues.

**Comment by gmoore** [comment]
@slide Thanks, looks like we need to get her into the jenkinsci org first. 

Screen Shot 2020-09-30 at 10 29 47 AM

**Comment by slide** [comment]
Done!

**Comment by gmoore** [comment]
@slide Thanks so much for helping out. Cheers!

**Pull request merged**
