### PR TITLE
Add sergii_contrast to plugin-contrast-continuous-application-securit…

### PR DESCRIPTION
**Pull request by serge17**
# Description

Grant @serge17 permission to deploy contrast-continuous-application-security

cc @gmoore

https://github.com/jenkinsci/contrast-continuous-application-security-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by gmoore** [comment]
Hi! I'm one of the current maintainers for our plugin. We approve of serge17 becoming a maintainer. Let us know if you need anything else.

**Comment by oleg-nenashev** [comment]
should be fine

**Comment by gmoore** [comment]
Hey @oleg-nenashev Sorry if I missed this in the docs. How do we get @serge17 added to https://github.com/orgs/jenkinsci/teams/contrast-continuous-application-security-plugin-developers ?

**Comment by daniel-beck** [comment]
@gmoore By asking 😄 I added him as committer, he may need to accept the invitation to the jenkinsci org.

**Comment by gmoore** [comment]
Thanks @daniel-beck

**Pull request merged**
