### PR TITLE
Add rukkanen to protecode developers

### PR DESCRIPTION
**Pull request by rukkanen**
# Description

Could I please have rights to release:
https://github.com/jenkinsci/protecode-sc-plugin
@mattisii is the only active developer currently.
alatalo isn't in the project anymore.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by mattisii** [comment]
This is OK

**Comment by daniel-beck** [comment]
This user does not exist in Artifactory. Please read this repository's readme.

**Comment by daniel-beck** [comment]
It seems that @alatalo's last contribution to the plugin was in September 2016, so seems reasonable. Pinging them anyway to give them an opportunity to speak up and have their access restored.

**Comment by rukkanen** [comment]
Logged into Artifactory.

**Comment by rukkanen** [comment]
I'm sorry, it's confuding that I have two names, rukkanen and Lauri Pajunen. rukkanen is my github etc name and Lauri Pajunen is then my company policy dictated correct name

**Comment by alatalo** [comment]
@daniel-beck  Confirming; I have left the project and @mattisii is the admin.

**Comment by rukkanen** [comment]
thank you @daniel-beck and sorry @alatalo for not noticing to ping

**Pull request merged**
