### PR TITLE
Add upload permission for AutonomiQ plugin

### PR DESCRIPTION
**Pull request by jameeluddin**
# Description

- Plugin: https://github.com/jenkinsci/autonomiq-plugin
- Hosting request link: https://issues.jenkins.io/browse/HOSTING-1132

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by halkeye** [comment]
why do you keep closing and recreating the PR? Its the exact same PR, nothing is going to change.

**Comment by halkeye** [comment]
image

**Comment by halkeye** [comment]
also you need to do each step in the template, once done, check it off

**Comment by jameeluddin** [comment]
may i know what are all the steps that are missing from above template

**Comment by jameeluddin** [comment]
validation has been done

**Comment by halkeye** [comment]
puneetchelani has not logged into artifactory
According to https://reports.jenkins.io/artifactory-ldap-users-report.json
puneetchelani_sauce
has logged in

So I think you should check your yaml file and confirm the usernames match
the usernames you logged into artifactory with

**Comment by jameeluddin** [comment]
i have changed the username, please review the pull request @halkeye

**Comment by halkeye** [comment]
To be clear, your no longer able to upload releases, just puneetchelani_sauce. Is that intentional? Which makes this PR a little confusing since its filed by you and not them.

**Comment by jameeluddin** [comment]
@halkeye, puneelchelani_sauce will work on upload releases, yes it is intentional. Hope it clears everything.

**Pull request merged**
