### PR TITLE
Update Code Dx plugin permissions

### PR DESCRIPTION
**Pull request by baffles**
# Description

GitHub repository: https://github.com/jenkinsci/codedx-plugin

Updating Jenkins LDAP accounts for @tylercamp and myself; due to re-organization, we have lost access to our old accounts and the associated email addresses, so are switching to new accounts.

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by baffles** [comment]
I hadn't logged into jira. Have now logged in, so can re-verify.

(closing and re-opening PR as suggested by the error message from the verification check)

**Comment by NotMyFault** [comment]
@KenProle, @phillip-elliott, @dylemma do you approve this permission update?

**Comment by KenProle** [comment]
Yes, I approve.

**Comment by phillip-elliott** [comment]
I approve.

**Comment by dylemma** [comment]
Approved

**Review by NotMyFault — APPROVED** [review]
Thanks for approving. The build will pass if both users logged into [Jira](https://issues.jenkins.io/).
The Jira user list refreshes every 2 hours.

**Pull request merged**
