### PR TITLE
Create pom-build-configurator-parent

### PR DESCRIPTION
**Pull request by AMCBridgeDevTeam**
# Description

Adding permissions for the Build Configurator plugin (https://github.com/jenkinsci/build-configurator-plugin), as approved in HOSTING-276 (https://issues.jenkins-ci.org/browse/HOSTING-276).
# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by orrc** [comment]
There are several problems that I can see, despite the relevant items in the checklist having been checked:
* filename doesn't end with `.yml`
* `paths`don't match the `groupId` and `artifactId` in the POM
* format of the file is weird; every line begins with `+++`

Also, if you can confirm that both of those LDAP account names are correct and have logged in, that would be helpful.

**Comment by roman-bilyi** [comment]
@orrc We've fixed all issues. 
**AMCBridgeDevTeam** logged in correctly.
**roman-bilyi** user name seems to be unacceptable due to dash symbol so it's removed from request.

**Comment by AMCBridgeDevTeam** [comment]
@orrc We've fixed all issues.
AMCBridgeDevTeam logged in correctly.
roman-bilyi user name seems to be unacceptable due to dash symbol so it's removed from request.

**Comment by orrc** [comment]
Please fix the [format](https://github.com/jenkins-infra/repository-permissions-updater#managing-permissions) of the file. Check any of the examples in the `permissions` folder.

**Comment by AMCBridgeDevTeam** [comment]
@orrc We've fixed.

**Comment by AMCBridgeDevTeam** [comment]
@orrc We've fixed.

**Comment by daniel-beck** [comment]
As this is a multi-module Maven project, you need to also add individual permissions files to each module. Just the parent POM isn't enough.

**Comment by AMCBridgeDevTeam** [comment]
@daniel-beck, thanks, we added permission files for other modules.

**Comment by daniel-beck** [comment]
@AMCBridgeDevTeam My apologies for the delay.

`amcbridgedevteam` (all lowercase) is the user name in Artifactory, please adapt these files. This is case sensitive.

**Pull request merged**
