### PR TITLE
Adding myself to plugin-jx-resources.yml

### PR DESCRIPTION
**Pull request by jglick**
CC @jstrachan to let me deal with problems like https://github.com/jenkinsci/jx-resources-plugin/pull/24#issuecomment-463023469.

### CODE REVIEW

**Comment by slide** [comment]
@jstrachan Do you sign off on this? Thanks!

**Comment by slide** [comment]
@jglick I am not sure that @jstrachan checks notifications from github, so you may want to contact him directly to get him to look at this.

**Comment by jglick** [comment]
Alternately, perhaps @rawlingsj wishes to resurrect the automatic releaser.

**Comment by jstrachan** [comment]
@slide I sign off on this thanks!

**Comment by jglick** [comment]
@batmat yet I still lack write permission to the repository. I thought that was handled when one of these got merged?

**Comment by batmat** [comment]
Not by default @jglick, there are many cases where people already actually have permission to work/merge PRs, but not to release yet. So better please ask explicitly for it in general indeed.

Anyway, done now.
```
[14:30] <+     batmat> | jenkins-admin: yo
[14:30] <@jenkins-adm> | I didn't understand the command
[14:30] <+     batmat> | jenkins-admin: make jglick committer on jx-resources-plugin
[14:30] <@jenkins-adm> | Added jglick as a GitHub committer for repository jx-resources-plugin
[14:30] <+     batmat> | jenkins-admin: thanks botty friend
[14:30] <@jenkins-adm> | You're welcome
[14:30] <+     batmat> | jenkins-admin: no, really, that was helpful
[14:30] <@jenkins-adm> | Wut?
```

**Pull request merged**
