### PR TITLE
Blueocean release permissions

### PR DESCRIPTION
**Pull request by kshultzCB**
# Description

This pull request proposes to add several names to the list of people who can cut releases of [Blue Ocean](https://github.com/jenkinsci/blueocean-plugin), the related [sse-gateway plugin](https://github.com/jenkinsci/sse-gateway-plugin) related plugins, plus two components and a pom.

@halkeye and @vivek , FYI/AA. This would allow the team to be able to perform releases in response to bug reports.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above: Done for Blue Ocean, which is multi-module, and SSE Gateway.

### For a newly hosted plugin only: _Not Applicable_

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only: _Not Applicable_

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo. Yes, there are some folks on this list who do not have merge rights to Blue Ocean.

### CODE REVIEW

**Comment by slide** [comment]
Just to be clear, all of these people need Github access? 

richbg, dnusbaum, jtaboada, kshultz, bitwiseman, olamy

**Comment by dwnusbaum** [comment]
@slide Ideally, yes:
* `dnusbaum`: @dwnusbaum 
* `carroll`: @car-roll 
* `kshultz`: @kshultzCB 
* `jtaboada`: @joseblas 

I think everyone else has the same username for both platforms.

**Comment by slide** [comment]
@dwnusbaum Yikes...168 calls to the bot...

**Comment by halkeye** [comment]
Most of these are under the "blueocean-plugin" repo

**Comment by dwnusbaum** [comment]
@slide A bunch of these are all inside of a single GitHub repo: https://github.com/jenkinsci/blueocean-plugin, so maybe not quite that bad? 😅

**Comment by halkeye** [comment]
honestly a bunch of these I don't have access to
https://github.com/jenkinsci/blueocean-test-ssh-server
https://github.com/jenkinsci/blueocean-maven-plugin
https://github.com/jenkinsci/blueocean-acceptance-test (should get archived, its in the main repo)
https://github.com/jenkinsci/blueocean-pipeline-editor-plugin (merged)

So really its just and
https://github.com/jenkinsci/blueocean-display-url-plugin
https://github.com/jenkinsci/blueocean-autofavorite-plugin
https://github.com/jenkinsci/blueocean-plugin

I have admin on those, so I can add blueocean-developers team to the first two

**Comment by kshultzCB** [comment]
It was an oversight for me to not have added @car-roll to the original PR. I've fixed that now.

**Comment by slide** [comment]
Anyone who currently has voice access can give the necessary permissions. I don't want to mess up what repos and what people to add. So, can someone on the list take care of the Github permissions for the correct repos?

**Comment by dwnusbaum** [comment]
I don't think any of us have voice on IRC. Maybe @bitwiseman? If you want to give me (or someone else) voice, then I'd be happy to take care of it.

**Comment by slide** [comment]
Is it these repos?

https://github.com/jenkinsci/blueocean-test-ssh-server
https://github.com/jenkinsci/blueocean-maven-plugin
https://github.com/jenkinsci/blueocean-acceptance-test
https://github.com/jenkinsci/blueocean-pipeline-editor-plugin
https://github.com/jenkinsci/blueocean-display-url-plugin
https://github.com/jenkinsci/blueocean-autofavorite-plugin
https://github.com/jenkinsci/blueocean-plugin
https://github.com/jenkinsci/sse-gateway-plugin

**Comment by dwnusbaum** [comment]
Yeah that looks right, but like Gavin mentioned, if just doing these four main repos makes it easier for you, then I think that would be good enough for now:

* https://github.com/jenkinsci/blueocean-display-url-plugin
* https://github.com/jenkinsci/blueocean-autofavorite-plugin
* https://github.com/jenkinsci/blueocean-plugin
* https://github.com/jenkinsci/sse-gateway-plugin

**Comment by slide** [comment]
I think I got all of them...let me know if someone doesn't get access

**Pull request merged**
