### PR TITLE
Adding me (chuemb) to the set of developers to get upload access for …

### PR DESCRIPTION
**Pull request by chuemb**
…absint-a3 plugin

# Description

Link: https://github.com/jenkinsci/absint-a3-plugin

Please add myself (GitHub ID "chuemb") to the uploader group for the absint-a3-plugin 

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### CODE REVIEW

**Comment by halkeye** [comment]
we need one of the existing maintainers to approve

Also if you want to be listed as one of the developers (who can release), we need you to login to jira and artifactory

**Comment by NotMyFault** [comment]
Hey @chuemb,

to process this request, please
- create an account on http://accounts.jenkins.io/
- log in to Jira with the account created on accounts.jenkins.io: https://issues.jenkins.io/
- log in to artifactory with the account created on accounts.jenkins.io: https://repo.jenkins-ci.org/
- resolve the merge conflict

> we need one of the existing maintainers to approve

It appears, the LDAP name is not an individual user but a GH org. Possibly @bschommer could approve this PR, given they create the file and are part of the same organization?

**Comment by NotMyFault** [comment]
Hello @chuemb,

if you are still interested in getting this PR merged, please address the outstanding concerns above.
If not, I'll go ahead and close this PR.

Thanks!

**Comment by bschommer** [comment]
I did not create the file, but @chuemb is part of our organisation, which should now also be publicly visible.

**Comment by chuemb** [comment]
Hey Alexander,

thanks for your reply.

> to process this request, please
>
>   * create an account on http://accounts.jenkins.io/
>

=> We have a generic account "absint"

>   * log in to Jira with the account created on accounts.jenkins.io:
>     https://issues.jenkins.io/
>

=> Logged into Jira with "absint"

>   * log in to artifactory with the account created on
>     accounts.jenkins.io: https://repo.jenkins-ci.org/
>

=> logged into artifactory with "absint"

>   * resolve the merge conflict
>
>     we need one of the existing maintainers to approve
>
> It appears, the LDAP name is not an individual user but a GH org. 
> Possibly @bschommer <https://github.com/bschommer> could approve this 
> PR, given they create the file and are part of the same organization?
>

@bschommer recently approved me @chuemb as a part of the organization 
AbsInt.
Furthermore, as he explained, @chuemb should be visible as a member of 
AbsInt Organisation.

Is that sufficient for you to approve the PR?

Thanks and Best,
Christian

-

Christian Huembert
AbsInt Angewandte Informatik GmbH
Science Park 1
D-66123 Saarbruecken, Germany
***@***.***
Tel:   +49 681 3836034
Fax:   +49 681 3836020
WWW:http://www.absint.com

Geschaeftsfuehrung: Dr.-Ing. Christian Ferdinand
Registereintrag: HRB 11234 Amtsgericht Saarbruecken

-

Am 10.10.22 um 10:21 schrieb Alexander Brandes:

**Comment by NotMyFault** [comment]
This PR adds a user with the ID `chuemb` to the permission file. This account needs to log in to artifactory and jira (links are above) in order to make the build pass.

**Comment by NotMyFault** [comment]
I'll go ahead and close this PR, given the user you want to add didn't log into Jira and Artifactory within the past 6 months. Please have no hesitation to re-open the PR once this circumstance changes.

Thanks!

**Pull request closed without merging**
