### PR TITLE
Request for initial permissions for the new ElasTest plugin

### PR DESCRIPTION
**Pull request by franciscoRdiaz**
# Description
HOSTING-396: [https://issues.jenkins-ci.org/browse/HOSTING-396](https://issues.jenkins-ci.org/browse/HOSTING-396)
GitHub: [https://github.com/jenkinsci/elastest-plugin](https://github.com/jenkinsci/elastest-plugin)

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
What's with the PR title and commit history?

**Comment by daniel-beck** [comment]
Please complete all applicable items in the checklist. The repository readme explains how.

**Comment by franciscoRdiaz** [comment]
Applicable items checked!

Thank you!

**Comment by daniel-beck** [comment]
@franciscoRdiaz Now I understand the commit history. I recommend you look into working with Git branches if you're unfamiliar with those.

**Comment by franciscoRdiaz** [comment]
@daniel-beck  I'll do that.

Thank you!

**Pull request merged**
