### PR TITLE
Add flowpluginteam as developer for electricflow-plugin

### PR DESCRIPTION
**Pull request by justnoxx**
# Description

Repository URL: https://github.com/jenkinsci/electricflow-plugin
OPS ticket: OPS-9889

@horodchukanton @imago-storm @ovasilko

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by slide** [comment]
Please fill out the PR template, it is there for a reason.

**Comment by justnoxx** [comment]
@slide Repository URL has been added to the Description.

**Comment by rbywater** [comment]
@justnoxx Can you confirm that you have logged into the Jenkins Artifactory with the `flowpluginteam` user as the automated checks are failing to find a user with that name.

Also you will need to @ mention an existing maintainer for them to confirm they are happy with having the new user added.

**Comment by justnoxx** [comment]
@rbywater @slide well, I am the maintainer of the plugin now, but I will mention the other part of the team in the description.
I did a login before submitting this pull request. I am logged in now. Please, see screenshot attached:
Screen Shot 2020-06-26 at 9 11 16 AM

**Comment by batmat** [comment]
retriggering to see whether the failure cause is now fixed

**Comment by justnoxx** [comment]
@batmat look like that all validations are passed.

**Comment by oleg-nenashev** [comment]
I will merge it based on the insights I have about the maintenance state.

**Pull request merged**
