### PR TITLE
adding new plugin visual-basic-6

### PR DESCRIPTION
**Pull request by froque**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by daniel-beck** [comment]
@froque Please note that this permission will not be granted until you've logged in to Artifactory at https://repo.jenkins-ci.org once. Even then it may take a while for the permission to be effective. See https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by froque** [comment]
@daniel-beck thanks. missed that step

**Comment by daniel-beck** [comment]
@froque Permissions have been granted now.

**Pull request merged**
