### PR TITLE
enable cd for loadrunner-cloud

### PR DESCRIPTION
**Pull request by narcotics726**
# Description

Repository url: https://github.com/jenkinsci/loadrunner-cloud-plugin
Hosting request: https://github.com/jenkins-infra/repository-permissions-updater/issues/2732
Committers: @weisun10, @narcotics726

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by weisun10** [comment]
@halkeye, I see the "needs authorization" label. Is there anything we need to do at plugin side?

**Comment by halkeye** [comment]
@weisun10 I just need an approval from either person listed as a developer in the metadata.
You are one of them, @narcotics726 doesn't look like either of the names in the file.

**Comment by weisun10** [comment]
> @weisun10 I just need an approval from either person listed as a developer in the metadata. You are one of them, @narcotics726 doesn't look like either of the names in the file.

@halkeye, approved. Neither me or Nark (narcotics726) can approve the PR.

**Comment by halkeye** [comment]
approval comment is fine

**Pull request merged**
