### PR TITLE
Remove lvotypko from release permissions

### PR DESCRIPTION
**Pull request by olivergondza**
# Description

Tidying up after Lucie has left the team.

# Submitter checklist for changing permissions

### Always

- [n/a] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

@lvotypko, any objections?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Would be nice to have explicit confirmation before we move forward

**Comment by olivergondza** [comment]
Asking for Lucie's authorization.

**Comment by slide** [comment]
I think this has passed the limit of how long we need to wait. The developer was copied on this request  but did not respond for over two months. @oleg-nenashev any issues moving forward?

**Comment by olivergondza** [comment]
Updated as requested.

---

On an aside, do we really feel more comfortable retaining release permission for someone we cannot reach rather than removing them? Not that any of those component would be in any way critical, but ...

**Comment by oleg-nenashev** [comment]
I suppose it is a subject for the plugin ownership and adoption process rework.
I do not feel comfortable with retaining permissions TBH, but this is our de-facto practice due to the lack of process for removing maintainers. 

https://github.com/jenkins-infra/jenkins.io/pull/2678 is somewhat related, esp. the discussion with @timja in https://github.com/jenkins-infra/jenkins.io/pull/2678#discussion_r350747258

**Comment by olivergondza** [comment]
Thanks guys!

**Pull request merged**
