### PR TITLE
Add bitwiseman to github-api-plugin maintainters

### PR DESCRIPTION
**Pull request by bitwiseman**
# Description

I'm a maintainer for [github-api](https://github.com/github-api/github-api) and multiple scm plugins such as [github-branch-source-plugin](https://github.com/jenkinsci/github-branch-source-plugin).

I need *maintainer* and publish rights this plugin/repository:
https://github.com/jenkinsci/github-api-plugin

@oleg-nenashev @kohsuke 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo. Important: I need *maintainer* permissions.

### CODE REVIEW

**Comment by slide** [comment]
Sounds fine to me

**Comment by recena** [comment]
Absolutely yes!

**Comment by KostyaSha** [comment]
@bitwiseman i'm maintaining it. If you finally made a release, then i can make a release.

**Comment by KostyaSha** [comment]
JFYI Half of this list are not active maintainers and they got permissions without approval before. Story repeats.

**Pull request merged**
