### PR TITLE
Update plugin-xlrelease-plugin.yml

### PR DESCRIPTION
**Pull request by nitheshrayuduv**
# Description
Repo:
https://github.com/jenkinsci/xlrelease-plugin

@FellipeAvanci 

Mentioning users being added
@nitheshrayuduv
@nehag83
@yogeshghotekar
@isaacsatish
@sachgaik-xl
@soni-ankur
@vrushnim
@mflynn001
@balaji-digital-ai

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [x] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [x] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [x] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by nitheshrayuduv** [comment]
Hi Team,
These are the new team members who are added to our team those who will be maintaining plugin-xlrelease-plugin.
Everyone of them did the steps according to the tick boxes.
Thanks and Regards,
Nithesh

**Comment by FellipeAvanci** [comment]
I authorize these developers to get permission to our repo.

**Review by timja — CHANGES_REQUESTED** [review]
> Make sure to @mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).

this is missing

**Comment by nitheshrayuduv** [comment]
Have updated the description to have all the people who are being added with their GitHub usernames

**Comment by timja** [comment]
invites sent to github

**Pull request merged**
