### PR TITLE
Repository permission for Purge Job History Plugin

### PR DESCRIPTION
**Pull request by aytuncbeken**
Permission request for Purge Job History Plugin for adding new contributor.
GitHub repository: https://github.com/jenkinsci/purge-job-history-plugin

You can find old maintainer consent here 
https://github.com/jenkinsci/purge-job-history-plugin/pull/3
@stephenc I kindly re-request your permission here. Thanks

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by aytuncbeken** [comment]
@slide @stephenc   Who can give write permission to repository on GitHub, I still do not have write permission.

Thanks.

**Comment by slide** [comment]
I can do that later today, I keep forgetting to look for that checkbox (it was added somewhat recently).

**Comment by aytuncbeken** [comment]
@slide Thanks a lot!

**Comment by slide** [comment]
Permissions added, you may need to accept the invitation to join the org via email or github.

**Comment by aytuncbeken** [comment]
@slide Thanks, I tried to merge my request but still having problem. Also the mail I received from GitHub had this "  purge-job-history-plugin Developers has 1 member and gives *read* access to 1 jenkinsci repository." Is is possible that I still have read access ? I will be glad if you can check ? Thanks.

**Comment by slide** [comment]
I have no insight into the settings on the repo as I don't have access to view those. The method I used to add you should have given you full access to the repo.

**Comment by aytuncbeken** [comment]
Thanks @slide I will check again.

**Comment by michaelneale** [comment]
@aytuncbeken I saw your comment on irc - did you get to try it again? I can't see settings either, but the bot said you have access now to commit

**Comment by slide** [comment]
@daniel-beck fixed the issue

**Comment by aytuncbeken** [comment]
Hi Michael,

Now I can commit, thanks for the help.

**Pull request merged**
