### PR TITLE
Renaming a plugin

### PR DESCRIPTION
**Pull request by liuweiGL**
# Description

Renaming a plugin: https://github.com/jenkinsci/dingtalk-plugin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by slide** [comment]
The way you have done this, it create a completely new plugin as far as the update center and so forth is concerned. Both plugins will be able to be installed at the same time, which can cause issues. Please think very carefully about this.

**Comment by liuweiGL** [comment]
Is it because of the `plugin-dingding-notifications.yml` file rename to `plugin-dingTalk.yml`  ?

**Comment by liuweiGL** [comment]
If i just make changes:

```yml
name: "dingding-notifications"
github: "jenkinsci/dingding-notifications-plugin"
```
>>>

```yml
name: "dingTalk"
github: "jenkinsci/dingTalk-plugin"
```
Is it ok?

**Comment by liuweiGL** [comment]
Hi, I have tested it locally and it doesn't seem to matter.
Let's just do it !

**Comment by slide** [comment]
No, the issue is because you are changing the artifactId the plugin. This could cause instability for users, so we try not to do it. Also, we don't allow capital letters in artifactIds, so I won't merge that change. It must be all lower case. @oleg-nenashev can you weigh in here?

**Comment by liuweiGL** [comment]
Hi, i have restored the `path` setting. Please check again.

**Comment by slide** [comment]
If you just want it updated when people look at the update center and so forth, you just need to update the name tag in the pom.xml.

**Comment by liuweiGL** [comment]
The plugin name is different with repo name, it's confused and ugly !

I like everything to be the same, not just for users, but for developers and next adopter.

**Comment by liuweiGL** [comment]
If this change doesn't effect anyone, please merge .

Thank you very much !

**Comment by liuweiGL** [comment]
Dear administrator, you are the most handsome.

Just do it :kissing_heart:

**Comment by slide** [comment]
Most of the people reviewing these are volunteers. You will need to be patient. Telling people they are handsome to get something done will not work.

**Comment by liuweiGL** [comment]
I'm waiting for a merge to release a new version.

Anyway, thanks for your help. :beers:

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Thanks for mention me here. I'm not sure this is a good idea to bring a break changes. IMO if `dingtalk` is complete different with the current one, I would suggest to create a new one instead of changing it.
I agree with @slide about changing the tag name in pom.xml file if you just want to give it a better name. Further more, name might has a chance to change again for some reasons. Do we need to change it again?

**Comment by liuweiGL** [comment]
This is not a break change.

The `paths` property is plugin's unique identifier, and i did't change it.

**Comment by liuweiGL** [comment]
With the addition of features, the name is no longer applicable, i think that's normal.

**Comment by slide** [comment]
Most of the time, people just change the `<name></name>` in the pom.xml, this is the main user facing thing for the plugin. It is what people see in the update center and so forth. Having internal names change doesn't change anything for users.

**Comment by liuweiGL** [comment]
These changes don't affect users, i don't know why not?

Unity or chaos, what's your choice?

**Comment by slide** [comment]
I'm not sure what you mean by unity or chaos.

**Pull request closed without merging**
