### PR TITLE
Adding wwna @amazon.com to CodePipeline plugin maintainers

### PR DESCRIPTION
**Pull request by wwna**
https://github.com/jenkinsci/aws-codepipeline-plugin/commits/master

# Description

https://github.com/jenkinsci/aws-codepipeline-plugin/commits/master

@belltimo 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by spluthlu** [comment]
I confirm wwna should be added as a CodePipeline plugin maintainer.

**Comment by belltimo** [comment]
I confirm wwna should be added as a CodePipeline plugin maintainer.

**Comment by daniel-beck** [comment]
@wwna Do you still need commit access to the repo?

**Comment by wwna** [comment]
I think this is all I need, thanks

**Pull request merged**
