### PR TITLE
Synopsys coverity plugin adoption

### PR DESCRIPTION
**Pull request by jcroall**
# Description

Pull request for jenkins-infra/repository-permissions-updater to adopt plugin-synopsys-coverity to @jcroall.

Note: I am not able to login to Artifactory (https://repo.jenkins-ci.org/ui/login/) with my jenkins.io account, it repots incorrect username/password or locked user. I will track that down but need to get this assigned.

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
> Note: I am not able to login to Artifactory

The artifactory validation fails until you logged in initially. If you are unable to log in or can't reset your password, please raise a [helpdesk issue](https://github.com/jenkins-infra/helpdesk/issues/new/choose) selecting "Accounts" as service.

To authorize this PR, could you get an existing maintainer to approve it, please?

**Comment by jcroall** [comment]
All of the maintainers have left the company some time ago. We need this somewhat urgently to get access to a security ticket (have been in touch with Wadeck Follonier about this) but I can try and track them down if it is necessary.

I will raise a ticket about artifactory.

**Comment by NotMyFault** [comment]
> All of the maintainers have left the company some time ago. 

Oh, I see, I was under the impression someone is left to approve this PR, because `bdsoss` wasn't removed from the list.

If you want to gain access to the plugin in order to take care of an issue in the security project on jira, I'm fine if @Wadeck approves this PR, if both of you are already in touch.

**Comment by jcroall** [comment]
> > All of the maintainers have left the company some time ago.
> 
> Oh, I see, I was under the impression someone is left to approve this PR, because `bdsoss` wasn't removed from the list.
> 
> If you want to gain access to the plugin in order to take care of an issue in the security project on jira, I'm fine if @Wadeck approves this PR, if both of you are already in touch.

Great! I'll check in with him via our email thread.

Regarding the remaining account, we haven't been able to track down anybody who knows the password. It seems useful to have a service account for cases like this, so I'm inclined to leave it and see if we can track that down or get access to the email for it.

Thanks!

**Comment by timja** [comment]
The email for the account is bdsoss AT blackducksoftware.com if that helps

**Review by Wadeck — APPROVED** [review]
I discussed with Synopsis support before this PR. Thanks @jcroall for the PR.

It's perfectly fine to move forward in terms of approval 👍

**Review by NotMyFault — APPROVED** [review]

**Comment by Wadeck** [comment]
@NotMyFault Have you added jcroall and removed the others from the list of maintainers?
Perhaps I am missing something but the list of maintainers does not seem to have changed in https://github.com/jenkinsci/synopsys-coverity-plugin

**Comment by NotMyFault** [comment]
> @NotMyFault Have you added jcroall

Organization invites are only valid for 7 days. I'm not sure if they did accept the original invite, however, I added them again to the team @jcroall 

> and removed the others from the list of maintainers?

I can't manage team memberships, therefore I didn't remove the other users.

**Comment by Wadeck** [comment]
Thanks for the quick answer 👍

**Pull request merged**
