### PR TITLE
create new plugin scm-httplient

### PR DESCRIPTION
**Pull request by meowlomoDevelopment**
# Description

Permissions update for scm-httpclient Plugin
Plugin source can be found at: https://github.com/jenkinsci/scm-httpclient-plugin
Approved hosting request can be found at: https://issues.jenkins-ci.org/browse/HOSTING-702

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by meowlomoDevelopment** [comment]
sorry, the Description 'Permissions update for scm-httpclient Plugin' corrects as 'Permissions update for SCM HttpClient Plugin'

**Comment by meowlomoDevelopment** [comment]
When i releasing to jenkins-ci.org, it shows that github path is @github.com:meowlomo/scm-httpclient-plugin.git . However, my repo path is git@github.com:jenkinsci/scm-httpclient-plugin.git actually. Is any suggestion for me? thanks.
 
default

**Comment by slide** [comment]
You'll need to fix your pom.xml:

https://github.com/jenkinsci/scm-httpclient-plugin/blob/master/pom.xml#L30

**Comment by meowlomoDevelopment** [comment]
Thank you.

**Pull request merged**
