### PR TITLE
Add timja to slack-plugin

### PR DESCRIPTION
**Pull request by timja**
# Description

https://github.com/jenkinsci/slack-plugin

Commit access granted:
https://groups.google.com/forum/#!topic/jenkinsci-dev/0pyFI2oJlog

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@kmadel Please approve

**Comment by oleg-nenashev** [comment]
Approval in https://groups.google.com/forum/#!topic/jenkinsci-dev/0pyFI2oJlog is probably enough @daniel-beck

**Comment by batmat** [comment]
yeah, approved publicly by @kmadel already indeed.

**Comment by batmat** [comment]
Will merge as soon as the PR build completes.

**Comment by kmadel** [comment]
I approve

**Pull request merged**
