### PR TITLE
New maintainer for build-with-parameters plugin

### PR DESCRIPTION
**Pull request by sugonyakivan**
# Description

Link: https://github.com/jenkinsci/build-with-parameters-plugin
Replacing developer with myself, commit permissions proof https://github.com/jenkinsci/build-with-parameters-plugin/commit/04ca138309b71bb3693f36d802ebb6bd0b38d348

# Permissions pull request checklist

### Always

- [x ] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [ x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@jessicaaustin's last release predates the cut-off date I used to create the initial permissions file, but I think she could still be considered the previous maintainer (or perhaps @olivergondza?).

Could either of you confirm this request to get release permissions for the plugin? Thanks!

**Comment by daniel-beck** [comment]
Also, @olivergondza you're getting removed here. Was this coordinated with you?

**Comment by olivergondza** [comment]
I do not feel to be a maintainer for the plugin - just fixed what I needed and moved on. No objections on adopting the plugin from me.

**Comment by jessicaaustin** [comment]
@daniel-beck I've spoken with @sugonyakivan over email and he's agreed to take over the plugin from me. Thanks!

**Comment by daniel-beck** [comment]
@sugonyakivan I also made you default assignee for Jira issues for this plugin.

**Pull request merged**
