### PR TITLE
get sqs plugin maintainers release privileges

### PR DESCRIPTION
**Pull request by joppa27**
# Description

https://github.com/jenkinsci/github-sqs-plugin
@aaronwalker @nemo83

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by joppa27** [comment]
Not sure if this has been done correctly, but wanted to get the ball rolling so the latest version of the `github-sqs-plugin` can be publish to the maven repo

**Comment by nemo83** [comment]
I have logged into the Artifactory and nemo83 is my account name on github, artifactory and the yaml. @joppa27 feel free to tick the checkboxes if ok for you too.

**Comment by joppa27** [comment]
@nemo83 consider it done :)

**Comment by nemo83** [comment]
funny I issued the same pr just a bunch of minutes before :-)

**Comment by nemo83** [comment]
can someone please merge this PR? it should be good to go. Right?

**Comment by oleg-nenashev** [comment]
Yeah. Sorry, we're still recovering from the NY break so that it takes time to process everything

**Pull request merged**
