### PR TITLE
Add markewaite as a versioncolumn maintainer

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Add markewaite as versioncolumn maintainer

@batmat agreed in a private meeting that he was willing to allow me to be a developer on the plugin so that it can be extended to support Java 17.

@batmat could you comment on this pull request to confirm you are OK with me being added as a maintainer?

https://github.com/jenkinsci/versioncolumn-plugin is the plugin repository

# Description

Java 17 support and plugin modernization are my primary targets.

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by basil — APPROVED** [review]
Thanks for helping move the ecosystem forward to Java 17!

**Comment by NotMyFault** [comment]
> batmat could you comment on this pull request to confirm you are OK with me being added as a maintainer?

The plugin is labeled as up for adoption and doesn't need a maintainer approval, therefore, but I'll hold it off if you want an approval 👍🏻

**Comment by MarkEWaite** [comment]
> The plugin is labeled as up for adoption and doesn't need a maintainer approval, therefore, but I'll hold it off if you want an approval 👍🏻

Thanks for catching my mistake!  No need to wait for approval from @batmat since he had already marked it as "up for adoption".

**Review by NotMyFault — APPROVED** [review]

**Comment by batmat** [comment]
FTR, I had put the plugin up for adoption after we discussed with Mark (I was basically checking I still know how to do it).
I was planning hence to either approve manually, or the process be fast-tracked if I wasn't approving fast enough :-).

All good, so. o/

**Pull request merged**
