### PR TITLE
permission for GSOC 2018 project simple pull request job plugin alpha…

### PR DESCRIPTION
**Pull request by gautamabhishek46**
… release

# Description
GSoC 2018 project [Simple pull request pluign](https://github.com/jenkinsci/simple-pull-request-job-plugin/tree/alpha-1.0). Work done till now needs to be released for alpha testing.
[Hosting issue](https://issues.jenkins-ci.org/browse/HOSTING-548?filter=-2)

Link to the repository branch [https://github.com/jenkinsci/simple-pull-request-job-plugin/tree/alpha-1.0](https://github.com/jenkinsci/simple-pull-request-job-plugin/tree/alpha-1.0)

@oleg-nenashev @kwhetstone @martinda @grandvizier

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by gautamabhishek46** [comment]
I forgot to logged into Artifactory AFAICT. Now I have logged into Artifactory AFAICT, how can I trigger a build without pushing a commit.

**Comment by daniel-beck** [comment]
> AFAICT, how can I trigger a build without pushing a commit.

Closing, waiting for a minute, then reopening the pull request does it.

**Comment by oleg-nenashev** [comment]
+1 to @daniel-beck

**Comment by gautamabhishek46** [comment]
@daniel-beck @oleg-nenashev Done. One thing is that now the name of permission file is "plugin-simple-pull-request-job-plugin.yml" is this ok?

**Comment by oleg-nenashev** [comment]
@gautamabhishek46 It would be better to remove "-plugin" from Artifact ID and from the file name. So we have this suffix only for the repo name

**Comment by gautamabhishek46** [comment]
@oleg-nenashev done

**Pull request merged**
