### PR TITLE
add yfangsl to sauce on demand plugin dev list

### PR DESCRIPTION
**Pull request by yfangsl**
# Description

Adding @yfangsl to https://github.com/jenkinsci/sauce-ondemand-plugin/

Please ping @halkeye for verification

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@halkeye Please confirm/reject this request for upload (release) permissions for this plugin by commenting.

**Comment by halkeye** [comment]
@daniel-beck looks good.
I think we should remove ross, should I/we submit a new pr for that?

**Comment by daniel-beck** [comment]
@halkeye Yes, please. As a courtesy, please ping them in that PR.

@halkeye @yfangsl Please also clarify whether I still need to grant commit access to the GitHub repo.

**Comment by yfangsl** [comment]
@daniel-beck I think I need access? My understanding is the permissions are separate, yes?

**Comment by daniel-beck** [comment]
@yfangsl That was my question in the previous comment. A made you committer.

**Pull request merged**
