### PR TITLE
Add g3n35i5 to developers list

### PR DESCRIPTION
**Pull request by mPokornyETM**
@g3n35i5 thx for your help

# Description

As discussed [here](https://github.com/jenkinsci/lockable-resources-plugin/pull/451#issuecomment-1408137977) it will be great when @g3n35i5 has review permissions as well. Otherwise there are no other active reviewer and PRs must be done without review.

plugin (lockable-resources)[https://github.com/jenkinsci/lockable-resources-plugin]

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
  **note** : I am not sure if it is correct name. I added GitHub account here
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by g3n35i5** [comment]
@mPokornyETM I'm happy to help!

As far as I can see, the only think I needed to do was to do a login in the Artifactory service. I did this now.

**Comment by NotMyFault** [comment]
@mPokornyETM 

> has review permissions as well.

If you just want them to be part of the GitHub team, I can add them to the GitHub team only. The developers list in this repository is used for release permissions, which is handled by CD in your case.

**Comment by mPokornyETM** [comment]
> GitHub

Sorry what means GitHub ? What I want is, that he became notification, when some PR is open (or changed) and he can approve / decline the changes. I am not sure if is this correct way, when not sorry for distribution ;-)

**Comment by mPokornyETM** [comment]
> @mPokornyETM I'm happy to help!
> 
> As far as I can see, the only think I needed to do was to do a login in the Artifactory service. I did this now.
> 
> My Jenkins community (LDAP) account is equal to my GitHub account name `g3n35i5` so this should match as well.

login to Artifactory makes sense also for other services you will need maybe later

**Comment by NotMyFault** [comment]
> What I want is, that he became notification, when some PR is open (or changed) and he can approve / decline the changes. I am not sure if is this correct way, when not sorry for distribution ;-)

Then a team addition is all they need. See the [GitHub permissions issue template](https://github.com/jenkins-infra/repository-permissions-updater/issues/new/choose) for future reference. Filling a pull request and adding a user to the developers list is only needed if you want someone to have release permission for a plugin. Given you're using CD, no release permission is needed because they happen automatically.

I invited the user mentioned to the team associated to your repository.

**Pull request closed without merging**
