### PR TITLE
Add marcos bento to prqa plugin

### PR DESCRIPTION
**Pull request by marcosbento**
Add marcos_bento as developer for prqa-plugin https://github.com/jenkinsci/prqa-plugin

jenkins-ci.org account: marcos_bento

cc: @isanych

### CODE REVIEW

**Comment by isanych** [comment]
Please add Marcos to developers

**Comment by daniel-beck** [comment]
@marcosbento Do you still need commit access to the repo? Happy to grant that as well, or perhaps @isanych wants to be team maintainer?

**Comment by marcosbento** [comment]
Yes, I would like to have commit access to the repository.

**Comment by daniel-beck** [comment]
@marcosbento done

**Pull request merged**
