### PR TITLE
add additional maintainer

### PR DESCRIPTION
**Pull request by dirk-thomas**
I would like to release a new version of the plugin (https://github.com/jenkinsci/jobrequeue-plugin/).

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
So the ownership handover request is here: https://groups.google.com/forum/#!searchin/jenkinsci-dev/dthomas%7Csort:relevance/jenkinsci-dev/a7Mzp8aMjww/Ram6k-FQDQAJ

**Comment by dirk-thomas** [comment]
The request has been granted by the original maintainer. See jenkinsci/jobrequeue-plugin#3 for his comment. I as able to merge the PR afterwards.

**Comment by oleg-nenashev** [comment]
Agreed, it's enough

**Comment by dirk-thomas** [comment]
Thank you for the fast merge. I was able to upload the new version.

Is there a delay until the new package version (1.1.) appears on the [plugin page](https://wiki.jenkins-ci.org/display/JENKINS/JobRequeue-Plugin) and the [download](http://updates.jenkins-ci.org/download/plugins/jobrequeue/)?

**Comment by oleg-nenashev** [comment]
There is a delay, because infra needs to sync mirrors.
It commonly takes several hours to propagate changes

**Comment by dirk-thomas** [comment]
Thanks for clarifying. Then I can have a reasonable expectation when to check it again instead of pushing refresh for the next hours :wink:

**Pull request merged**
