### PR TITLE
grant release permission to momin for environment-dashboard plugin

### PR DESCRIPTION
**Pull request by mominkhan**
Please add momin as a developer for environment-dashboard plugin

jenkins-ci.org account: momin

cc:  @mominkhan

Plugin Repository:
- https://github.com/vipinsthename/environment-dashboard

Commit reference: 

- https://github.com/vipinsthename/environment-dashboard/commit/d24a085baf99e6c7b72a37c7c567eeb695ac9712

### CODE REVIEW

**Comment by daniel-beck** [comment]
Needs approval by @vipinsthename -- as this is outside the GitHub organization (which is strongly discouraged BTW), we have no access.

**Comment by mominkhan** [comment]
@vipinsthename .. please approve

**Comment by mominkhan** [comment]
The maintainer of the environment dashboard plugin seems to be inactive and unresponsive.

@daniel-beck  .. can you please suggest what can be done in this scenario?

**Comment by daniel-beck** [comment]
@mominkhan Please try to contact the maintainer via email directly in case they file away GitHub notifications without reading.

**Comment by daniel-beck** [comment]
@vipinsthename Ping

**Comment by batmat** [comment]
Closing as outdated, no answer since more than 1 year.

**Pull request closed without merging**
