### PR TITLE
Enable CD Permissions

### PR DESCRIPTION
**Pull request by lukej7**
# Description

Enable cd permissions for our plugin repo so we can start automating releases

# Submitter checklist for adding or changing permissions

### Always

- [x]  Add link to plugin/component Git repository in description above
https://github.com/jenkinsci/bigpanda-plugin

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

https://github.com/jenkinsci/bigpanda-plugin/pull/10

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
Both commits linked are invalid and incomplete. Please add a link to PR enabling CD according to the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) preparing your plugin for CD, rather than committing only parts of the work needed.

Thanks!

**Comment by lukej7** [comment]
Hey @NotMyFault ! Sorry about that! Is this what you mean? https://github.com/jenkinsci/bigpanda-plugin/pull/10

Or are you saying I should go ahead with the other steps and put those in a PR?

Thank you!

**Comment by NotMyFault** [comment]
> Or are you saying I should go ahead with the other steps and put those in a PR?

I am looking for a complete PR which enables CD according to the documentation I linked above, rather than several wrong changes over the place.
The PR you linked is still incomplete.

**Comment by lukej7** [comment]
Hey there @NotMyFault , okay apologies for that I understand now, I've updated the PR to enable CD: https://github.com/jenkinsci/bigpanda-plugin/pull/10

How's that?

**Review by NotMyFault — APPROVED** [review]
That's good!

**Pull request merged**
