### PR TITLE
Add mmitche as ghprb maintainer

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by daniel-beck** [comment]
It doesn't look like you're a committer to the GHPRB plugin, and I don't see anything on the mailing list related to you maintaining the plugin. So what motivates this request?

@benpatterson Do you know more about this?

**Comment by daniel-beck** [comment]
Also, no Artifactory login yet.

**Comment by benpatterson** [comment]
Hi @daniel-beck . Yes, I contacted @mmitche directly after [pointing out](https://groups.google.com/forum/#!msg/jenkinsci-dev/iHBzu1sBOmI/_XGXvtPiBQAJ) on the jenkins-dev list that I can't go it alone. He understands the plugin and looks like he had interacted with the previous maintainer so I thought he could lend a hand.

He would be co-maintainer along with me for now. HTH

**Comment by daniel-beck** [comment]
@benpatterson Thanks.

@mmitche Could you clarify whether you also still need commit access? I can grant that if necessary.

**Comment by daniel-beck** [comment]
@benpatterson Will you remain default assignee of issues in Jira?

**Comment by benpatterson** [comment]
Hi @daniel-beck ... Yes, I should still be the default assignee.

**Comment by daniel-beck** [comment]
@mmitche You still need to log in to Artifactory before we can proceed here.

And if you still need commit access I can also grant you that if you tell me to.

**Comment by mmitche** [comment]
@daniel-beck I'm not totally familiar with artifactory.  Where do I log in?

**Comment by daniel-beck** [comment]
@mmitche See this repo's README.

**Comment by mmitche** [comment]
@daniel-beck Sorry about the delay, done.

**Pull request merged**
