### PR TITLE
Synopsys coverity add schatti

### PR DESCRIPTION
**Pull request by jcroall**
# Description

Change for: jenkins-infra/repository-permissions-updater
Adding R&D colleague to: synopsys-coverity-plugin

@jcroall as the current maintainer - approves this addition
Suresh Chatti 'schatti' in Jenkins, @schatti123 in GitHub as developer on project.

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
@jcroall Could you check your commit, please? It looks malformed.

**Comment by jcroall** [comment]
Whoops, it totally was malformed! Sorry about that.

**Comment by NotMyFault** [comment]
This is still wrong.

**Comment by NotMyFault** [comment]
I resolved the conflicts for you. Are the users supposed to be added to the GitHub repository too? If so, please specify their GitHub handles.

**Comment by jcroall** [comment]
> I resolved the conflicts for you. Are the users supposed to be added to the GitHub repository too? If so, please specify their GitHub handles.

Thanks, I added his GitHub handle of @schatti123.

**Comment by jcroall** [comment]
User has also logged into Artifactory using Jenkins.io credentials.

**Review by slide — APPROVED** [review]

**Comment by slide** [comment]
@schatti123 has been added as a committer on the repo as well.

**Pull request merged**
