### PR TITLE
Update plugin-docker-slaves.yml

### PR DESCRIPTION
**Pull request by ndeloof**
see https://issues.jenkins-ci.org/projects/HOSTING/issues/HOSTING-190 for details

### CODE REVIEW

**Comment by batmat** [comment]
:+1: but what I don't get is that seems you have released from your history. Did you just disable the deploy part to test it locally @ndeloof ?

**Comment by batmat** [comment]
You should be able to release in ~5 min Nicolas.

**Comment by ndeloof** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project docker-slaves: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:docker-slaves:hpi:1.0.4 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/docker-slaves/1.0.4/docker-slaves-1.0.4.hpi, ReasonPhrase: Forbidden. -> [Help 1]

**Comment by batmat** [comment]
Actually I see the problem. I went too fast yesterday: you didn't suffix the path up to the artifactId @ndeloof

**Comment by ndeloof** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/72

**Pull request merged**
