### PR TITLE
Add ljader as developer to jsch-plugin

### PR DESCRIPTION
**Pull request by ljader**
This PR should be merged **ONLY AFTER** @daniel-beck contacts @zregvart about granting me push access to jsch-plugin (to merge https://github.com/jenkinsci/jsch-plugin/pull/2)

### CODE REVIEW

**Comment by daniel-beck** [comment]
No response from @zregvart after several weeks, so we can consider the plugin abandoned.

Now I'd like to get clarification whether @ljader will be taking over as maintainer.

**Comment by oleg-nenashev** [comment]
👍 for going forward once @ljader responds

**Comment by zregvart** [comment]
Sorry guys didn't missed the notification, feel free to add @ljader, thanks and sorry for late reply.

**Comment by daniel-beck** [comment]
@zregvart Thanks for your response!

Are you interested at all in continuing to maintain the plugin?

There's also a thread on the jenkinsci-dev mailing list about this request on which you've been cc'ed.

**Comment by zregvart** [comment]
@daniel-beck the `jsch-plugin` in the current state is just `pom.xml`, from the pull request (jenkinsci/jsch-plugin#2) I see that the intent is to move forward with the motive I had: solve ClassCastException due to two versions of jsch jar present in classpath. So I would recognize @ljader contribution as more significant than my own. In that light make @ljader the maintainer, and remove myself. Thank you and once again sorry for not noticing the e-mails and notifications on github.

**Comment by ljader** [comment]
Hi all, please make me the maintainer of the jsch-plugin.

I will merge my PR and release the jsch-plugin,
which are the precondition to continue with the fix in ssh-plugin.

**Comment by oleg-nenashev** [comment]
@ljader done

**Pull request merged**
