### PR TITLE
Added @JoeMerten to ansicolor.

### PR DESCRIPTION
**Pull request by dblock**
# Description

Please add @JoeMerten to https://github.com/dblock/jenkins-ansicolor-plugin release permissions.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@dblock Done. Note that it's generally preferable to host plugin repositories in the jenkinsci organization to allow continuity if you decide to move on. Maybe something to consider.

**Comment by dblock** [comment]
Yes, I'd actually like to do that @daniel-beck. Which org is that? How do I transfer?

**Comment by oleg-nenashev** [comment]
Actually there is already a repo for that https://github.com/jenkinsci/ansicolor-plugin
So maybe we just need to grant commit permissions and to adjust the POM file

**Comment by daniel-beck** [comment]
@oleg-nenashev Issues are tracked in GitHub, so I think we need to transfer. Restoring use of the forked repo doesn't help anyone.

@dblock Great to hear! So what I propose is that I make you an admin of https://github.com/jenkinsci-transfer, allowing you to transfer your repository into that organization. From there, Oleg or I can transfer it into https://github.com/jenkinsci with all PRs and issues intact. You'll be made repo admin and we can add your existing committers, we just need a list (and everyone needs to accept membership into the jenkinsci org).

**Comment by dblock** [comment]
I do this often to other repos and orgs, so how about I transfer it to you and you just transfer it to the org, so you don't need to make me admin.

**Comment by dblock** [comment]
@daniel-beck I requested the transfer. You should kill the fork in https://github.com/jenkinsci/ansicolor-plugin, then accept and transfer into the jekinsci org.

**Comment by JoeMerten** [comment]
Seeing that it's merged and retried:

    git checkout ansicolor-0.5.0 && mvn clean deploy

but still no permission:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project ansicolor: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:ansicolor:hpi:0.5.0 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Failed to transfer file: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor/0.5.0/ansicolor-0.5.0.hpi. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

Complete buildog: [mvn-deploy-buildlog.txt](https://github.com/jenkins-infra/repository-permissions-updater/files/853435/mvn-deploy-buildlog.txt)

Tried both `joemerten` and `JoeMerten` in `~/.m2/settings.xml`.

Any suggestions?
Maybe have to wait some duration til the permission changes takes into affect?

**Comment by JoeMerten** [comment]
Maybe need to put lower case `joemerten` into [permissions/plugin-ansicolor.yml](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ansicolor.yml)?

**Comment by daniel-beck** [comment]
@JoeMerten Yes, that's the problem. I wasn't sure whether it's case sensitive, now we know. Fixing…

**Comment by daniel-beck** [comment]
@dblock Done! https://github.com/jenkinsci/ansicolor-plugin Thanks for agreeing to the transfer. 

PTAL, you should be admin and existing contributors have write access. Please adjust the POM to point to this repo; while GitHub is redirecting, it'll make some tooling easier (e.g. the upcoming https://github.com/jenkins-infra/backend-update-center2/pull/126 )

**Comment by JoeMerten** [comment]
@db with lowercase `joemerten`, upload has been succeeded how.
Wowever, there is one small cosmetic issue left.

Checked yesterday in a fresh installed jenkins 1.653. Manage Jenkins → Manage Plugins → Available
→ AnsiColor is displayed with 0.5.0
But when clicking AnsiColor which is a link to https://plugins.jenkins.io/ansicolor, it displays old information: "0.4.3" et cetera. See also [AnsiColor #99](https://github.com/jenkinsci/ansicolor-plugin/issues/99#issuecomment-287797832). Any idea how to solve this?

**Comment by daniel-beck** [comment]
@JoeMerten There's currently an issue with the data update to the plugins site. Should be resolved later today.

FWIW you can easily see this on the home page by checking when the topmost "Recently Updated" plugin was released. As there's plugin releases basically every day, "5 days go" means the plugins site is probably ~4 days outdated.

Also, I'm @daniel-beck :wink:

**Comment by JoeMerten** [comment]
Hey @daniel-beck,
could you explain why there are two different styled plugin info pages?
- https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin
- https://plugins.jenkins.io/ansicolor

Note: I'd also created an issue report at https://issues.jenkins-ci.org/browse/JENKINS-43007, cause don't know were the right place / responsibility was.

Joe.

**Comment by daniel-beck** [comment]
> cause don't know were the right place / responsibility was.

Every 'Create Issue' screen links to https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue which explains where to report what.

**Comment by daniel-beck** [comment]
@JoeMerten 

> why there are two different styled plugin info pages?

We started with the wiki where the actual plugin documentation is maintained. The plugin site (plugins.j.io) was added as part of the jenkins.io site redesign a year ago, as the wiki didn't scale well (lists by wiki page label, etc., it was a mess). This site accesses the wiki to incorporate plugin documentation. I plan to change the plugin info macro on wiki pages to basically just point to the new site, then we'll have:

- wiki.j.o: hosts documentation in most cases.
- plugins.j.io: displays documentation and metadata, has search and 'interesting' plugins listed on home page.

Happy to discuss/explain further, but this should probably be moved onto jenkinsci-dev or IRC. Closed PRs aren't a great place for extended discussions.

**Pull request merged**
