### PR TITLE
add plugin-lark-notification.yaml

### PR DESCRIPTION
**Pull request by zhouxinfeng**
Our team will be adopting the lark-notification-plugin.
github repo: https://github.com/jenkinsci/lark-notification-plugin

dev wiki:https://wiki.jenkins.io/display/JENKINS/lark-notification-plugin

# Description

# Submitter checklist for changing permissions

### Always
https://github.com/zhouxinfeng/lark-notification-plugin
- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only
https://issues.jenkins-ci.org/browse/HOSTING-733
- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Thanks for your contribution. But you need to create a correct ticket for this. And please read the guideline below.
https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins

**Comment by LinuxSuRen** [comment]
Also you need to add a link to resolved HOSTING issue in description above.

**Comment by zhouxinfeng** [comment]
> Thanks for your contribution. But you need to create a correct ticket for this. And please read the guideline below.
> https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins

I have added,Is there any mistake?

**Comment by LinuxSuRen** [comment]
You still need to file an issue in the HOSTING project instead of JENKINS project. Plus, the correct issue must be resolved and put that link into the description above.

**Comment by zhouxinfeng** [comment]
> You still need to file an issue in the HOSTING project instead of JENKINS project. Plus, the correct issue must be resolved and put that link into the description above.



> You still need to file an issue in the HOSTING project instead of JENKINS project. Plus, the correct issue must be resolved and put that link into the description above.

submited agian,is "https://issues.jenkins-ci.org/browse/HOSTING-733" ?,forgive me a newly plugin‘s  developer ,thanks a lot.

**Comment by LinuxSuRen** [comment]
No worry about this. And no more other problems. Just wait for the [issues](https://issues.jenkins-ci.org/browse/HOSTING-733) to be resolved.

**Comment by batmat** [comment]
Hosting request has been resolved afaict. Do you plan to finalize this @zhouxinfeng ? Thanks

**Comment by batmat** [comment]
@slide do you think anything is still missing? Thanks :)

**Comment by slide** [comment]
@batmat, there is still some stuff that needs to happen because there were two hosting requests from the same company for similar things, I'd like to hold off on this for the time being.

**Pull request closed without merging**
