### PR TITLE
Add aws-sam as new plugin

### PR DESCRIPTION
**Pull request by mikedeck**
# Description

This request is to add the AWS SAM plugin: https://github.com/jenkinsci/aws-sam-plugin

I am requesting release access for myself (mikedeck_AWS) and I am one of the committers to this repo.

Here is the hosting request ticket: https://issues.jenkins-ci.org/browse/HOSTING-630

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks good, but it's very unusual that the original requester is not one of the uploaders. Is that intentional?

Please also not that only users listed in this file are considered (equal co-)owners of the plugin. So when it's essentially a company maintaining the plugin (as appears to be the case here), we recommend a list of co-workers, or perhaps grant access to a general team account as well. Will make things less weird after previous maintainers change jobs as well. While there's a process for transferring maintainership of abandoned plugins, it's slow.

**Comment by mikedeck** [comment]
@daniel-beck, agreed Sean Summers (original) requester should be an uploader too, but I haven't confirmed with him that he has logged into Artifactory yet and I didn't want that to break the automation or cause a rejection as I'm trying to get this released before Jenkins World. I definitely understand the convention and definitely plan on getting others added shortly. I'd appreciate it if we could get this initial access set up for the first release and do a fast follow to add others.

**Comment by daniel-beck** [comment]
@mikedeck This was delayed a bit as I was at DWJW in SF, and just returned home.

**Comment by mikedeck** [comment]
@daniel-beck, no problem, sorry for being a pest and thanks for merging!

**Pull request merged**
