### PR TITLE
add new maintainer of amazon-ecs-plugin

### PR DESCRIPTION
**Pull request by gokhanoner**
setup developer permission to gokhanoner (@gokhanoner)

Git URL -> https://github.com/jenkinsci/amazon-ecs-plugin

@webratz @pgarbe @markyjackson-taulia 

# Description

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
+1

**Review by oleg-nenashev — APPROVED** [review]
The plugin is up for adoption, so looks good to me. Please restore the checklist from the PR template @gokhanoner , it is important for permission transfer. Usually we also ask for a few contributions to be submitted first, but IIUC it was sorted out in the mailing list

**Comment by gokhanoner** [comment]
@oleg-nenashev do you want me to post the check-list to the initial commit? All of it or only some part?

**Review by yJunS — APPROVED** [review]

**Comment by slide** [comment]
@gokhanoner The PR template is not part of a commit, it is just something that shows up when you make a PR. It has checkboxes that you need to fill in to make sure we have all the necessary info.

**Comment by gokhanoner** [comment]
@slide @oleg-nenashev PR template restored.

**Comment by slide** [comment]
@markyjackson-taulia you are `jequals5` in the permissions file, correct?

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia you are `jequals5` in the permissions file, correct?

@slide yes

**Pull request merged**
