### PR TITLE
Adoption request for "CloudBees CD" plugin

### PR DESCRIPTION
**Pull request by CJkrishnan**
# Link to GitHub repository

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@CJkrishnan`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by CJkrishnan** [comment]
> You forgot to fill out the PR template.

Now I filled out the PR template

**Comment by alecharp** [comment]
Hello @CJkrishnan, have you reach out to the current maintainers prior to request admin access on the repository? I don't see any closed or on-going pull request from you on this repository. Any reason you are requesting to become a maintainer on this plugin?

**Comment by CJkrishnan** [comment]
> Hello @CJkrishnan, have you reach out to the current maintainers prior to request admin access on the repository? I don't see any closed or on-going pull request from you on this repository. Any reason you are requesting to become a maintainer on this plugin?

I reached out my team mates those are worked on it already, regarding existing maintainer accounts. They are going to ensure the existing accounts are still usable or not, then they will update to me. So Still I am waiting for the reply from them.
Once I got the reply I will update you.

**Comment by NotMyFault** [comment]
A comment or review by an existing maintainer is more than enough.

**Comment by justnoxx** [comment]
@NotMyFault fine with me, please proceed.

**Pull request merged**
