### PR TITLE
please add michaelbaron to the klocwork-plugin

### PR DESCRIPTION
**Pull request by michael-baron**
# Description

Adding upload permissions to @michael-baron, the maintainer of https://github.com/jenkinsci/klocwork-plugin

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@michael-baron I remember the repo was hosted in another organization for a while, and the history diverted. Has this been cleaned up?

**Comment by daniel-beck** [comment]
@michael-baron To clarify, you're @jlarfors's colleague? I don't see any mention of you in the mailing list threads on transfer of maintainership.

**Comment by michael-baron** [comment]
@daniel-beck Yes I'm a colleague of @jlarfors working at http://emenda.com. As partners of Klocwork we continued to maintain the plugin, however due to issues with access to the repository this was done externally as you suggest. After getting access we have now merged in our external version with the official repository mentioned above.

**Comment by daniel-beck** [comment]
@michael-baron Thanks for the clarification.

FTR I have also contacted @oleg-nenashev who granted you commit access and he confirmed that @jlarfors requested commit access for you. (Your GitHub profile is a bit lightweight.)

**Pull request merged**
