### PR TITLE
Add more developers for CodeDeploy jenkins plugin

### PR DESCRIPTION
**Pull request by yubangxi**
Add yubangxi, feverlu and q13117god

### CODE REVIEW

**Comment by suryanarayanan** [comment]
Looks good to me.

**Comment by daniel-beck** [comment]
None of these have admin access to https://github.com/jenkinsci/aws-codedeploy-plugin ?

**Comment by yubangxi** [comment]
Hi Daniel,

How can we request admin access to the main plugin repo? https://github.com/jenkinsci/aws-codedeploy-plugin

**Comment by daniel-beck** [comment]
@yubangxi Current admins are @suryanarayanan and @Jmcfar and can grant access.

Just wondering -- Note that this is just the permissions to upload a release; you'll need to be granted at least write access to the Git repo elsewhere.

**Comment by yubangxi** [comment]
Access to original plugin repo has been approval by @suryanarayanan

**Pull request merged**
