### PR TITLE
added one developer from MicroFocus for making a release 

### PR DESCRIPTION
**Pull request by ivkrishna-mf**
# Description 
added one developer from MicroFocus for making a release 

https://github.com/jenkinsci/accurev-plugin
@casz 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by ivkrishna-mf** [comment]
@casz  can you look into this for providing the access to maintain accurev plugin

**Comment by ivkrishna-mf** [comment]
sure @casz  i will be working on one RPI and i will make a pull request soon

**Comment by batmat** [comment]
There are checkboxes in the PR template for a reason. Please complete all that apply. Thanks

**Comment by ivkrishna-mf** [comment]
ok. i will do that.

**Comment by batmat** [comment]
OK, I believe we can close this for now. Please comment here so we reopen when people have gained legitimacy to get release access. 

Or please correct me if I misunderstood the current status, happy to reopen. 

Thank you

**Pull request closed without merging**
