### PR TITLE
Add permissions to deploy javax-servlet.

### PR DESCRIPTION
**Pull request by jtnord**
Allow permissions for teilo to deploy a dummy version of the servlet-api.

# Description

Allow teilo to deploy a dummy version of the serlvet-api.  The servlet-api since version 3 has been published under a different `artifactId`.  This means it is possible to get 2 different versions of the API in the classpath of plugins causing build time issues.

Ref: https://github.com/jenkinsci/jenkins/pull/3033/files#diff-600376dffeb79835ede4a0b285078036R241

# Submitter checklist for changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

Not applicable - there is no repo for this.  Just a simple [POM](https://repo.jenkins-ci.org/snapshots/javax/servlet/servlet-api/0-SNAPSHOT/servlet-api-0-20170921.162448-2.pom)

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Wouldn't checkUpperBounds have something to say about this? IIUC the idea is for plugins to depend on "fake 2.5" so they effectively only get 3.x?

**Comment by daniel-beck** [comment]
Pinging the other reviewers, @oleg-nenashev @batmat @orrc for FYI.

Unless someone objects I'll merge by Monday.

**Comment by jtnord** [comment]
@daniel-beck well we can either exclude this from upper bounds (if I deploy version `0`), or I can deploy it with version `999-empty`...
@stephenc was the original proposer of this way handling things.

**Comment by batmat** [comment]
Should we also add an enforcer rule to ban it in plugin-pom?

**Comment by jtnord** [comment]
@batmat 

> Should we also add an enforcer rule to ban it in plugin-pom?

Given the plugin pom targets lots of versions of Jenkins we can not do this

**Comment by daniel-beck** [comment]
I think the rest of this discussion should be had on related core PRs etc.

**Pull request merged**
