### PR TITLE
Add new users for azure-publishersettings-credentials plugin.

### PR DESCRIPTION
**Pull request by markawm**
# Description
Added new users for azure-publishersettings-credentials plugin - https://github.com/jenkinsci/azure-publishersettings-credentials-plugin/

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

cc @ndeloof @batmat

### CODE REVIEW

**Comment by markawm** [comment]
Build failed because my username (markwm) isn't known to Artifactory... but I had previously logged into Artifactory ok with it. 🤷‍♀️ 
image

**Comment by daniel-beck** [comment]
@ndeloof has asked me a while back to mark the plugin for adoption (which I've completely missed 😦). So this plugin can be considered to not have an owner.

**Comment by oleg-nenashev** [comment]
I confirm the discussion between @daniel-beck and @ndeloof . In this discussion Nicolas permitted a release of the plugin and permitted marking the plugin for adoption. Although it has not been marked for adoption, this permission transfer can be performed IMO

**Comment by batmat** [comment]
```
[23:50] <+     batmat> | jenkins-admin: yo ol' friend
[23:50] <@jenkins-adm> | Wut?
[23:50] <+     batmat> | jenkins-admin: sigh, seems like an asymetrical relationship, like I think you're a friend, and you keep doing like you don't know me, really
[23:50] <@jenkins-adm> | Wut?
[23:51] <@ danielbeck> | you're on a roll
[23:51] <+     batmat> | jenkins-admin: anyway, ok, do as you wish
[23:51] <@jenkins-adm> | I didn't understand the command
[23:51] <@ danielbeck> | should have quit after 2, that was great
[23:51] <+     batmat> | jenkins-admin: I'm feeling lucky
[23:51] <@jenkins-adm> | I didn't understand the command
[23:52] <+     batmat> | jenkins-admin: make batmat committer on azure-publishersettings-credentials-plugin
[23:52] <@jenkins-adm> | Added batmat as a GitHub committer for repository azure-publishersettings-credentials-plugin
[23:52] <+     batmat> | jenkins-admin: make markawm committer on azure-publishersettings-credentials-plugin
[23:52] <@jenkins-adm> | Added markawm as a GitHub committer for repository azure-publishersettings-credentials-plugin
[23:52] <+     batmat> | context for ^^^ https://github.com/jenkins-infra/repository-permissions-updater/pull/1037/files
```

**Comment by batmat** [comment]
I mean, two `Wut?` was to be stored. To be marked with a :tombstone: if you will :trollface:

**Pull request merged**
