### PR TITLE
Enabling CD and adding security contacts for gcp-java-sdk-plugin

### PR DESCRIPTION
**Pull request by aneveux**
# Link to GitHub repository

https://github.com/jenkinsci/gcp-java-sdk-plugin

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

CD should be already enabled in my plugin, I followed the documentation before being hosted on `jenkinsci` not knowing I should have done that afterwards.

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [x] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
I assume you have more paths than that, and each one of those needs cd.enabled set?

based on looking at https://github.com/jenkinsci/gcp-java-sdk-plugin/tree/master 

the other 2 modules

**Comment by aneveux** [comment]
Oh you are right, I totally missed that.

Thanks a lot for the good catch :heart:

**Comment by aneveux** [comment]
Pinging @Wadeck here as I added the Security Contacts.

**Comment by aneveux** [comment]
@timja I used a wildcard path simiarly to what is done in the `aws-sdk` plugin.

This plugin is just an API plugin that does not contain any source code but simply serves GCP dependencies to other plugins requiring them, there are no "per-plugin maintainers" per se, as each plugin is just a `pom.xml` with specific dependencies.

Is that OK to keep it like this, consistent with the `aws-sdk` or do you prefer that I create one file per plugin?

**Comment by timja** [comment]
> @timja I used a wildcard path simiarly to what is done in the `aws-sdk` plugin.
> 
> This plugin is just an API plugin that does not contain any source code but simply serves GCP dependencies to other plugins requiring them, there are no "per-plugin maintainers" per se, as each plugin is just a `pom.xml` with specific dependencies.
> 
> Is that OK to keep it like this, consistent with the `aws-sdk` or do you prefer that I create one file per plugin?

it's fine, but if someone views one of them on plugin site maintainers will be empty, you can always change it later if you want.

**Comment by timja** [comment]
> @timja I used a wildcard path simiarly to what is done in the `aws-sdk` plugin.
> 
> This plugin is just an API plugin that does not contain any source code but simply serves GCP dependencies to other plugins requiring them, there are no "per-plugin maintainers" per se, as each plugin is just a `pom.xml` with specific dependencies.
> 
> Is that OK to keep it like this, consistent with the `aws-sdk` or do you prefer that I create one file per plugin?

noting https://github.com/jenkins-infra/repository-permissions-updater/issues/2911

**Pull request merged**
