### PR TITLE
Use ant matcher for artifactory path in bom

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkins-infra/repository-permissions-updater/pull/1937#issuecomment-827440676

@jetersen @daniel-beck @jglick

### CODE REVIEW

**Comment by daniel-beck** [comment]
Oh, that looks nice. If I don't have validation against this, it should work. I recommend reviewing the generated payload for any transformation issues, but otherwise 👍

**Comment by timja** [comment]
> Oh, that looks nice. If I don't have validation against this, it should work. I recommend reviewing the generated payload for any transformation issues, but otherwise 👍

let's give it a go, can easily revert it

**Comment by daniel-beck** [comment]
This changes `github.index.json`. Do we use that for incrementals for the bom?

**Comment by timja** [comment]
> This changes `github.index.json`. Do we use that for incrementals for the bom?

Yes, may need adapting there, don't know that anyone actually uses incremental bom builds though, @jglick?

**Comment by jglick** [comment]
Cannot recall offhand if https://github.com/jenkins-infra/incrementals-publisher/blob/00be8881121de3bb26ba91605aafedeecbba7435/lib/permissions.js relies on this field. I would recommend reverting this.

**Comment by timja** [comment]
why?

**Comment by jglick** [comment]
Could break incremental deployment at least of this component, which we want to enable.

**Comment by timja** [comment]
I'll fix forward if required, I was able to do a release with this config ^^,

https://github.com/jenkinsci/bom/pull/498

**Comment by jetersen** [comment]
@timja https://github.com/jenkins-infra/incrementals-publisher/blob/00be8881121de3bb26ba91605aafedeecbba7435/lib/permissions.js#L19 this line would require fixing, if I am reading the code correctly 😅

**Comment by jglick** [comment]
Rather https://github.com/jenkins-infra/incrementals-publisher/blob/00be8881121de3bb26ba91605aafedeecbba7435/lib/permissions.js#L30 looks like it would break against

```json
    "jenkinsci/bom": [
        "io/jenkins/tools/bom/bom-*"
    ],
```

**Comment by jetersen** [comment]
@jglick right I simply cannot read 🙈

**Comment by timja** [comment]
Well bom builds themselves keep flaking out but I did a PR anyway as a unit test showed it wouldn't work:
https://github.com/jenkins-infra/incrementals-publisher/pull/16

**Comment by jetersen** [comment]
@timja so this https://github.com/jenkins-infra/incrementals-publisher/releases/tag/v1.4.0 fixes the incrementals publisher on Jenkins CI right?

**Comment by timja** [comment]
Yes it did and 👍

**Pull request merged**
