### PR TITLE
request upload permission for ftp-rename plugin

### PR DESCRIPTION
**Pull request by brunocantisano**
request upload permission for ftp rename plugin #301

GitHub Link:
https://github.com/jenkinsci/ftp-rename-plugin

Jenkins Wiki Link:
https://wiki.jenkins-ci.org/display/JENKINS/Ftp+Rename+Plugin

# Description

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
https://issues.jenkins-ci.org/browse/HOSTING-301

**Comment by daniel-beck** [comment]
Needs initial login as described in this repository's readme.

**Comment by brunocantisano** [comment]
after this can I release the plugin or should I have any other step?

**Comment by daniel-beck** [comment]
@brunocantisano Should work now. If it does not see https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Workingaroundcommonissues

**Pull request merged**
