### PR TITLE
Add Malena and Markas developers of sonarqube plugin

### PR DESCRIPTION
**Pull request by tomverin**
# Description

Adding @malena-ebert-sonarsource and @mark-rekveld-sonarsource as uploaders to the sonarqube plugin https://github.com/SonarSource/jenkins-sonar-plugin from @tomverin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by timja** [comment]
> Exception in thread "main" java.lang.IllegalStateException: User name not known to Artifactory: maeb

**Comment by malena-ebert-sonarsource** [comment]
> > Exception in thread "main" java.lang.IllegalStateException: User name not known to Artifactory: maeb

I logged in.

**Review by timja — APPROVED** [review]

**Comment by mark-rekveld-sonarsource** [comment]
@timja I just tried to push to the jenkinsci/sonarqube-plugin repository but it failed with a no permissions error. Is there something I need to do on my end to complete the permissions setup?

**Comment by MarkEWaite** [comment]
We may need help from @slide on this one.  I believe there are diagnosis steps to identify the source of a failure (incorrect settings.xml, incorrect password, etc.), but I didn't find them on my first search.  I assume that you've already logged into repos.jenkins-ci.org per the [release permissions](https://www.jenkins.io/doc/developer/plugin-governance/managing-permissions/#release-permissions) instructions.

**Comment by mark-rekveld-sonarsource** [comment]
Hi @MarkEWaite yeah I can login on repos.jenkins-ci.org Was needed for this PR that triggered me to get a new password.
. One thing to note is that the repos.jenkins-ci.org username is `markrekveld` and for github its `mark-rekveld-sonarsource`. There is also a github account with username `markrekveld` but this is my personal account that doesn't have commit access to the sonarsource repos. Could this be the cause of the issue?

**Comment by slide** [comment]
What is the github repo for this plugin in the jenkinsci org?

**Comment by mark-rekveld-sonarsource** [comment]
sonarqube-plugin

**Comment by slide** [comment]
FYI, this repo is not for github permissions, this is just for the ability to release the plugin to the Jenkins Artifactory and update center. Github permissions are managed separately. I added both users to the developers team for the plugin, so you should be able to push to the repo. 

I'm curious why the repo is named sonarqube-plugin, but the artifactId is sonar. We generally have a requirement that the repo name match with the artifactId. The repo should be sonar-plugin, or the artifactId should be sonarqube. DO NOT change the artifactId to sonarqube, it would be better to rename the repo. Just curious how that happened.

**Comment by mark-rekveld-sonarsource** [comment]
Thanks for the fix I can push to the repo now.

I'm not sure why the naming of the repo and the plugin are not in line with the Jenkins team guidelines.
This far before my time, but maybe @tomverin, @julienlancelot, @henryju know why.

**Comment by slide** [comment]
Glad it is working for you now.

**Pull request merged**
