### PR TITLE
Add jaxb permission file

### PR DESCRIPTION
**Pull request by batmat**
# Description

This PR is a special one: it creates a permission file for https://github.com/jenkinsci/jaxb-plugin that got created directly by @kohsuke in the context of Java 11 testing.
I already got commit access to that repository.

My only goal here is to enable Incremental releases, which I believe is requiring the `github` field. That is why there's no developers specified to be allowed to release.

Thanks!

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- ~Add link to resolved HOSTING issue in description above~ N/A

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

cc @jenkins-infra/java11-support

### CODE REVIEW

**Comment by batmat** [comment]
Cf. https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fjaxb-plugin/detail/master/2/pipeline, goal is to have the Incrementals deployment be successful.

Currently failing as:

image

**Comment by oleg-nenashev** [comment]
Formally it needs authorization from @kohsuke 
But I have no strong opinion in this case

**Comment by batmat** [comment]
@oleg-nenashev I think we do not absolutely need @kohsuke approval in this very case, though for sure it would be better/cleaner, for at least the following reasons:
* I think I remember a dev list thread, but can't find it just now, where Kohsuke already stated that anyone should feel free to take over maintainership because he didn't consider himself anymore an active maintainer of any plugin
* that plugin is still in a very early stage, has never been released yet, and was created solely to see how Jenkins could support JAXB once on Java 11. 
   * As you and I are members of the @jenkins-infra/java11-support team, taking over this does seem to make sense
* Given Kohsuke has not committed in that repo since June 2018, I suppose anyway we could on top of everything consider it abandoned.

Again, I agree it would be cleaner to have his approval confirmed. But I think we could move forward because I suppose he would trust us to not do something evil in such case.

**Comment by oleg-nenashev** [comment]
Thanks @kohsuke !

**Pull request merged**
