### PR TITLE
Add Jens Thielscher as maintainer of nomad-plugin

### PR DESCRIPTION
**Pull request by multani**
# Description

@j3t has been making several valuable changes on the [Nomad plugin](https://github.com/jenkinsci/nomad-plugin) in the past few months.

The plugin lacks active maintainers and he could help to bring new features and improvements.

I'm currently one of the active maintainer of that plugin.

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name @j3t 
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions) @j3t 

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by multani** [comment]
Settings this as a draft pull request, until Jens shares his Artifactory username.

**Comment by multani** [comment]
Is it possible to retrigger the checks? Apparently, closing and reopening doesn't :thinking:

**Comment by halkeye** [comment]
I thought it re-ran on a cron, but we re-run after someone says they've logged in, so its now green.

**Comment by halkeye** [comment]
github permissions given
merging

**Comment by multani** [comment]
@halkeye Should the [`nomad-plugin-developers` team](https://github.com/orgs/jenkinsci/teams/nomad-plugin-developers) match the content of this configuration file actually?

**Comment by halkeye** [comment]
This file controls who can release. It's LDAP not GitHub usernames. Commit access is still kinda manual and sometimes different than release access.

I've been distracted lately but working on adding commit to this file - https://community.jenkins.io/t/codify-github-access/799 but it'll be a while yet.

Is that what you meant?

**Comment by multani** [comment]
> I've been distracted lately but working on adding commit to this file - https://community.jenkins.io/t/codify-github-access/799 but it'll be a while yet.

Yes, that's what I was talking about, thanks for the pointer, that will be great if you manage to move this forward :+1: 

I added Jens in GitHub directly, it should be all good now, thanks again for the help!

**Comment by halkeye** [comment]
I added them to the team, so they should be added as soon as they join the org. The team is nice cause you can use it for CODEOWNERS / mentions without updating everything.

**Pull request merged**
