### PR TITLE
Add myself in the jenkinswalldisplay dev team to release the plugin

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by daniel-beck** [comment]
@pellepelster This would grant permission to release the Wall Display Plugin to Arnaud (e.g. to properly publish 0.6.33 [based on the new plugin parent](https://github.com/jenkinsci/walldisplay-plugin/pull/46)). Please let us know whether you approve.

**Comment by daniel-beck** [comment]
@pellepelster Ping.

**Comment by pellepelster** [comment]
sorry i was afk for a few days will do the release asap

**Comment by aheritier** [comment]
perfect @pellepelster Thx a lot

**Pull request closed without merging**
