### PR TITLE
Request to be a maintainer/owner using Jenkins ID.

### PR DESCRIPTION
**Pull request by MatthewQueenan**
Request to be a maintainer/owner using Jenkins ID. 

Link to plugin: https://github.com/jenkinsci/vectorcast-execution-plugin

@chris-overend  and @richardmkeeble are aware of this request.

# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by batmat** [comment]
Please check the right boxes. Maybe you thought we put this PR template up just for the fun ;-)? Also this is duplicated with #985, closing here.

**Comment by batmat** [comment]
My bad, it's another plugin.

So please check the right boxes...

**Comment by batmat** [comment]
`Exception in thread "main" java.lang.IllegalStateException: User name not known to Artifactory: MatthewQueenan`

I see you checked the boxes above. Did you **actually** do the checks associated to each line? Thanks

**Comment by MatthewQueenan** [comment]
Accidentally used the wrong username. Username should be "matthew_queenan".

**Comment by batmat** [comment]
@MatthewQueenan so do you plan to fix this?

**Pull request closed without merging**
