### PR TITLE
Add myself to authorized BigPanda developers

### PR DESCRIPTION
**Pull request by WaffleStudios**
# Description

I (@WaffleStudios) performed development on the [BigPanda Jenkins plugin](https://github.com/jenkinsci/bigpanda-plugin) and now need to be authorized to publish the update.

Approved by @julioguereca 

# Submitter checklist for adding or changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by halkeye** [comment]
🤞 the existing maintainers are github users too
@erikzaadi
@jguereca

**Comment by halkeye** [comment]
@julioguereca

**Comment by julioguereca** [comment]
Hi! Yes, I am confirming we want to add @WaffleStudios as a maintainer as well

**Comment by WaffleStudios** [comment]
I've logged into Jira for the first time 👍  @halkeye

**Comment by halkeye** [comment]
It takes up to an hour for the data to propefate so I'll re run it in a bit

**Comment by halkeye** [comment]
Make sure you accept the invite from https://github.com/jenkinsci

**Pull request merged**
