### PR TITLE
PR to request neccessary permissions

### PR DESCRIPTION
**Pull request by ugurkany**
# Description

Requested PR to request necessary permissions to publish new versions of the Amazon ECS Plugin for Jenkins.

Relevant feature PR : https://github.com/jenkinsci/amazon-ecs-plugin/pull/274
Github Repository : https://github.com/jenkinsci/amazon-ecs-plugin
Existing Maintainers : @webratz @pgarbe @markyjackson-taulia @Stericson 
Github Account to be given Repo access : @ugurkany

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by Stericson** [comment]
Not sure I would endorse adding @ugurkany at this time for a PR opened 2 days ago.

**Comment by halkeye** [comment]
The plugin is up for adoption..

**Comment by halkeye** [comment]
> Not sure I would endorse adding @ugurkany at this time for a PR opened 2 days ago.

@Stericson if you are not comfortable with @ugurkany having release privs. I would recommend removing the adopt me label from the repo, right now the plugin allows for anyone who wants to take ownership to take ownership.

I'm re-running the build because ugurkany shows up in https://reports.jenkins.io/artifactory-ldap-users-report.json now

**Comment by ugurkany** [comment]
@Stericson, I don't understand how the opening date of PR affects this decision. There is no information about that. Like  @halkeye said, the plugin is on the adoption status

**Comment by Stericson** [comment]
My concern was primarily based on the following 

1. Usually, people want to become a contributor after many contributions to the project or because nothing is moving forward in the project. In this case, PRs are being addressed and, as far as I've seen this is your first contribution to the project.

2. Disregarding the above, I'd like to see some kind of activity in a users GitHub history if I'm going to endorse or support someone I don't know coming on as a contributor. In the last few years, you have not really contributed much from what little I can see.

Granted, the above are opinions based on my limited view/insight. But, it still stands that I don't feel comfortable recommending that you be added as a contributor from what little I know.

With all of that being said, the point that the project is still up for adoption, something I have personally been hesitant to remove, is a fair point and should be considered.

Thanks,
Stephen

**Comment by timja** [comment]
Hi @Stericson 

Basically up for adoption means that the plugin can be transferred at any time.

If you are hesitant to allow adoption without knowing more about the person then the label should be removed, you can always add more maintainer if people steps up / transfer without it being up for adoption

**Comment by ugurkany** [comment]
@Stericson, I agree with you about your concern. So it is your choice then, but I am disposed to contribute to this plugin. I will open a few more PR in the upcoming month.

**Comment by halkeye** [comment]
As I've given every oppertunity to dismiss the adopt me label, and all procedures have been followed. I'm going to merge this and grant access.

It doesn't matter if someone has a public history of contributing to open source or not. That would be a form of gatekeeping. Many contributors only contribute at work because thats the time they have/are given.

**Comment by halkeye** [comment]
@ugurkany make sure you either accept the org invite via email, or goto https://github.com/jenkinsci/ and accept the org invite there.

**Comment by ugurkany** [comment]
@halkeye thank you for this opportunity.

**Pull request merged**
