### PR TITLE
Artifactory Groovy Script conversion

### PR DESCRIPTION
**Pull request by TheMeinerLP**
This PR converts the two last Groovy scripts and reworks the code in readability. The framework Reactor was integrated to allow more speed and parallel work. 

Many of the main parts have been split from the Updater class into smaller classes, moving the Updater class into a launcher package to separate start classes from other logic. 

Java 21 features such as sealed interfaces are now also used in the core to build a better API.

### CODE REVIEW

**Comment by TheMeinerLP** [comment]
Waiting for #3936 get merged

**Review by timja — COMMENTED** [review]
looks ok from what I can see, one nit, have you tested this in some way?

**Review by timja — COMMENTED** [review]
looks ok from what I can see, one nit, have you tested this in some way?

**Comment by TheMeinerLP** [comment]
> looks ok from what I can see, one nit, have you tested this in some way?

I would compare the json files of the master and my branch, there should be no differences. I would consider it valid

**Comment by timja** [comment]
@daniel-beck do you want to check this one?

**Comment by daniel-beck** [comment]
@timja Thanks for the ping. I remember test coverage wasn't great when I built this (anything?) so how well has this been tested? Any schedule for merge?

**Comment by timja** [comment]
> @timja Thanks for the ping. I remember test coverage wasn't great when I built this (anything?) so how well has this been tested? Any schedule for merge?

No test coverage that I can tell.
No testing done that I'm aware of, JSON files mentioned here aren't really applicable I think as this is about applying permissions: https://github.com/jenkins-infra/repository-permissions-updater/pull/3938#issuecomment-2247816113

Schedule for merge no not really although this is done as part of GSOC I believe so @NotMyFault or @TheMeinerLP may be able to comment.

**Comment by NotMyFault** [comment]
> > @timja Thanks for the ping. I remember test coverage wasn't great when I built this (anything?) so how well has this been tested? Any schedule for merge?
> 
> No test coverage that I can tell. No testing done that I'm aware of, JSON files mentioned here aren't really applicable I think as this is about applying permissions: [#3938 (comment)](https://github.com/jenkins-infra/repository-permissions-updater/pull/3938#issuecomment-2247816113)
> 
> Schedule for merge no not really although this is done as part of GSOC I believe so @NotMyFault or @TheMeinerLP may be able to comment.

Test coverage does not exist (yet), but in case somethings breaks, we can always revert

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
