### PR TITLE
Create plugin-cloudshell-sandbox.yml

### PR DESCRIPTION
**Pull request by TomerAdmon**
# Description

Adding new plugin to the list.

The CloudShell Sandbox Jenkins Plugin provides an easy way to consume CloudShell sandboxes through Jenkins for a variety of use cases. The plugin allows you to build jobs that create on demand sandboxes in CloudShell based on pre-defined blueprints.

CloudShell Sandbox Plugin:
https://github.com/jenkinsci/cloudshell-sandbox-plugin

HOSTING issue:
https://issues.jenkins-ci.org/browse/HOSTING-418

# Submitter checklist for changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [X] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [X] Make sure the file is created in `permissions/` directory
- [X] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [X] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [X] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please complete the checklist. Thanks!

**Comment by TomerAdmon** [comment]
@daniel-beck  - Thanks for the quick response. Updated all requested information 👍

**Comment by TomerAdmon** [comment]
Hi @daniel-beck  :-) 
Thanks for the help.

Quick question: how do I verify that my permissions are not valid and i can upload the plugin?
Do i need to execute anything to achieve that?
At the moment it seems like when i'm trying to release my plugin to https://repo.jenkins-ci.org/releases i'm getting an "Unauthorized" error message...

Thanks!

**Comment by daniel-beck** [comment]
> Unauthorized

HTTP 401 ≠ HTTP 403, so that is unrelated. Responded in the hosting issue if that was you.

**Pull request merged**
