### PR TITLE
Allow rahulsom to adopt cctray-xml

### PR DESCRIPTION
**Pull request by rahulsom**
The maintainer has marked the plugin as up for adoption. It needs some fixes to work with 2.346.x. I intend to get this going.

https://github.com/jenkinsci/cctray-xml-plugin/ is the plugin
@daniel-beck was the previous maintainer and has expressed that the way forward to get changes in is to adopt it - https://github.com/jenkinsci/cctray-xml-plugin/pull/5#issuecomment-1195741234

# Description

Adopt cctray-xml plugin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks for taking care of this plugin!

**Review by MarkEWaite — APPROVED** [review]

**Comment by rahulsom** [comment]
I seem to have logged in without trouble before I opened the PR.

<details>
  <summary>Screenshot</summary>
  
image
</details>

Is there something else I need to have done?

**Comment by daniel-beck** [comment]
Patience. This syncs roughly hourly.

**Comment by halkeye** [comment]
Approved. 

Make sure you accept the github invite or goto https://github.com/jenkinsci/ and accept it there

**Comment by rahulsom** [comment]
Thanks! @halkeye @daniel-beck @MarkEWaite

**Pull request merged**
