### PR TITLE
Create plugin-cavisson-ns-nd-integration-plugin.yml

### PR DESCRIPTION
**Pull request by cavissonsystems**
# Description

### Link to resolved HOSTING issue : https://issues.jenkins.io/browse/HOSTING-794

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by anupreet19 — APPROVED** [review]
Approval for changing permissions for cavisson-ns-nd-integration plugin

**Comment by slide** [comment]
Please fill out the full PR template, which includes links to the hosting request in Jira and so forth.

**Comment by cavissonsystems** [comment]
I've filled the PR template and have mentioned the link to plugin Git repository and link to resolved HOSTING issue.

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by slide** [comment]
The link to the hosting issue is incorrect. Please put in the link to the HOSTING issue for your plugin.

**Comment by cavissonsystems** [comment]
Updated the HOSTING issue link

**Pull request merged**
