### PR TITLE
add developer to neuvector-vulnerability-scanner-plugin

### PR DESCRIPTION
**Pull request by songlongcn**
# Description
https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin
@neuvector

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Maintainer checklist (not for requesters!)

- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by slide** [comment]
Please \@ an existing maintainer (as it mentioned in the pr template) for their permission.

**Comment by slide** [comment]
Also, please fill out the check boxes as requested in the PR template.

**Comment by songlongcn** [comment]
> Please @ an existing maintainer (as it mentioned in the pr template) for their permission.
added Git repo link;
added @neuvector maintainer

**Comment by slide** [comment]
```
User name not known to Artifactory: songlongcn
```

Please make sure this is the username you use to login to Jenkins Jira and Jenkins Artifactory.

**Comment by songlongcn** [comment]
> ```
> User name not known to Artifactory: songlongcn
> ```
> 
> Please make sure this is the username you use to login to Jenkins Jira and Jenkins Artifactory.

songlongcn is the developer's github account. "neuvector" is the username we used to login Jenkins Jira and Artifactory. How to add songlongcn to be a user that can login Jenkins Artifactory ?

**Comment by slide** [comment]
That user would need to create an account in the Jenkins infra.

**Comment by songlongcn** [comment]
> That user would need to create an account in the Jenkins infra.

songlongcn has been added in the permissions/plugin-neuvector-vulnerabbility-scanner.yml
Please let me know if there is something else that I need to do to create "songlongcn" account in the Jenkins infra.

**Comment by songlongcn** [comment]
> You should not be changing this file at all.

reverted the change

**Comment by slide** [comment]
I'm going to close this one out, please submit a new PR. I want to make sure none of the changes to pom.xml are even possibly in a PR.

**Pull request closed without merging**
