### PR TITLE
Enable CD Permissions

### PR DESCRIPTION
**Pull request by danielomoto**
# Description

Repository: https://github.com/jenkinsci/add-changes-to-build-changelog-plugin
PR: https://github.com/danielomoto/add-changes-to-build-changelog-plugin/pull/1

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [x] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
> PR: https://github.com/jenkins-infra/repository-permissions-updater/pull/3150

You are supposed to link to the PR where you enable CD in your plugin.

**Comment by danielomoto** [comment]
Hi @NotMyFault,

Thanks for that pointer.  I knew something was off, but must have gotten confused while following the steps.  I updated the request with the pull request containing the required changes.

**Comment by NotMyFault** [comment]
Btw, you selected the wrong target branch. Pull requests should target, https://github.com/jenkinsci/add-changes-to-build-changelog-plugin, not https://github.com/danielomoto/add-changes-to-build-changelog-plugin.

In fact, you can delete https://github.com/danielomoto/add-changes-to-build-changelog-plugin, the jenkinsci organization is the new home of the repository, from where it's distributed.

**Comment by danielomoto** [comment]
Hi @NotMyFault ,

Thanks again for all the help!

So, I reread the documentation and it seems like I messed this pull request up. :( I did get my repos mixed up and updated the jenkinsci/add-changes-to-build-changelog-plugin directly without going through a pull request.  In this case, what should I do?  Should I revert that change and redo it using a feature branch/pull request/merge?  Would that satisfy the requirement?

**Comment by NotMyFault** [comment]
You can create a new PR towards the repository hosted in the jenkinsci org. No worries!

**Review by NotMyFault — APPROVED** [review]

**Comment by danielomoto** [comment]
Hi @NotMyFault,

Thanks for the merge!

**Pull request merged**
