### PR TITLE
Adopt keycloak plugin.

### PR DESCRIPTION
**Pull request by mrmateo**
# Description

Adopt https://github.com/jenkinsci/keycloak-plugin
Plugin is marked as 'adopt-this-plugin' and has unresolved security issues that I would like to fix and release.

From https://github.com/jenkins-infra/update-center2/pull/678 the Jenkins team was notified by the previous maintainer that they would not maintain it anymore.

I understand any security issues will need to be fixed before this plugin can be published via the plugins tool.

# Submitter checklist for adding or changing permissions

### Always

- [X] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [X] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by mrmateo** [comment]
Conversation was added to Jenkins Developers group with details required from https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/ , will add link to the conversation when it shows up (looks like new members have messages held for moderation).

**Comment by NotMyFault** [comment]
You will need to revert https://github.com/jenkins-infra/update-center2/pull/678 to restore distribution of the plugin.

**Comment by mrmateo** [comment]
@NotMyFault - should I wait until there are fixes for the outstanding security issues before putting in a PR to revert that?

**Comment by NotMyFault** [comment]
> @NotMyFault - should I wait until there are fixes for the outstanding security issues before putting in a PR to revert that?

If you want to adopt the plugin, you need to restore the open security issues yourself, before restoring the distribution. My previous comment was just a pointer, given not every plugin, that's up for adoption, is suspended.

**Comment by NotMyFault** [comment]
>  I have fixes for the two security issues ready.

That's awesome! Commonly, we like to see a few contributions of new contributors, who are interested in stepping up, before granting them access to a plugin.
I went ahead and unarchived the repository, allowing you to contribute your changes 🙏

**Comment by mrmateo** [comment]
> > I have fixes for the two security issues ready.
> 
> That's awesome! Commonly, we like to see a few contributions of new contributors, who are interested in stepping up, before granting them access to a plugin. I went ahead and unarchived the repository, allowing you to contribute your changes 🙏

Thank you! I added the PRs.

**Review by NotMyFault — APPROVED** [review]

**Comment by NotMyFault** [comment]
> > > I have fixes for the two security issues ready.
> > 
> > 
> > That's awesome! Commonly, we like to see a few contributions of new contributors, who are interested in stepping up, before granting them access to a plugin. I went ahead and unarchived the repository, allowing you to contribute your changes 🙏
> 
> Thank you! I added the PRs.

Thanks. To be added to the issues on Jira and update the security warnings on the Jenkins update center, please make sure to [notify](https://www.jenkins.io/security/cna/) the security team about the update.

**Pull request merged**
