### PR TITLE
Add new members for plugin-autify

### PR DESCRIPTION
**Pull request by riywo**
# Description

Add new members for maintaining Autify Plugin: https://github.com/jenkinsci/autify-plugin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)

- [ ] Add a link to the pull request, which enables continous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
    - Current maintainer - @riywo 
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
    - @4ydx
    - @hgsgtk
    - @mtsmfm
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by riywo** [comment]
hgsgtk just loged in but rerun failed. https://issues.jenkins.io/secure/ViewProfile.jspa?name=hgsgtk

I'll retry tomorrow in case there are some eventual consistencies.

**Comment by slide** [comment]
mtsmfm needs to login to artifactory

**Comment by mtsmfm** [comment]
Ah sorry, I only logged to Jira 🙇 
I've loggein to Artifactory now, can you run again?

**Review by NotMyFault — APPROVED** [review]

**Comment by mtsmfm** [comment]
@slide @NotMyFault For some reason I still doesn't receive an invitation for the GitHub team which mantains https://github.com/jenkinsci/autify-plugin. Can I ask you to invite me again? 🙏

**Comment by NotMyFault** [comment]
> @slide @NotMyFault For some reason I still doesn't receive an invitation for the GitHub team which mantains https://github.com/jenkinsci/autify-plugin. Can I ask you to invite me again? 🙏
> 
> I think team name is autify-plugin Developers

I resend the invite. GitHub invites are only valid for 7 days.

**Comment by mtsmfm** [comment]
@NotMyFault Thanks, now I got an invitaiton email!

**Pull request merged**
