### PR TITLE
granting access for adopted plugin

### PR DESCRIPTION
**Pull request by michaelneale**
AS per discussion here: 

https://groups.google.com/forum/#!topic/jenkinsci-dev/KmgkVuHKD7U

cc @daniel-beck @rtyler

### CODE REVIEW

**Comment by michaelneale** [comment]
Failure is due to some post build step: 

```
GitHub has been notified of this commit’s build result

org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: artifactoryAdmin
	at org.jenkinsci.plugins.credentialsbinding.MultiBinding.getCredentials(MultiBinding.java:124)
	at org.jenkinsci.plugins.credentialsbinding.impl.UsernamePasswordMultiBinding.bind(UsernamePasswordMultiBinding.java:68)
	at org.jenkinsci.plugins.credentialsbinding.impl.BindingStep$Execution.start(BindingStep.java:92)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:184)
```

but passes otherwise

**Comment by daniel-beck** [comment]
@michaelneale The joys of GitHub org folder building PRs for a repo set up to only be a single-branch Pipeline…

**Comment by daniel-beck** [comment]
@i386 Okay if Michael also has the upload permission?

**Comment by i386** [comment]
@daniel-beck yes absolutely 👍

**Pull request merged**
