### PR TITLE
Create plugin-easyqa

### PR DESCRIPTION
**Pull request by yana-gusti**
Initial set of permissions based on plugin uploads

# Description

Link to plugin Git repository
[https://github.com/jenkinsci/easyqa-plugin](https://github.com/jenkinsci/easyqa-plugin)

Link to resolved HOSTING issue
https://issues.jenkins-ci.org/browse/HOSTING-348

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@yana-gusti The checklist is for you to actually do as required for a hosting request. Please review all of it. There's at least four items you ignored.

**Comment by yana-gusti** [comment]
@daniel-beck I have tried to fix all requirements. Please, check

**Comment by daniel-beck** [comment]
@yana-gusti No file name extension, no `---` prefix inside the file (unsure whether needed, but all other files have that). The path entry `org/jenkins-ci/plugins/easyqa` is not needed.

**Comment by yana-gusti** [comment]
@daniel-beck I have fixed. Please, check. Thank you.

**Pull request merged**
