### PR TITLE
Add NotMyFault to favorite-view

### PR DESCRIPTION
**Pull request by NotMyFault**
# Description

# Submitter checklist for adding or changing permissions

https://github.com/jenkinsci/favorite-view-plugin

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by halkeye** [comment]
So i know this plugin hasn't been updated since 2012, which to me means abandoned, but officially we need to go through the process. Can you post to the mailing list and see if there's any objections?

**Comment by NotMyFault** [comment]
I can do that if it's a hard requirement to make this PR eligible for a merge, but that was no blocker for previous abandoned plugins I took over.

I'm currently addressing the outstanding broken icons, which we left intentionally untouched earlier this year, if a plugin is abandoned. Sending a mail for each inevitably slows down the process more than needed, especially if a plugin has no maintainers 🤷🏻

**Comment by halkeye** [comment]
I'm not going to make you wait 2 weeks, but I don't want it to be hidden in github PRs only. Just more of an FYI type thing.

If its "adopt-this-plugin" label is applied, its super easy to take over and i'll just approve it. But lack of label I want documented tis all.

**Comment by MarkEWaite** [comment]
Since there are no developers listed with repository permissions, I think that makes it a "de-facto" plugin for adoption.  I'm +1 for this adoption request.

**Comment by halkeye** [comment]
> Since there are no developers listed with repository permissions, I think that makes it a "de-facto" plugin for adoption.

thats not a scenario listed on https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

If you want to propose that change, i'd start with a mailing list topic and a vote in governance on monday.

**Comment by timja** [comment]
> So i know this plugin hasn't been updated since 2012, which to me means abandoned, but officially we need to go through the process. Can you post to the mailing list and see if there's any objections?

There are no maintainers of this plugin currently, 0 people have access to it on GitHub.

In that case we would normally mark it for adoption but given we have an adoption request here would normally proceed.

There's been a number of these for the broken icon plugins that have zero maintainers listed.

**Comment by halkeye** [comment]
> There's been a number of these for the broken icon plugins that have zero maintainers listed.

Then lets get the doc updated so its normal procedure instead of undocumented exception

**Comment by timja** [comment]
> > There's been a number of these for the broken icon plugins that have zero maintainers listed.
> 
> Then lets get the doc updated so its normal procedure instead of undocumented exception

https://github.com/jenkins-infra/jenkins.io/pull/5416

**Pull request merged**
