### PR TITLE
add huangp and seanf as developer

### PR DESCRIPTION
**Pull request by huangp**
_(This PR template only applies to permission changes -- ignore for changes to the tool)_

# Description

huangp and seanf would like to have zanata-plugin upload permission. 
github repo for the plugin: https://github.com/jenkinsci/zanata-plugin
huangp commit history: https://github.com/jenkinsci/zanata-plugin/commits?author=huangp
seanf commit history: https://github.com/jenkinsci/zanata-plugin/commits?author=seanf

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by orrc** [comment]
Can you please go through the checklist?  In particular:

> Make sure to `@`mention an existing maintainer

Is there consent from the existing maintainer? You can ask them here, or link to a thread on the developers' mailing list, etc.

> All newly added users have logged in to Artifactory at least once

**Comment by daniel-beck** [comment]
Both users have logged in.

**Comment by huangp** [comment]
@yu-shao-gm Hi Shao, are you happy for Sean and I to become uploaders for the plugin? Thanks

**Comment by yu-shao-gm** [comment]
@huangp @seanf I am perfectly ok to have both of you as uploader.

**Pull request merged**
