### PR TITLE
Add issue forms (preparation for moving hosting to GitHub issues

### PR DESCRIPTION
**Pull request by timja**
See:

- https://github.com/timja/repository-permissions-updater/issues/new/choose
- https://github.com/timja/repository-permissions-updater/issues/1

Other forms are imported from https://github.com/jenkinsci/.github/tree/master/.github/ISSUE_TEMPLATE

### CODE REVIEW

**Comment by halkeye** [comment]
I'm not sure this repo needs documentation or feature request but looks good to me.

**Comment by halkeye** [comment]
actually at the moment, i think this repo should only get hosting requests as issues.

**Comment by timja** [comment]
> actually at the moment, i think this repo should only get hosting requests as issues.

there can be bugs/ feature requests, e.g. https://github.com/jenkins-infra/ircbot/issues/103

**Review by oleg-nenashev — APPROVED** [review]
nice!

**Pull request merged**
