### PR TITLE
Add Dev permission for escoem and MCardenas

### PR DESCRIPTION
**Pull request by MCardenasBlanco**
Requesting dev permission for Emilio Escobar and Manuel Cardenas as commented with @oleg-nenashev.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@MCardenasBlanco To clarify, this grants permission to _release_ to the Maven repo. GitHub commit permissions are separate.

**Comment by batmat** [comment]
LGTM :+1: waiting for @oleg-nenashev ack

**Comment by daniel-beck** [comment]
Probably better if @jglick or @stephenc approved as Oleg is unresponsive.

**Comment by oleg-nenashev** [comment]
I confirm there is an agreement to handover the ownership of the plugin. According to our discussion with @escoem and @MCardenasBlanco, the first steps for them will be to make several contributions to the plugin in order to study the Code base. This step does not actually require the release permission. I am fine with granting it, but IMHO it is not a blocker for the initial ramp-up

**Comment by daniel-beck** [comment]
> I am fine with granting it

There we go. Thanks @oleg-nenashev

**Pull request merged**
