### PR TITLE
update bearychat plugin developer

### PR DESCRIPTION
**Pull request by yuanbohan**
# Description

@otbzi @yuanbohan

jenkins bearychat plugin repo in BearyInnovative organization:
https://github.com/bearyinnovative/jenkins-bearychat-plugin

jenkins bearychat plugin repo in JenkinsCI organization:
https://github.com/jenkinsci/bearychat-plugin

**otbzi** has left BearyInnovative team, we have to update the uploader to be **yuanbohan**, the owner of [BearyInnovative](https://github.com/bearyinnovative). 

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by yuanbohan** [comment]
@orrc Can I ask how long it will take to transfer the permission? If there is something that I should supply, just let me know.

**Comment by daniel-beck** [comment]
@yuanbohan is a committer and GitHub repo admin, so the usual process in such cases is to allow the existing uploader (@otbzi) a few days to refuse upload permissions, after which they'll be granted by default. This handles the case in which there are multiple committers, but one user is the final authority on what gets released.

Of course @otbzi can also explicitly approve this request by leaving a comment, thereby speeding up the process.

**Comment by daniel-beck** [comment]
Confirmed user exists in Artifactory.

Notably this is one of the few requests actually removing uploaders, but the (unverified) explanation does make sense.

**Comment by yuanbohan** [comment]
@daniel-beck OK. And yuanbohan exists in [Artifactory](https://repo.jenkins-ci.org/webapp/#/home)

**Comment by otbzi** [comment]
I confirm this permission migration. thx

**Pull request merged**
