### PR TITLE
Update plugin-cobertura.yml

### PR DESCRIPTION
**Pull request by jeffpearce**
Adding self as developer per @christ66

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jeffpearce Could you please add link to the confirmation from @christ66 or to ask him to comment here?

**Comment by daniel-beck** [comment]
User doesn't exist or has never logged into Artifactory.

See PR checklist or this repo's readme for more information.

**Comment by jeffpearce** [comment]
@daniel-beck  - I logged into Artificatory - can you recheck the "needs initial login" ?

**Comment by daniel-beck** [comment]
@jeffpearce Still no such user. Wrong user name?

**Comment by jeffpearce** [comment]
@daniel-beck - i misunderstood something in the instructions. It should be there now.

**Pull request merged**
