### PR TITLE
Add sag47 as maintainer of pipeline multibranch defaults plugin

### PR DESCRIPTION
**Pull request by samrocketman**
# Description

* Plugin repository: https://github.com/jenkinsci/pipeline-multibranch-defaults-plugin

This is so that I can merge and release [a pull request][#3] in case the original maintainer does not reply.  The pipeline multibranch defaults plugin has not had any changes in two years so it is unlikely anybody supports it.

@vaimr please let me know if you still plan to maintain this plugin.  If not, I can take over maintaining and and performing releases.

[#3]: https://github.com/jenkinsci/pipeline-multibranch-defaults-plugin/pull/3

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by samrocketman** [comment]
@daniel-beck what's the grace period for a maintainer to comment authorization?  As noted in the description, this plugin has had no changes in 2 years and is likely abandoned.

**Comment by daniel-beck** [comment]
@samrocketman By convention, two weeks after reaching out to them via email cc the dev list. GitHub (or Jira) notifications are missed too easily).

**Comment by samrocketman** [comment]
I'll reach out to them via email.

**Comment by samrocketman** [comment]
On Aug 27, 2018 I reached out to [the maintainer email provided in `pom.xml`](https://github.com/jenkinsci/pipeline-multibranch-defaults-plugin/blob/0a28f2c7569bc07195f28d40ee87eff17aa96156/pom.xml#L52) and have not received a response.  Here's a quote of the email sent:

> ### Subject
> Maintainer for pipeline-multibranch-defaults-plugin
> ### Message body
> Hello Saponenko Denis,
> I opened a pull request at:
> `https://github.com/jenkinsci/pipeline-multibranch-defaults-plugin/pull/3`
>
> I was wondering if you still maintain the pipeline multibranch defautls plugin.  If not, can I be added as a maintainer of the plugin?
>
> Please reply to this email or comment in
> `https://github.com/jenkins-infra/repository-permissions-updater/pull/822`
> if you are OK with me being added as a maintainer.
>
> Thanks,
> SAM

**Comment by samrocketman** [comment]
@daniel-beck should I remove the original maintainer?  Since they have not been responsive.

**Comment by samrocketman** [comment]
The build failure has nothing to do with my addition.  Seems like a bug in the pipeline job.

**Comment by daniel-beck** [comment]
Build failure was due to a premature merge of another PR, and has long since been cleaned up.

**Comment by batmat** [comment]
Given this PR has been open quite long **and** even more importantly the repo seems indeed not actively maintained since soon 2 years, I'm going to merge this. 

Though @samrocketman it would probably have been preferrable to also send an email to the dev list as usual with the maintainer in CC, so that we double-make sure there's no answer. Sending a private email to the maintainer is not the usual/standard way to get a fastest approval/takeover. 

Anyway, @vaimr in case you can finally answer, feel free to do here or anywhere else.

Also, note for anyone watching: a PR here and merging it is *not* what gives people commit access. This only provides release permission for this GAV.  

The commit access part was just done on IRC a few seconds ago:

image

**Comment by samrocketman** [comment]
Ah I didn’t get the CC dev list part.

**Pull request merged**
