### PR TITLE
Add CloudBees colleagues to some plugins I maintain

### PR DESCRIPTION
**Pull request by Vlatombe**
- @ajard
- @aneveux
- @kerogers-cloudbees
- @amuniz

# Description

# Submitter checklist for adding or changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by batmat** [comment]
wrt. to 
image

@Vlatombe I assume these people will need GitHub access to the repositories too? (i.e. not just the deployment permission)

**Comment by timja** [comment]
> I assume these people will need GitHub access to the repositories too?

tbh it's a bit pointless that step, we just always assume they need it. ideally identity systems would be aligned / it would be done automatically as part of the PR.

**Comment by batmat** [comment]
@timja yeah, hacking on the team definition made me envision indeed how we could version all (most?) GH teams here and "apply" also GH permissions from RPU.

**Comment by batmat** [comment]
I've retriggered the CI build, all green now. Going to merge given the request comes from an existing maintainer. I will also handle the GH side as need be.

**Review by batmat — APPROVED** [review]

**Comment by batmat** [comment]
@Vlatombe I believe I've added all of the GH aliases to the two repository teams.

@aHenryJard
@aneveux
@kerogers-cloudbees
@amuniz please confirm you do have write access to these two repositories. Thanks!

**Pull request merged**
