### PR TITLE
add new plugin yml file https://github.com/jenkinsci/requests-plugin

### PR DESCRIPTION
**Pull request by trixmot**
# Description
https://github.com/jenkinsci/requests-plugin

https://github.com/jenkinsci/requests-plugin
# Submitter checklist for changing permissions
trixmot

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
Please fill out the check boxes, they are there for a reason :-)

**Comment by trixmot** [comment]
checked...

**Comment by slide** [comment]
The issue template has requests for information for you to fill out. Please read the prompts and fill out the details as requested.

**Comment by trixmot** [comment]
Can you please point me to the issue template that requires more info

**Comment by slide** [comment]
Click edit on your original comment (has Description and the check boxes) and read the content there. It has specific instructions.

**Comment by slide** [comment]
Looks like this user ` hasn't logged in to Artifactory (e.g., a Jenkins account like JIRA or the wiki uses):

`User name not known to Artifactory: jflynn`

**Comment by trixmot** [comment]
need to remove jflynn

**Pull request closed without merging**
