### PR TITLE
Adding developers

### PR DESCRIPTION
**Pull request by jeromepochat**
Adding:
* @bzzitsme
* @riliane
* @Pldi23
* @jeromepochat

### CODE REVIEW

**Comment by Wadeck** [comment]
Requesting approval from existing members, in this case at least @aneveux

**Review by aneveux — APPROVED** [review]

**Review by aneveux — APPROVED** [review]

**Comment by jeromepochat** [comment]
Validation step failed with "needs to log in to Artifactory and Jira".
I'm currently logged in both Artifactory and Jira.
Could you please re-trigger?

**Comment by timja** [comment]
> Validation step failed with "needs to log in to Artifactory and Jira". I'm currently logged in both Artifactory and Jira. Could you please re-trigger?

re-triggered, seems to have still failed

**Comment by jeromepochat** [comment]
Should all the added developers need to log in to Artifactory and Jira? or just myself as PR creator?

**Comment by Vlatombe** [comment]
@jeromepochat I think all users must log in at least once.

**Pull request merged**
