### PR TITLE
add cryptomove permission

### PR DESCRIPTION
**Pull request by shicholas**
# Description

Add permission to publish the Jenkins Plugin CryptoMove, which can hopefully be listed on the Jenkins web page. https://github.com/jenkinsci/cryptomove-plugin

Host Request: https://issues.jenkins-ci.org/browse/HOSTING-789

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
Please add a link to the hosting issue that was completed. This helps us keep track of things.

**Comment by shicholas** [comment]
@slide here you go https://issues.jenkins-ci.org/browse/HOSTING-789?jql=text%20~%20%22cryptomove%22 thank you!

**Comment by cryptomoovin** [comment]
@slide - can you please take a look at this screenshot? I thought this PR allowed me to have the proper permissions to publish versions?

Or do the versions get automatically published in CI? The docs aren't very clear on this. 

Thank you,

Captura de Pantalla 2019-06-19 a la(s) 08 48 41

**Comment by slide** [comment]
You use the `mvn release:prepare release:perform` command to do releases after setting up your settings.xml, you shouldn't be trying to upload manually. Did you follow this information on how to release? https://jenkins.io/doc/developer/publishing/releasing/

It also looks like your path is different for your plugin, something I did not catch when merging the PR. The yml file you submitted has org/jenkins-ci/plugins/ for the path, but it looks like your pom.xml has io.jenkins.plugins, these need to match up. You can submit a PR to the yml file to fix the path. Sorry for not catching that.

**Comment by cryptomoovin** [comment]
Yes I tried with that step and received an access denied error from the
Jenkins maven server so I tried with the UI.

The path mishap seems to be the cause of my issue. I'll submit a pr soon,
thank you.

**Pull request merged**
