### PR TITLE
added froque as maintainer to powershell plugin

### PR DESCRIPTION
**Pull request by froque**
# Description

The link to plugin repository: https://github.com/jenkinsci/powershell-plugin

pinging @chrisalbrecht for confirmation. 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by chrisalbrecht** [comment]
@froque all good!

**Comment by froque** [comment]
@slide anything else required ?

**Comment by froque** [comment]
@chrisalbrecht @slide I don't believe I have commit access to https://github.com/jenkinsci/powershell-plugin repository

**Comment by slide** [comment]
Fixed

**Pull request merged**
