### PR TITLE
 Enable CD for Cyberchief Security Scanner Plugin

### PR DESCRIPTION
**Pull request by ziontavera**
# Link to GitHub repository

https://github.com/jenkinsci/cyberchief-security-scanner-plugin

# Link to the PR enabling CD in plugin
https://github.com/jenkinsci/cyberchief-security-scanner-plugin/pull/2

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [ ] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [ ] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
You forgot to incrementalify the plugin: https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config

**Comment by ziontavera** [comment]
@NotMyFault Fixed :+1:

**Comment by ziontavera** [comment]
Hi @NotMyFault Thanks for merging the PR! May I know what steps I need to take next in order to release the plugin? I tried to follow the steps in this [document](https://www.jenkins.io/doc/developer/publishing/releasing-manually/), but Im getting an error regarding "not-setup-for-mrp"
image

**Comment by ziontavera** [comment]
Does it trigger the release if I added the label after I merged a PR? For example, this [PR](https://github.com/jenkinsci/cyberchief-security-scanner-plugin/pull/2)

**Comment by NotMyFault** [comment]
> Does it trigger the release if I added the label after I merged a PR? For example, this [PR](https://github.com/jenkinsci/cyberchief-security-scanner-plugin/pull/2)

If you put an interesting label on it, for sure :)

**Comment by ziontavera** [comment]
> > Does it trigger the release if I added the label after I merged a PR? For example, this [PR](https://github.com/jenkinsci/cyberchief-security-scanner-plugin/pull/2)
> 
> If you put an interesting label on it, for sure :)

Ahh there it is. Thank you so much! :raised_hands:  I can see it now in repo.jenkins-ci but is that all? Or are there other steps to take to have the plugin on https://plugins.jenkins.io/
image

**Pull request merged**
