### PR TITLE
Permission for uploading quamotion-cloud plugin

### PR DESCRIPTION
**Pull request by bartsaintgermain**
Add permissions for new quamotion-cloud plugin.
Git repo: https://github.com/jenkinsci/quamotion-cloud-plugin
Hosting issue: HOSTING-521 https://issues.jenkins-ci.org/browse/HOSTING-521

# Description

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by bartsaintgermain** [comment]
I did update the filename

**Comment by daniel-beck** [comment]
Please review the PR checklist, complete all applicable items, and check them off.

**Comment by bartsaintgermain** [comment]
I tried to fulfill all items. Hope these are fine.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/quamotion-cloud-plugin/blob/84fdb3a32d8debebf0ef899172cf066b6b2f6472/pom.xml#L10 contradicts https://github.com/jenkins-infra/repository-permissions-updater/pull/629/files#diff-4e99724ce8ccca27f09cb856e2412e3aR4

**Comment by bartsaintgermain** [comment]
Sorry, my bet. Is this fine now?

**Comment by daniel-beck** [comment]
@bartsaintgermain Sorry for the delay, I must have accidentally marked this PR as read, but not acted on it.

**Pull request merged**
