### PR TITLE
Create plugin-yet-another-build-visualizer

### PR DESCRIPTION
**Pull request by GLundh**
# Description
Yet Another Build Visualizer Plugin

* https://github.com/jenkinsci/yet-another-build-visualizer-plugin
* https://issues.jenkins-ci.org/browse/HOSTING-655

A Jenkins plugin that allows visualization of the build flow of upstream and downstream builds in Jenkins.

# Submitter checklist for changing permissions
### Always
* [x]  Add link to plugin/component Git repository in description above

### For a newly hosted plugin only
* [x]  Add link to resolved HOSTING issue in description above

### For a new permissions file only
* [x]  Make sure the file is created in `permissions/` directory
* [x]  `artifactId` (pom.xml) is used for `name` (permissions YAML file).
* [x]  [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
* [x]  Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)
* [x]  [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
* [x]  Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
* [x]  [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by GLundh** [comment]
Not sure why the build is failing. Does not seem related to the change.

**Comment by vrondakis** [comment]
You need to name the file "plugin-yet-another-build-visualizer.yml" not just "plugin-yet-another-build-visualizer"

**Comment by GLundh** [comment]
Doh! Thanks!

**Comment by GLundh** [comment]
The build was not triggered.(?) Seems like ci.jenkins.io was unreachable for a while. How do I retrigger the build?

**Comment by GLundh** [comment]
@batmat : Anything else that needs to be done to get this merged?

**Comment by GLundh** [comment]
@daniel-beck : I see other requests getting closed. Any thing I can do to move this and #906 along?

**Comment by GLundh** [comment]
@daniel-beck , @batmat, @oleg-nenashev : I would really, really appreciate if we could move this along. The plugin wiki is complete, but a week later, I still cannot issue an release. 

I see other PRs being merged. How is the prioritization done? Are there any additional steps I can take to get some movement here? Time wise it is costly to run an internal development branch because I cannot complete the move to Open Source. Planned releases needs to be scrapped and branches rebased.

Since us, plugin developers, are completely dependent on this step, it seems strange to give these PRs so little focus.

**Comment by daniel-beck** [comment]
> I see other PRs being merged. How is the prioritization done?

Don't know, I was simply too busy to review these recently. I generally try to treat them equally with exponential backoff the more often I need to request rework. In terms of recently merged PRs, I suspect the squeaky wheel gets the grease.

> Since us, plugin developers, are completely dependent on this step, it seems strange to give these PRs so little focus.

Yes, something like this shouldn't happen. Unfortunately, available time is finite, and sometimes routine work like this gets pre-empted.

**Pull request merged**
