### PR TITLE
add rymurphy/bparees as needed to openshift plugins

### PR DESCRIPTION
**Pull request by gabemontero**
updating developer list for openshift plugins

@jenkinsadmin PTAL

### CODE REVIEW

**Comment by gabemontero** [comment]
@oatmealraisin @bparees fyi

**Comment by bparees** [comment]
are we both on the login plugin?

**Comment by gabemontero** [comment]
you are ... @oatmealraisin isn't ... thought about it and then went conservative, but can add him if you like.

**Comment by bparees** [comment]
it's fine as is.

**Comment by daniel-beck** [comment]
`rymurphy` hasn't logged into Artifactory, so the entire change will only be applied when they do.

**Comment by oatmealraisin** [comment]
@daniel-beck sorry, I have logged in now. Thanks for the notice!

**Comment by daniel-beck** [comment]
Permission changes got applied.

**Pull request merged**
