### PR TITLE
Need permission to deploy reqtify-plugin

### PR DESCRIPTION
**Pull request by rpl17-alt**
# Link to GitHub repository

(https://github.com/jenkinsci/reqtify-plugin.git)

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@NKR`
- `@rpl17_alt`

This PR requests upload permissions for the `reqtify-plugin`. 
I need these permissions to be able to deploy new releases of the plugin to the Jenkins artifact repository. 
My Jenkins username is `your-jenkins-username`.

### CODE REVIEW

**Comment by rpl17-alt** [comment]
My Jenkins username is rpl17_alt
my github username is rpl17-alt

**Comment by MarkEWaite** [comment]
The Jenkins user account nkr8 needs to approve this addition of permission.  I believe the Jenkins user account nkr8 corresponds to GitHub account @NavnathKumbhar based on https://github.com/jenkinsci/reqtify-plugin/commits?author=NavnathKumbhar

@NavnathKumbhar do you approve this grant of release permission to Jenkins user account rpl17_alt ?

**Comment by MarkEWaite** [comment]
@rpl17-alt before you can be granted permission to release a plugin, you must login to two Jenkins services with your Jenkins account `rpl16_alt`.  Those two services are:

* https://issues.jenkins.io - the Jenkins issue tracker
* https://repo.jenkins-ci.org/ - the Jenkins artifact repository

Those instructions are included in the pull request template.  Unfortunately, you seem to have deleted the pull request template and replaced it with your own content.

**Comment by NavnathKumbhar** [comment]
> The Jenkins user account nkr8 needs to approve this addition of permission. I believe the Jenkins user account nkr8 corresponds to GitHub account @NavnathKumbhar based on https://github.com/jenkinsci/reqtify-plugin/commits?author=NavnathKumbhar
> 
> @NavnathKumbhar do you approve this grant of release permission to Jenkins user account rpl17_alt ?

Yes, I approve.

**Comment by rpl17-alt** [comment]
```
@rpl17-alt before you can be granted permission to release a plugin, you must login to two Jenkins services with your Jenkins account rpl16_alt. Those two services are:

https://issues.jenkins.io/ - the Jenkins issue tracker
https://repo.jenkins-ci.org/ - the Jenkins artifact repository
Those instructions are included in the pull request template. Unfortunately, you seem to have deleted the pull request template and replaced it with your own content.
```
>>
my jenkin id is rpl17_alt in your comment iy is rpl16_alt
nkr8 give me acess still i am getting error 403

**Comment by rpl17-alt** [comment]
now logged in

**Comment by MarkEWaite** [comment]
> ```
> @rpl17-alt before you can be granted permission to release a plugin, you must login to two Jenkins services with your Jenkins account rpl16_alt. Those two services are:
> 
> https://issues.jenkins.io/ - the Jenkins issue tracker
> https://repo.jenkins-ci.org/ - the Jenkins artifact repository
> Those instructions are included in the pull request template. Unfortunately, you seem to have deleted the pull request template and replaced it with your own content.
> ```
> 
> > >
> 
> my jenkin id is rpl17_alt in your comment iy is rpl16_alt nkr8 give me acess still i am getting error 403

Thanks for catching that mistake!  I've corrected it by pushing a new commit to the repository.  Refer to 9189d72542dabf6797068e976fd6d56d122227cd

**Comment by rpl17-alt** [comment]
This is new for me 
I have to do any action from my side before deploy? 
or Do you know when I will get access to deploy my plugin?

**Comment by MarkEWaite** [comment]
> This is new for me I have to do any action from my side before deploy? or Do you know when I will get access to deploy my plugin?

I don't see any action needed from you at this time.

You'll need to wait for the ci.jenkins.io server to be upgraded to Jenkins 2.462.1 and restarted.  We're in the process of releasing a security fix for Jenkins core as announced in the [security advisory](https://groups.google.com/g/jenkinsci-advisories/c/NkXElf7MmcI/m/bn2IY98xBAAJ).  Once that release is complete, ci.jenkins.io will be restarted and the job that evaluates this pull request will run.  When the job passes, then the maintainers of this repository will be able to merge your pull request.

**Pull request merged**
