### PR TITLE
Adopt Build-Blocker Plugin

### PR DESCRIPTION
**Pull request by hypery2k**
# Description

# Submitter checklist for changing permissions

see https://github.com/jenkinsci/build-blocker-plugin/pull/9#issuecomment-418135348

ping @fbelzunc

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Approval from @ffromm is also required AFAICT. 
Thread in the developer list: https://groups.google.com/forum/#!topic/jenkinsci-dev/lUMVgMmhHiE

**Comment by fbelzunc** [comment]
@hypery2k Thanks for adopting the plugin!

**Comment by oleg-nenashev** [comment]
@daniel-beck From what I see, @hypery2k didn't CC @ffromm  in the mailing list: https://groups.google.com/forum/#!topic/jenkinsci-dev/lUMVgMmhHiE . Do you consider the current state as a "best effort"? Or should other channels be used first?

**Comment by daniel-beck** [comment]
CCing someone in an email (or explaining why not, e.g. users.noreply.github.com) isn't too much to ask. (If we have docs that don't mention this, they need to be fixed, of course.)

**Comment by batmat** [comment]
Also:
image

This checkbox is not optional. It **must** be checked, though it seems good given the green PR build.

@hypery2k can you please provide a status update here? Thanks

**Comment by batmat** [comment]
Closing without reaction as per my last comment 2 weeks ago. Please reopen when/if you are available again to process this PR. Thanks!

**Pull request closed without merging**
