### PR TITLE
Add Phoenix Autotest Plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Hosting Ticket : https://issues.jenkins-ci.org/browse/HOSTING-468
Repo : https://github.com/jenkinsci/phoenix-autotest-plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Have you passed the checklist defined in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/.github/PULL_REQUEST_TEMPLATE.md ? I would recommend following the PR template

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Yes, already look over the checklist

**Comment by LinuxSuRen** [comment]
@oleg-nenashev What do I need to do? Just wait?

**Comment by daniel-beck** [comment]
The user `suren` does not exist in Artifactory. Please read this repo's readme again.

**Comment by daniel-beck** [comment]
Also, the path specified does not make sense combined with the artifactId.

Please see this repository's readme for instructions how these work.

**Pull request merged**
