### PR TITLE
Request to add user rfriedman as maintainer for ease-plugin

### PR DESCRIPTION
**Pull request by rufriedman**
# Description

I am requesting commit access for jenkins.io user "rfriedman" to https://github.com/jenkinsci/ease-plugin. I have spoken with one of the other maintainers, @oleksiyp, and he thinks he no longer has the ability to approve pull requests.

# Submitter checklist for changing permissions

### Always

- https://github.com/jenkinsci/ease-plugin

### When adding new uploaders (this includes newly created permissions files)

@oleksiyp
@kwilson6744

### CODE REVIEW

**Comment by kwilson6744** [comment]
I approve

**Comment by daniel-beck** [comment]
I recommend that @oleksiyp files an INFRA issue in Jira to get the permissions issue cleared up.

**Comment by batmat** [comment]
@daniel-beck did you also grant commit access? Thanks

**Comment by daniel-beck** [comment]
@batmat To whom?

**Comment by batmat** [comment]
to the requester, @rufriedman

**Comment by daniel-beck** [comment]
Ah. I read the initial comment wrong.

For reference, @kwilson6744 and @rufriedman, this PR grants release permission.

**Pull request merged**
