### PR TITLE
Add Openmake DeployHub Plugin

### PR DESCRIPTION
**Pull request by sbtaylor15**
# Description

https://github.com/jenkinsci/deployhub-plugin.git

# Submitter checklist for changing permissions

@sbtaylor15
@philgibbs

### Always

- [X] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [X] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [X] Make sure the file is created in `permissions/` directory
- [X] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [X] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@sbtaylor15 Please review the submitter checklist, it makes our job much easier. Thank you.

**Comment by sbtaylor15** [comment]
@daniel-beck I have completed the check-list.  Let me know if I have something setup incorrectly.

**Comment by sbtaylor15** [comment]
@daniel-beck try it now. I missed adding the file back in on the rename

**Comment by daniel-beck** [comment]
Hosting request: https://issues.jenkins-ci.org/browse/HOSTING-354

**Comment by daniel-beck** [comment]
There were no releases using the old ID, so no permissions file to remove and no IDs to blacklist.

**Pull request merged**
