### PR TITLE
Add nfalco as mantainer of dependency-check-plugin

### PR DESCRIPTION
**Pull request by nfalco79**
I would like to adopt/co-maintain the dependency-check-plugin, which is already maintained by @danile42 . Detailed eequest in jenkins google group.

https://github.com/jenkinsci/dependency-check-plugin

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1 from me

**Comment by nfalco79** [comment]
Just to have a complete overview of this request I post a link to the Google group discussion:
https://groups.google.com/g/jenkinsci-dev/c/pUde3PjmNLA

**Comment by nfalco79** [comment]
Any news

**Comment by timja** [comment]
Needs approval from @danile42 or to wait 2 weeks from the request being filed

**Review by NotMyFault — APPROVED** [review]
Looks good, waiting period is over without reaction from the maintainer.

Proceeding.

**Comment by nfalco79** [comment]
I suppose github repository permission are handled by this project automatically right?

**Comment by nfalco79** [comment]
ok than I will wait to get mantainer access for @nfalco79 to the dependency-check-plugin

**Comment by NotMyFault** [comment]
> Is JIRA default assegnee handled by this tool?

Yes, I'll assign you once I'm able to do that.

**Comment by NotMyFault** [comment]
@nfalco79 All set!

**Pull request merged**
