### PR TITLE
Added ClearCase UCM Object Oriented Library to Jenkins artifactory

### PR DESCRIPTION
**Pull request by MadsNielsen**
# Description
ClearCase Object Oriented library: COOL for short
https://github.com/Praqma/cool
# Submitter checklist for changing permissions
### Always

- [x] Add link to plugin/component Git repository in description above

### For new plugins
Hosting request is here: https://issues.jenkins-ci.org/browse/HOSTING-575

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by MadsNielsen** [comment]
Cool library. We're shutting down our own maven repo. We want to host this on jenkinsci.org.

@ReleasePraqma is the serviceuser and his account is praqma

**Comment by MadsNielsen** [comment]
@oleg-nenashev Oh, so the hosting requirements are true even for non-plugins as in just libraries?

**Comment by oleg-nenashev** [comment]
@MadsNielsen Yes. And it will be required to justify their value to the Jenkins project. If they are used in ClearCase UCM  plugin only, my recommendation would be to just put them as submodules or bundle code into the plugin.

**Comment by MadsNielsen** [comment]
@oleg-nenashev Awright.

**Comment by MadsNielsen** [comment]
@oleg-nenashev I was actually wrong, this plugin is also used in https://wiki.jenkins.io/display/JENKINS/Config+Rotator+Plugin. So we do have multiple uses of it among published Jenkins plugins.

I'll go ahead a create a HOSTING ticket for this.

**Comment by oleg-nenashev** [comment]
Yes, hosting is the best solution here IMHO.
I would recommend converting this library to API plugin, it would address all concerns IMHO

**Comment by oleg-nenashev** [comment]
kinda. Changing packaging to "hpi" actually

**Comment by MadsNielsen** [comment]
@oleg-nenashev OK :) ~ That i can do. It does make sense, i don't think many use the stand-alone jar anyways.

**Comment by MadsNielsen** [comment]
Ok @oleg-nenashev i've converted the cool library to an API (use jenkins parent and produce a .hpi file). The hosting request seems like something you create, as i cannot select a component for it.

**Comment by oleg-nenashev** [comment]
@MadsNielsen hmm, you should be able to create hosting requests

**Comment by oleg-nenashev** [comment]
The component there is "New Plugin Hosting Request" ;)

**Comment by MadsNielsen** [comment]
@oleg-nenashev Doh...sometimes you cannot see the forrest for all the trees. Added hosting request ticket... :P

**Comment by MadsNielsen** [comment]
Alright, i've modified the pom for the target plugin so that the artifact id is now `clearcase-ucm-api. It being a plugin is implied according to documentation. It's name is reported as `ClearCase UCM library for Jenkins Plugin`. 

I've updated the hosting request with a better name for the project on https://issues.jenkins-ci.org/browse/HOSTING-575. 

Hope this is enough :)

**Comment by MadsNielsen** [comment]
@oleg-nenashev I believe this is in order

**Pull request merged**
