### PR TITLE
Update permissions list for Code Dx plugin

### PR DESCRIPTION
**Pull request by baffles**
# Description

GitHub: https://github.com/jenkinsci/codedx-plugin

Just looking to prune the uploader list of folks who no longer work on this project.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### CODE REVIEW

**Comment by batmat** [comment]
@baffles can you please clarify why you would remove these people? 
From the Jenkins Project PoV, we need approval from these people to remove them FWIW. Please have them approve here.

Thanks

**Comment by daniel-beck** [comment]
Well, this has happened in the past, and we've done it by giving future former co-maintainers an opportunity to dispute the change. So, CC @ademartini and @leRadwan, who, by the way, still have commit access.

If you want to clean up GitHub permissions as well (currently 6 users), I recommend this be done as well, ideally through an INFRA issue in Jira.

**Comment by baffles** [comment]
Just cleaning up permissions; the folks listed no longer maintain the plugin. I do have an open INFRA issue (INFRA-1818) for GitHub permission cleanup/changes to go along with this as well.

**Comment by batmat** [comment]
I suppose we'll wait at least 15 days overall, somehow like the usual wait time for plugin adoption for the plugin process.

**Comment by daniel-beck** [comment]
As the requester here already is a maintainer, 11 days seems plenty. (In fact, I basically forgot about this one. 😅) And it's not like this is irreversible if needed.

**Comment by baffles** [comment]
Thanks!

**Pull request merged**
