### PR TITLE
Create plugin-reqtify.yml

### PR DESCRIPTION
**Pull request by NavnathKumbhar**
# Description

Github: https://github.com/jenkinsci/reqtify-plugin

Hosting issue: https://issues.jenkins-ci.org/browse/HOSTING-793

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by slide** [comment]
You checked a box but didn't provide the information. Please make sure to read the issue template and provide the requested information.

**Comment by NavnathKumbhar** [comment]
Updated plugin-reqtify.yml matching with checked items.

**Comment by NavnathKumbhar** [comment]
What is it mean by the status "Queued
All nodes of label ‘java’ are offline"?

**Comment by slide** [comment]
image

Please look at these items, one of them is ALWAYS. Since this is a new plugin, the second applies. 

As for the build, there were issues on ci.jenkins.io, they are now resolved.

**Comment by NavnathKumbhar** [comment]
Are we set to merge?

**Comment by slide** [comment]
No, have you not read my comments?

**Comment by NavnathKumbhar** [comment]
> No, have you not read my comments?

Hello Alex,
Sorry for the misunderstanding.
I updated the description field with respect to the checkbox : **"Add link to resolved HOSTING issue in description above"**

**Pull request merged**
