### PR TITLE
OC-117 Enable continuous deployment for plugin-clover

### PR DESCRIPTION
**Pull request by marek-parfianowicz**
# Link to GitHub repository

https://github.com/jenkinsci/clover-plugin

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

https://github.com/jenkinsci/clover-plugin/pull/34

and

https://github.com/jenkinsci/clover-plugin/blob/master/.github/workflows/B-release-jenkins-clover-plugin.yml

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
> > All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
> 
> mparfianowicz and marekparf works on issues.jenkins.io (/)
> 
> mparfianowicz and marekparf are blocked on repo.jenkins-ci.org (x)

Can't you log in with the same credentials you're using on Jira on artifactory?

**Comment by marek-parfianowicz** [comment]
I tried and I can't. I had a few invalid password attempts (I did not log in for a long time) so maybe my account was blocked?

**Comment by NotMyFault** [comment]
> so maybe my account was blocked?

Best to file an issue on the [helpdesk](https://github.com/jenkins-infra/helpdesk/issues/new?assignees=&labels=triage&projects=&template=1-report-issue.yml).

**Comment by marek-parfianowicz** [comment]
https://github.com/jenkinsci/clover-plugin/actions/runs/6411049291/job/17405672847

{noformat}
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project clover: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:clover:hpi:4.14.0-rc550.9e732fca_5ec9 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/clover/4.14.0-rc550.9e732fca_5ec9/clover-4.14.0-rc550.9e732fca_5ec9.hpi, status: 401 Unauthorized -> [Help 1]
{noformat}

The plugin builds fine, it stops on deployment, as expected.

Questions:

* Are there any naming requirements for actions? I haven't found anything about it in the docs. I named the action "B Release Jenkins Clover Plugin", but in examples I saw "CD".

* Is this necessary to have this hash after X.Y.Z number when doing a manual release? I understand it's required for automated releases, for incrementals. But what about explicit ones?

[clover-4.14.0-rc550.9e732fca_5ec9.hpi]

**Comment by NotMyFault** [comment]
To 1: No, the name of the workflow doesn't matter for its functionality, but "cd" is expected in various metrics and scores, like the plugin health score.

To 2: See the "Manually controlled prefix" part of https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config how to setup the files accordingly.

The PR linked is incomplete too.

**Comment by marek-parfianowicz** [comment]
Is this sufficient?

https://github.com/jenkinsci/clover-plugin/pull/47/files

**Comment by NotMyFault** [comment]
> Is this sufficient?

Yes.

If you like, you can make use of https://www.jenkins.io/doc/developer/publishing/requesting-hosting/#integrate-with-jira for https://github.com/jenkinsci/clover-plugin/pull/47/files#diff-101bec72d0f1f84e7290d113531bbd8c6aa355cdc9f456df255544bc0a2da0eaR5-R7, ignoring the Jira part and using openclover/clover URL 😉

**Review by NotMyFault — APPROVED** [review]

**Comment by marek-parfianowicz** [comment]
I'd like to keep the "OC-" prefix, even if I not use Jira. :) 

Thanks for reviewing my changes, I'll merge the PR #47 then.

**Pull request merged**
