### PR TITLE
Update plugin-multibranch-build-strategy-extension.yml

### PR DESCRIPTION
**Pull request by igalg**
enable cd

# Link to GitHub repository

# When modifying release permission

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [x] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [x] I have provided a link to the pull request in my plugin, which enables CD according to the documentation.
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by igalg** [comment]
https://github.com/jenkinsci/multibranch-build-strategy-extension-plugin/pull/18

**Comment by NotMyFault** [comment]
> NotMyFault   Hi i just wanted to be sure that the pr is waiting for review or for something else Thank's a lot Igal

I don't have the capacity to review a PR with a diff sizing +1.6k/-0.7k. Please link a PR enabling CD only.

**Comment by FrogDevelopper** [comment]
new PR was created with only changes for automatic release
https://github.com/jenkinsci/multibranch-build-strategy-extension-plugin/pull/19

**Comment by NotMyFault** [comment]
> new PR was created with only changes for automatic release [jenkinsci/multibranch-build-strategy-extension-plugin#19](https://github.com/jenkinsci/multibranch-build-strategy-extension-plugin/pull/19)

The PR linked is incomplete. The pom hasn't been incrementalified yet. Take a look at the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config) on how to do that.

**Comment by FrogDevelopper** [comment]
@NotMyFault 
Pom updated

**Review by NotMyFault — APPROVED** [review]

**Pull request merged**
