### PR TITLE
Request to add ACCELQ plugin to auto upload

### PR DESCRIPTION
**Pull request by accelq**
# Description
https://github.com/jenkinsci/accelq-ci-connect-plugin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When enabling automated releases (cd: true)
https://github.com/jenkinsci/accelq-ci-connect-plugin/commit/4ed1a51b6be2df5f7d51d7f93bc13c6af12745fc -Directly ran on main branch - hope this doesn't causes any issue.

So, the code is in the github repo itself, its just the way we package it
https://github.com/jenkinsci/accelq-ci-connect-plugin/tree/main/core

- [x] Add a link to the pull request, which enables continuous delivery for your plugin or component.  
Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly.

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory and Jira at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by NotMyFault** [comment]
@accelq Please include a link to the PR enabling CD in your plugin, as advised by this PR template.

**Comment by NotMyFault** [comment]
And if you are at it, make sure to remove https://github.com/jenkinsci/accelq-ci-connect-plugin/blob/4ed1a51b6be2df5f7d51d7f93bc13c6af12745fc/pom.xml#L79-L85

Currently you are distributing .jar files only, while Jenkins plugins expect a .hpi file too, causing to produce invalid plugin releases.

**Comment by accelq** [comment]
1. What is this PR link? I don't get it. As per the below screenshots it does not mention of any other PR.
image

2. It's a jar we use as a library for all our core functionalities, Uptil our previous releases this was fine, why does it need to be removed now?

**Comment by NotMyFault** [comment]
To 1)The link to the pr where you enable cd in your plugin relates to the pr where you committed the changes to prepare your plugin for CD, like incrementals and all other changes according to the docs.To 2)You used to publish hpi files before but stopped doing at a point. I asked for the rationale behind. If it's not a Jenkins plugin, it shouldn't be suffixed as plugin and outlines to be a plugin.Typically, libraries are setup differently, notably, you don't turn a plugin into a library. See my comment on the hpi removal.On 20. Apr 2023, at 12:21, accelQ Inc ***@***.***> wrote:﻿


What is this PR link? I don't get it. As per the below screenshots it does not mention of any other PR.



It's a jar we use as a library for all our core functionalities, Uptil our previous releases this was fine, why does it need to be removed now?

**Comment by halkeye** [comment]
> The link to the pr where you enable cd in your plugin relates to the pr where you committed the changes to prepare your plugin for CD, like incrementals and all other changes according to the docs.

I did find https://github.com/jenkinsci/accelq-ci-connect-plugin/commit/4ed1a51b6be2df5f7d51d7f93bc13c6af12745fc (which has githubRepo listed twice)

> To 2) You used to publish hpi files before but stopped doing at a point. I asked for the rationale behind. If it's not a Jenkins plugin, it shouldn't be suffixed as plugin and outlines to be a plugin.Typically, libraries are setup differently, notably, you don't turn a plugin into a library. See my comment on the hpi removal.

I don't think they are publishing a jar as far as I can tell, its just loading the jar from disk for compiling (from what I read last night, thats what system scope means)

**Comment by NotMyFault** [comment]
> I don't think they are publishing a jar as far as I can tell, its just loading the jar from disk for compiling (from what I read last night, thats what system scope means)

Then I fail to see what your concerns are?

**Comment by accelq** [comment]
Updated the docs. Please let me know if there are any more issues.
2. So earlier we used to deploy manually the plugin, but earlier I had raised a ticket concern that flow always fails and wanted to migrate to this automated flow, so ideally I think no code change should be required for the plugin.

**Comment by NotMyFault** [comment]
> core.jar is a dependency on the jenkins plugin. So it should be in POM right?

Right, could you include the link to the source code hosting this dependency is at, please?

**Comment by accelq** [comment]
So, the code is in the github repo itself, its just the way we package it
https://github.com/jenkinsci/accelq-ci-connect-plugin/tree/main/core

**Comment by accelq** [comment]
hi @NotMyFault is there anything more I can help with or can we merge this PR?

**Comment by NotMyFault** [comment]
> hi @NotMyFault is there anything more I can help with or can we merge this PR?

To facilitate an easier and faster review, you can provide a link to the PR preparing your plugin for releases via CD, as advised by the PR template and my prior comment.
Please take a look at the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/), how to setup the `.github` folder structure properly.

**Comment by accelq** [comment]
Hi, adding the PRs
https://github.com/jenkinsci/accelq-ci-connect-plugin/pull/18
https://github.com/jenkinsci/accelq-ci-connect-plugin/pull/17
https://github.com/jenkinsci/accelq-ci-connect-plugin/pull/16

**Pull request closed without merging**
