### PR TITLE
Replaced one of the  ec2 maintainer

### PR DESCRIPTION
**Pull request by thoulen**
# Description
Updated list of the Ec2 plugin maintainers (https://github.com/jenkinsci/ec2-plugin)

# Submitter checklist for changing permissions

### Always

- [ x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Dev list reference: https://groups.google.com/d/msg/jenkinsci-dev/xXM_gOT0Zf8/nOssbBRXEAAJ

CC @francisu

**Comment by francisu** [comment]
I was the only active maintainer until now. The others just did a little work but went away. I think you can safely remove them.

**Comment by francisu** [comment]
And it might be helpful to keep me on with commit access if you want, in case I do get a little time, but it's up to you.

**Comment by daniel-beck** [comment]
> commit access

This is releasing, not committing. https://jenkins.io/doc/developer/publishing/source-code-hosting/ has commit access (which I noted should probably be cleaned up).

**Comment by thoulen** [comment]
@francis for sure !

 I will open a ticket to clean the release part.

**Comment by daniel-beck** [comment]
@francisu Could you confirm that you should be removed as maintainer, and release permission revoked?

**Comment by francisu** [comment]
Yes. Thanks for checking.

**Pull request merged**
