### PR TITLE
postbuildscript permissions

### PR DESCRIPTION
**Pull request by dheid**
# Description

I would like to take over the maintenance of the Postbuildscript plugin (https://github.com/jenkinsci/postbuildscript-plugin) and want to merge the pull request https://github.com/jenkinsci/postbuildscript-plugin/pull/15 Please also provide me the Git access to the repository.

The previous maintainer was @gboissinot, but @daniel-beck  told me, that he doesn't maintain it any longer. On https://wiki.jenkins.io/display/JENKINS/PostBuildScript+Plugin the community is looking for a new maintainer. @gboissinot does not react to any mails currently.

My Jenkins community account name is dheid

# Submitter checklist for changing permissions

### Always

- [ x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
>  told me, that he doesn't maintain it any longer

FTR (sort of), private email conversation around May 2016.

**Comment by daniel-beck** [comment]
Looking through my email archives, there was also https://groups.google.com/d/msg/jenkinsci-dev/xWAfH6wKZMY/s4iAcjzYAAAJ -- perhaps that would be someone who could collaborate with you here? Of course, given that they didn't respond anymore, they might have lost interest.

**Comment by daniel-beck** [comment]
@dheid Please note that postbuildscript is currently blacklisted. Once you published the release containing your changes, file a PR removing it from https://github.com/jenkinsci/backend-update-center2/blob/master/src/main/resources/artifact-ignores.properties, and updating the version range for https://github.com/jenkins-infra/backend-update-center2/blob/master/src/main/resources/warnings.json

**Comment by dheid** [comment]
Thanks for your help! I applied the two changes here: https://github.com/jenkins-infra/backend-update-center2/pull/169

**Pull request merged**
