### PR TITLE
Replace existing members

### PR DESCRIPTION
**Pull request by benoittgt**
# Description

Please @chrsvl or @rsfez. Could you approve new developpers (@benoittgt, @RobertAudi and @Benlenem)?

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

I don't know how to log in Artifactory. I have no access to it.

### CODE REVIEW

**Comment by chrsvl** [comment]
No problem, we can approve

**Comment by rsfez** [comment]
Sure, enjoy.

**Comment by benoittgt** [comment]
Thanks @dblock  I'm sorry I don't understand why I don't have GitHub rights now.

In the documentation, it is mentioned 
> Its permissions system is independent of GitHub's, and we limit which users (identified by the Jenkins LDAP account, same as wiki and JIRA) are allowed to upload which artifacts.

But I don't get it.

**Comment by oleg-nenashev** [comment]
@benoittgt GitHub permissions granted. When transferring ownership, it needs to be handled via a separate ChatOps logic now.

**Pull request merged**
