### PR TITLE
Add greybird as maintainer of claim plugin

### PR DESCRIPTION
**Pull request by Greybird**
# Description

I'd like to be added as a maintainer of https://github.com/jenkinsci/claim-plugin.
Current maintainer,  @ki82 agreed to share the ownership on this [mailing list thread](https://groups.google.com/d/msg/jenkinsci-dev/-XEbuDgB9SI/c7LwtO3cBQAJ)

🔺 I will also need the github access to the repository.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@ki82's email is a bit ambiguous, so I would like a direct response in this thread confirming he meant to give you permission to release.

**Comment by ki82** [comment]
I give Arnaud the permission to release the claim-plugin.

**Comment by Greybird** [comment]
@daniel-beck Thanks, however, it seems I do not have write access to the repository.
Do you need me to do something else?

**Comment by daniel-beck** [comment]
@Greybird Sorry about that, missed the note in the PR comment when I merged this.

**Comment by Greybird** [comment]
Thanks!

**Comment by Greybird** [comment]
Sorry to bother you again.
It seems I cannot push directly to the repo, so when I launch a release from maven as git push fail.
Maybe the "write access" permissions I asked were not what I expected ?

**Comment by daniel-beck** [comment]
They are. Probably just a problem with your setup, ask on the dev list.

**Pull request merged**
