### PR TITLE
Add aheritier as maintainer of cloudbees-jenkins-advisor

### PR DESCRIPTION
**Pull request by aheritier**
# Description

I'm actively working on Advisor server in my daily job at CloudBees, I would like to be able to maintain the plugin too [jenkinsci/cloudbees-jenkins-advisor-plugin](https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin/).

I'm asking to have the admin role on the repository + the permission to upload/release the plugin

I suppose that @Evildethow , @kwhetstone  and even @kohsuke will confirm

Thanks

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

#### Merge permission to GitHub repository
- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @evildethow @kwhetstone @kohsuke please approve

**Comment by kohsuke** [comment]
I think we have all the +1s we need, but just in case, my +1 as well.

**Comment by slide** [comment]
Just waiting on the build...

**Comment by oleg-nenashev** [comment]
It already starts feeling like Windows update...

**Pull request merged**
