### PR TITLE
Update plugin-zephyr-enterprise-test-management.yml

### PR DESCRIPTION
**Pull request by mohan-zephyr**
# Description

Requesting uploader permission.

Plugin Git repository [zephyr-enterprise-test-management-plugin](https://github.com/jenkinsci/zephyr-enterprise-test-management-plugin.git)

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

@zeedeveloper

### CODE REVIEW

**Comment by mohan-zephyr** [comment]
request release permission

**Comment by daniel-beck** [comment]
We use a PR template for a reason. I need you to confirm the relevant parts are done (and edit the PR comment accordingly) before I spend time on this.

**Comment by mohan-zephyr** [comment]
Hi Daniel, Though your PR template is a bit confusing for a first timer, I've done my best to update it. Please merge the PR. Thank you.

**Comment by daniel-beck** [comment]
@mohan-zephyr 

> is a bit confusing for a first timer

Feel free to suggest changes/improvements. Note that on GitHub, you can 'check' checkboxes, so no need to rephrase things you do. It can look like the 'Submitter checklist' e.g. here:
https://github.com/jenkinsci/blueocean-plugin/pull/646

**Comment by daniel-beck** [comment]
@zephyrmohan Please note that repeated 'approvals' by a user who doesn't have this permission already, looks like a second account by the same person, and has never committed to the repo, doesn't help at all. In fact, it makes this request look fishy.

@mohan-zephyr 

>  I have used the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name.
> I confirm I have logged in to Artifactory at least once.

The user doesn't exist in Artifactory, so one or both of these statements are false.

**Comment by mohan-zephyr** [comment]
@daniel-beck 
The user doesn't exist in Artifactory, so one or both of these statements are false.

My Gitgub user id is "mohan-zephyr" and my Jenkins CI user id is zephyrmohan. Please look at the modified YAML file and I mentioned "zephyrmohan". I dont see this is a limitation by you (We can use different ID's for Github and Jenkns CI as per your doc). 

The user "zephyrmohan" does exist in Artifactory.

**Comment by daniel-beck** [comment]
@mohan-zephyr 

>  I dont see this is a limitation by you (We can use different ID's for Github and Jenkns CI as per your doc).

True.

> The user "zephyrmohan" does exist in Artifactory.

It does not. I looked a bit further and `mohanzephyr` exists, did you mean to use that?

**Comment by mohan-zephyr** [comment]
@daniel-beck 

My apologies for the confusion caused and the time wasted. Yes, I indeed wanted to use "mohanzephyr". I now corrected it in the YAML file. Please review & merge it. Thank you.

**Pull request merged**
