### PR TITLE
Add justinharringa as dev for release process

### PR DESCRIPTION
**Pull request by justinharringa**
# Description
Adding myself as a releaser/contributor for the [Chatter Notifier Plugin](https://github.com/jenkinsci/chatter-notifier-plugin/). I've also opened a [request to move this plugin to ci.jenkins.io](https://issues.jenkins-ci.org/browse/INFRA-1191). @superfell is the current release dev.

# Permissions pull request checklist

### Always

- [X] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [X] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [X] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [X] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
@superfell please approve or reject this change that will allow @justinharringa to release the plugin.

**Comment by superfell** [comment]
Approved.

**Comment by justinharringa** [comment]
@daniel-beck is this all I need to do in order to execute my `mvn release:prepare release:perform`?

I'm getting:
`ERROR: Permission to jenkinsci/chatter-notifier-plugin.git denied to justinharringa`

**Comment by daniel-beck** [comment]
@justinharringa You did not have commit access to `jenkinsci/chatter-notifier-plugin`. Based on @superfell's response, I've granted you access.

Note that committing to Git and uploading to Artifactory are separately maintained permissions, and nowhere did you mention that you still need both.

**Comment by justinharringa** [comment]
Gotcha. Sorry about that. Thanks!

**Pull request merged**
