### PR TITLE
Update plugin-cerberus-testing.yml

### PR DESCRIPTION
**Pull request by vertigo17**
# Description

The GitHub repo is an already existing jenkinsci repo: 
https://github.com/jenkinsci/cerberus-testing-plugin
The purpose of the request is only to add my Jenkins account (vertigo17) to the authorized account that can upload the new release.
This is to fix the error I got when uploading my new release of the plugin:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project cerberus-testing: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:cerberus-testing:hpi:1.0.5 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/cerberus-testing/1.0.5/cerberus-testing-1.0.5.hpi, ReasonPhrase: . -> [Help 1]`

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please complete the items in the checklist that apply, checking off all the ones you completed.

**Comment by vertigo17** [comment]
That should be fine now.

**Comment by daniel-beck** [comment]
It is not clear to me that you should have this permission, please have @nicodeur approve this request.

**Comment by vertigo17** [comment]
OK, I will ask @nicodeur to comment the PR in order to confirm the grant permission.

**Comment by nicodeur** [comment]
Hello,

I confirm @vertigo17 can have permission on https://github.com/jenkinsci/cerberus-testing-plugin

**Comment by daniel-beck** [comment]
@nicodeur To clarify, Git permissions are already granted. This is for releasing new versions of the plugin.

**Comment by nicodeur** [comment]
Yes, indeed, it's for releasing new versions. Can you make it or give me the procedure please ?

**Comment by daniel-beck** [comment]
@nicodeur Done; your response just wasn't clear whether you approve.

**Comment by vertigo17** [comment]
Thanks @daniel-beck , so that means I can make a new attempt to release and error message:
`Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/cerberus-testing/1.0.5/cerberus-testing-1.0.5.hpi`
should disappear.
Correct ?

**Comment by daniel-beck** [comment]
@vertigo17 Yes.

**Comment by vertigo17** [comment]
Worked perfectly.
1.1 has been released.

**Pull request merged**
