### PR TITLE
Update plugin-templating-engine.yml

### PR DESCRIPTION
**Pull request by cokieffebah**
# Description
adding cokieffebah as developer to https://github.com/jenkinsci/templating-engine-plugin
@steven-terrana 

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by slide** [comment]
Looks like you haven't logged in to Artifactory as specified on the wiki

```
Exception in thread "main" java.lang.IllegalStateException: User name not known to Artifactory: cokieffebah
```

**Comment by cokieffebah** [comment]
Thanks,

Logged in shortly there after.  Do I have to redo the pull request or will the system try again

Thanks again

Carlos

**Comment by slide** [comment]
Close and reopen for build

**Comment by slide** [comment]
Waiting for authorization from @steven-terrana

**Comment by cokieffebah** [comment]
He should be back either tomorrow or mid this week.   I actually work near him.  Sorry about that.

**Comment by slide** [comment]
Sounds good, thanks for the update

**Comment by steven-terrana** [comment]
approved!

**Pull request merged**
