### PR TITLE
Add Nestor Salceda (nestorsalceda) to the sysdig-secure plugin

### PR DESCRIPTION
**Pull request by nestorsalceda**
Hello,

I'm one of the maintainers of Sysdig Secure plugin and I would like to cut a new release, so that I'm requesting permissons to upload it to artifactory.

Thank you!

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
As one of the maintainers, I approve

**Review by yJunS — APPROVED** [review]

**Comment by nestorsalceda** [comment]
Hey,

Is there anything else I can do on my side to get this merged?

Thank you!

**Comment by timja** [comment]
One of these maintainers to approve:

image

**Comment by nestorsalceda** [comment]
> One of these maintainers to approve:
> 
> image

Okey, I think that @markyjackson-taulia already approved. AFAIK he is _jequals5_, isn't he?

**Comment by timja** [comment]
if marky can confirm that, the joys of separate systems for identity...

**Review by markyjackson-taulia — APPROVED** [review]

**Pull request merged**
