### PR TITLE
Managing Permissions - updating maintainers of zephyr-enterprise-test-management plugin

### PR DESCRIPTION
**Pull request by SmartBearAshutosh**
# Link to GitHub repository

https://github.com/jenkinsci/zephyr-enterprise-test-management-plugin

# When modifying release permission

List the GitHub usernames of the users who should have commit permissions below:
- `@SmartBearAshutosh`
- `@AshwaniKrSh`

This is needed in order to cut releases of the plugin or component.

If you are modifying the release permission of your plugin or component, fill out the following checklist:

```[tasklist]
### Release permission checklist (for submitters)
- [x] The usernames of the users added to the "developers" section in the .yml file are the same the users use to log in to [accounts.jenkins.io](https://accounts.jenkins.io/).
- [x] All users added have logged in to [Artifactory](https://repo.jenkins-ci.org/) and [Jira](https://issues.jenkins.io/) once.
- [ ] I have mentioned an [existing team member](https://github.com/orgs/jenkinsci/teams) of the plugin or component team to approve this request.
```

## When enabling automated releases (cd: true)

Follow the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) to ensure, your pull request is set up properly. Don't merge it yet.  
In case of changes requested by the hosting team, an open PR facilitates future reviews, without derailing work across multiple PRs.

### Link to the PR enabling CD in your plugin

```[tasklist]
### CD checklist (for submitters)
- [ ] I have provided a link to the pull request in my plugin, which enables CD according to the documentation. 
```

```[tasklist]
### Reviewer checklist
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.
```
There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it.

### CODE REVIEW

**Comment by SmartBearAshutosh** [comment]
Now logged in to Jira. Please retrigger the build
@alecharp @slide @NotMyFault @batmat @oleg-nenashev @timja

**Comment by timja** [comment]
Can you get someone who already has access to approve it please?

**Comment by AshwaniKrSh** [comment]
@timja, an existing team member left the company as of now we are only one, can you help us process this further?

**Comment by timja** [comment]
Are any of these people still around?
image

image

can you login to the zeedeveloper account (looks like a service account)?

**Comment by AshwaniKrSh** [comment]
@timja any update on this? Please help us to resolve this asap.

**Comment by timja** [comment]
It is waiting for approval from @swapna-vemula

**Comment by AshwaniKrSh** [comment]
@timja Can you help with this, @swapna-vemula didn't receive any review request, is there anything different we need to check for the review?

**Comment by swapna-vemula** [comment]
I approve

**Comment by timja** [comment]
Invites sent, can you please go to https://github.com/jenkinsci to accept the invite

**Pull request merged**
