### PR TITLE
chore: pin GitHub actions with their SHA-1 instead of their version number

### PR DESCRIPTION
**Pull request by lemeurherve**
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
can we leave actions/checkout and actions/setup-java with a pinned version instead please? to reduce dependabot pull requests I already get a million of them...

**Comment by NotMyFault** [comment]
Preferably, only 3rd party actions should be pinned. Official actions administered by GH, such as `actions/`, or our actions, should stay as-is, no?

**Comment by lemeurherve** [comment]
> can we leave actions/checkout and actions/setup-java with a pinned version instead please? to reduce dependabot pull requests I already get a million of them...

I'm currently updating my script to let only the version in the comment.

> Preferably, only 3rd party actions should be pinned. Official actions administered by GH, such as `actions/`, or our actions, should stay as-is, no?

I don't see why, and it would also be more complicated as I would need to exclude these modifications.

**Comment by dduportal** [comment]
> can we leave actions/checkout and actions/setup-java with a pinned version instead please? to reduce dependabot pull requests I already get a million of them...

For any action, is dependabot triggered on each SHA change (e.g. on each commit on the action's source repository) or is it the same as before (e.g. triggered when a new release is available, but the SHA is updated along with the commented version)?

**Comment by timja** [comment]
> > can we leave actions/checkout and actions/setup-java with a pinned version instead please? to reduce dependabot pull requests I already get a million of them...
> 
> For any action, is dependabot triggered on each SHA change (e.g. on each commit on the action's source repository) or is it the same as before (e.g. triggered when a new release is available, but the SHA is updated along with the commented version)?

No it's when it's released but we pin to e.g. version 3 rather than 3.10 as we are happy to receive minor updates to these actions.

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
> No it's when it's released but we pin to e.g. version 3 rather than 3.10 as we are happy to receive minor updates to these actions.

Make sense. Looks like that if we do not "sha-ized" the `actions/` that would help (ref. https://github.com/jenkins-infra/helpdesk/issues/3402#issuecomment-1443706544).

FWIW, if we ran into a 3rd party GHA too verbose, we can always tell dependabot to ignore the patch or minor versions: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the- dependabot.yml-file#ignore

**Pull request merged**
