### PR TITLE
Add mathworks-polyspace plugin

### PR DESCRIPTION
**Pull request by pascal-brand38**
Signed-off-by: Pascal Brand <pascal.brand38@gmail.com>

# Description

Adding Mathworks Polyspace plugin
Here is our github repository: https://github.com/jenkinsci/mathworks-polyspace-plugin
The hosting request is here: https://issues.jenkins-ci.org/browse/HOSTING-723
At the moment maintainers are @pascal-brand38, @cpreve, and @sbobin

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by pascal-brand38** [comment]
Hi,

I can't find the source of the CI issue. Error is:

    [FATAL] Non-resolvable parent POM for io.jenkins.infra:repository-permissions-updater:1.0-SNAPSHOT: Could not transfer artifact org.jenkins-ci:jenkins:pom:1.36 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): /home/jenkins/.m2/repository/org/jenkins-ci/jenkins/1.36/jenkins-1.36.pom.part.lock (No such file or directory) and 'parent.relativePath' points at wrong local POM @ line 3, column 13

Anyone has a hint?

**Comment by slide** [comment]
It seems like a maven dependency is not available...most likely some infra issue.

**Comment by pascal-brand38** [comment]
Looks like everything is fine now.
@slide do I miss anything to get it merged?
Thanks, Pascal.

**Comment by slide** [comment]
The first two items in the checklist are checked, but the links aren't present, can you please add them?

**Comment by pascal-brand38** [comment]
@slide Done. thanks.

**Pull request merged**
