### PR TITLE
Distribute configurator for foreman-host-configurator

### PR DESCRIPTION
**Pull request by olivergondza**
# Description

Enable pushing one more jar + add me as a developer.

https://github.com/jenkinsci/foreman-node-sharing-plugin

@scoheb, please approve my developer status.

# Submitter checklist for changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### CODE REVIEW

**Comment by olivergondza** [comment]
I am wondering if I need to whitelist path for `<packaging>pom</packaging>` parent.

**Comment by daniel-beck** [comment]
@olivergondza Yes. There are plenty of `pom-whatever.yml` files in this repo already.

**Comment by olivergondza** [comment]
Thanks, updated.

**Comment by daniel-beck** [comment]
@olivergondza Unfortunately it's not that easy. It's basically `for each path: allowedPaths += path + "/*/" + name`, i.e. you can now upload:

- `org/jenkins-ci/plugins/nodesharing/foreman-node-sharing/*/foreman-node-sharing`
- `org/jenkins-ci/plugins/nodesharing/parent/*/foreman-node-sharing`
- `org/jenkins-ci/plugins/nodesharing/configurator/*/foreman-node-sharing`

I know, annoying, but haven't had time to improve this. You need to add two more files, one for the parent pom, one for configuration.

(The rationale is that otherwise some evil plugin maintainer could upload `org/jenkins-ci/plugins/nodesharing/configurator/5.0/mailer/mailer-5.0.hpi` and all this permissions control would be a waste of time.)

**Comment by olivergondza** [comment]
I see, I hope this is correct.

**Comment by daniel-beck** [comment]
@olivergondza Looks reasonable, so just waiting for @scoheb to approve.

(If something goes wrong, please just ping me on IRC.)

**Comment by scoheb** [comment]
100% approve

**Pull request merged**
