### PR TITLE
Add mtgibbs to fortify-on-demand-uploader 

### PR DESCRIPTION
**Pull request by mtgibbs**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Was there a problem with the PR template or why is the PR description empty?

**Comment by mtgibbs** [comment]
I didn't see a template or a contributing.md.  Nor do I know what sort of specifics you want to prove ownership of the plugin on the jenkinsci org.

https://github.com/jenkinsci/fortify-on-demand-uploader-plugin

**Comment by mtgibbs** [comment]
Here we go, I don't know why I didn't see it on PR.  @daniel-beck 

# Description

Adding mtgibbs as maintainer to the fortify-on-demand-uploader-plugin package.

https://github.com/jenkinsci/fortify-on-demand-uploader-plugin

The existing maintainer is no longer actively developing the latest version of the plugin.

@ryancblack for verification anyways.  Though you can check my direct commit permissions on the repository as I was tailoring the POM to getting ready to publish the package.

# Permissions pull request checklist

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

**Comment by mtgibbs** [comment]
@daniel-beck 

On a side note, the PULL_REQUEST_TEMPLATE file isn't marked as .md, which might have been why it didn't auto-populate?  I've never used this feature before so I can't say without testing it.

**Comment by daniel-beck** [comment]
@mtgibbs Don't know -- I've had a few PRs already that included it, hence my confusion. I'll add the `.md` extension, thanks for the hint.

**Comment by daniel-beck** [comment]
I'll give @ryancblack a day or so to deny this request, otherwise I'll grant it -- as you're admin on the repo it should be unusual to not also grant release permission. Unfortunately Ryan didn't give much context other than that changed jobs but intended to continue working on it.

**Comment by ryancblack** [comment]
@daniel-beck - please grant release, and thank you! I do intend to assist however @mtgibbs is point on this project moving forward.

**Comment by daniel-beck** [comment]
@ryancblack Okay, thanks!

@mtgibbs Should we make you default assignee for JIRA issues as well?

**Pull request merged**
