### PR TITLE
add new maintainer to dependency-track-plugin

### PR DESCRIPTION
**Pull request by sephiroth-j**
# Description
replacing @stevespringett with @sephiroth-j as maintainer for https://github.com/jenkinsci/dependency-track-plugin

see [JENKINS-64102](https://issues.jenkins-ci.org/browse/JENKINS-64102) and https://groups.google.com/g/jenkinsci-dev/c/UdBhQnr4FNg

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [x] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [x] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [x] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please use the PR template, follow its instructions, and check off all items that apply.

**Comment by sephiroth-j** [comment]
> Please use the PR template, follow its instructions, and check off all items that apply.

I have updated the initial comment of the PR. The template was not used when editing the file directly using Github web.

**Comment by oleg-nenashev** [comment]
> Validation — sephirothj needs to login to artifactory

**Comment by oleg-nenashev** [comment]
Retriggered the PR just in case. Updating the GitHub permissions

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
I confirm that @sephiroth-j has not logged into Artifactory yet

**Comment by sephiroth-j** [comment]
> 
> 
> I confirm that @sephiroth-j has not logged into Artifactory yet

I have logged in about 4 hours ago. That's why i closed and re-opened the PR 3 hours ago.

The check is okay now, so I guest it just took a "bit" longer than the proposed one hour to sync my login.

**Pull request merged**
