### PR TITLE
Added permission for absint-astree-plugin.

### PR DESCRIPTION
**Pull request by bschommer**

### CODE REVIEW

**Comment by jherter** [comment]
"Confirming comment".

**Comment by oleg-nenashev** [comment]
👍

**Comment by daniel-beck** [comment]
@jherter @bschommer  Please note that this permission will not be granted until these users have logged in to Artifactory at https://repo.jenkins-ci.org once (at least jherter has not yet). Afterwards it may still take a while for the permission to be effective. See https://github.com/jenkins-infra/repository-permissions-updater#requesting-permissions

**Comment by bschommer** [comment]
We updated the users to include the correct ones, see PR #31.

**Pull request merged**
